In [1]:
import numpy as np
import pandas as pd
import pandas as df

#Today we will sae about excell file and read them sheet wise

In [2]:
import pandas as pd

# Adjust settings to display all columns without truncation
pd.set_option('display.max_columns', None)  # Display all columns
pd.set_option('display.max_rows', None)     # Display all rows if needed
pd.set_option('display.width', None)        # Adjust display width automatically

# Load the Excel file and specify the sheet name
df_movies = pd.read_excel("movies_db.xlsx", sheet_name="movies")

# Display the first 5 rows
df_movies.head()

,movie_id,title,industry,release_year,imdb_rating,studio,language_id
0,101,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,3
1,102,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,5
2,103,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,5
3,104,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,5
4,105,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,5

In [3]:
import pandas as pd

# Adjust settings to display all columns without truncation
pd.set_option('display.max_columns', None)  # Display all columns
pd.set_option('display.max_rows', None)     # Display all rows if needed
pd.set_option('display.width', None)        # Adjust display width automatically

# Load the Excel file and specify the sheet name
df_movies = pd.read_excel("movies_db.xlsx", sheet_name="movies")

# Display the all rows
df_movies

,movie_id,title,industry,release_year,imdb_rating,studio,language_id
0,101,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,3
1,102,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,5
2,103,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,5
3,104,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,5
4,105,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,5
5,106,Sholay,Bollywood,1975,8.1,United Producers,1
6,107,Dilwale Dulhania Le Jayenge,Bollywood,1995,8.0,Yash Raj Films,1
7,108,3 Idiots,Bollywood,2009,8.4,Vinod Chopra Films,1
8,109,Kabhi Khushi Kabhie Gham,Bollywood,2001,7.4,Dharma Productions,1
9,110,Bajirao Mastani,Bollywood,2015,7.2,NaN,1
10,111,The Shawshank Redemption,Hollywood,1994,9.3,Castle Rock Entertainment,5
11,112,Inception,Hollywood,2010,8.8,Warner Bros. Pictures,5
12,113,Interstellar,Hollywood,2014,8.6,Warner Bros. Pictures,5
13,115,The Pursuit of Happyness,Hollywood,2006,8.0,Columbia Pictures,5
14,116,Gladiator,Hollywood,2000,8.5,Universal Pictures,5
15,117,Titanic,Hollywood,1997,7.9,Paramount Pictures,5
16,118,It's a Wonderful Life,Hollywood,1946,8.6,Liberty Films,5
17,119,Avatar,Hollywood,2009,7.8,20th Century Fox,5
18,120,The Godfather,Hollywood,1972,9.2,Paramount Pictures,5
19,121,The Dark Knight,Hollywood,2008,9.0,Syncopy,5
20,122,Schindler's List,Hollywood,1993,9.0,Universal Pictures,5
21,123,Jurassic Park,Hollywood,1993,8.2,Universal Pictures,5
22,124,Parasite,Hollywood,2019,8.5,NaN,5
23,125,Avengers: Endgame,Hollywood,2019,8.4,Marvel Studios,5
24,126,Avengers: Infinity War,Hollywood,2018,8.4,Marvel Studios,5
25,127,Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,7
26,128,Taare Zameen Par,Bollywood,2007,8.3,NaN,1
27,129,Munna Bhai M.B.B.S.,Bollywood,2003,8.1,Vinod Chopra Productions,1
28,130,PK,Bollywood,2014,8.1,Vinod Chopra Films,1
29,131,Sanju,Bollywood,2018,NaN,Vinod Chopra Films,1
30,132,Pushpa: The Rise - Part 1,Bollywood,2021,7.6,Mythri Movie Makers,2
31,133,RRR,Bollywood,2022,8.0,DVV Entertainment,2
32,134,Baahubali: The Beginning,Bollywood,2015,8.0,Arka Media Works,2
33,135,The Kashmir Files,Bollywood,2022,8.3,Zee Studios,1
34,136,Bajrangi Bhaijaan,Bollywood,2015,8.1,Salman Khan Films,1
35,137,Captain America: The First Avenger,Hollywood,2011,6.9,Marvel Studios,5
36,138,Captain America: The Winter Soldier,Hollywood,2014,7.8,Marvel Studios,5
37,139,Race 3,Bollywood,2018,1.9,Salman Khan Films,1
38,140,Shershaah,Bollywood,2021,8.4,Dharma Productions,1

In [4]:
import pandas as pd

# Adjust settings to display all columns without truncation
pd.set_option('display.max_columns', None)  # Display all columns
pd.set_option('display.max_rows', None)     # Display all rows if needed
pd.set_option('display.width', None)        # Adjust display width automatically

# Load the Excel file and specify the sheet name
df_financials = pd.read_excel("movies_db.xlsx", sheet_name="financials")

# Display the all rows
df_financials

    movie_id    budget   revenue       unit currency
0        101      1.00      12.5   Billions      INR
1        102    200.00     954.8   Millions      USD
2        103    165.00     644.8   Millions       $$
3        104    180.00     854.0   Millions  Dollars
4        105    250.00     670.0   Millions      USD
5        107    400.00    2000.0   Millions      INR
6        108    550.00    4000.0   Millions      INR
7        109    390.00    1360.0   Millions      INR
8        110      1.40       3.5   Billions      INR
9        111     25.00      73.3   Millions      USD
10       113    165.00     701.8   Millions      USD
11       114    205.00     365.3   Millions      USD
12       115     55.00     307.1   Millions      USD
13       116    103.00     460.5   Millions      USD
14       117    200.00    2202.0   Millions      USD
15       118      3.18       3.3   Millions      USD
16       119    237.00    2847.0   Millions      USD
17       120      7.20     291.0   Millions      USD
18       121    185.00    1006.0   Millions      USD
19       122     22.00     322.2   Millions      USD
20       123     63.00    1046.0   Millions      USD
21       124     15.50     263.1   Millions      USD
22       125    400.00    2798.0   Millions      USD
23       126    400.00    2048.0   Millions      USD
24       127  70000.00  100000.0  Thousands      INR
25       128    120.00    1350.0   Millions      INR
26       129    100.00     410.0   Millions      INR
27       130    850.00    8540.0   Millions      INR
28       131      1.00       5.9   Billions      INR
29       132      2.00       3.6   Billions      INR
30       133      5.50      12.0   Billions      INR
31       134      1.80       6.5   Billions      INR
32       135    250.00    3409.0   Millions      INR
33       136    900.00   11690.0   Millions      INR
34       137    216.70     370.6   Millions      USD
35       138    177.00     714.4   Millions      USD
36       139      1.80       3.1   Billions      INR
37       140    500.00     950.0   Millions      INR
38       406     30.00     350.0   Millions      INR
39       412    160.00     836.8   Millions      USD

In [5]:
import pandas as pd

# Adjust settings to display all columns without truncation
pd.set_option('display.max_columns', None)  # Display all columns
pd.set_option('display.max_rows', None)     # Display all rows if needed
pd.set_option('display.width', None)        # Adjust display width automatically

# Load the Excel file and specify the sheet name
df_actors = pd.read_excel("movies_db.xlsx", sheet_name="actors")

# Display the all rows
df_actors

    actor_id                   name  birth_year
0         50                   Yash        1986
1         51            Sanjay Dutt        1959
2         52   Benedict Cumberbatch        1976
3         53        Elizabeth Olsen        1989
4         54        Chris Hemsworth        1983
5         55        Natalie Portman        1981
6         56         Tom Hiddleston        1981
7         57       Amitabh Bachchan        1942
8         58          Jaya Bachchan        1948
9         59         Shah Rukh Khan        1965
10        60                  Kajol        1974
11        61             Aamir Khan        1965
12        62            R. Madhavan        1970
13        63          Sharman Joshi        1979
14        64         Hrithik Roshan        1974
15        65          Ranveer Singh        1985
16        66       Deepika Padukone        1986
17        67            Tim Robbins        1958
18        68         Morgan Freeman        1937
19        69      Leonardo DiCaprio        1974
20        70           Ken Watanabe        1959
21        71    Matthew McConaughey        1969
22        72          Anne Hathaway        1982
23        73  John David Washington        1984
24        74       Robert Pattinson        1986
25        75             Will Smith        1968
26        76        Thandiwe Newton        1972
27        77          Russell Crowe        1964
28        78        Joaquin Phoenix        1974
29        79           Kate Winslet        1975
30        80          James Stewart        1908
31        81             Donna Reed        1921
32        82        Sam Worthington        1976
33        83            Zoe Saldana        1978
34        84          Marlon Brando        1924
35        85              Al Pacino        1940
36        86         Christian Bale        1974
37        87           Heath Ledger        1979
38        88            Liam Neeson        1952
39        89           Ben Kingsley        1943
40        90              Sam Neill        1947
41        91             Laura Dern        1967
42        92           Song Kang-ho        1967
43        93           Lee Sun-kyun        1975
44        94      Robert Downey Jr.        1965
45        95            Chris Evans        1981
46       150          Kanu Banerjee        1905
47       151        Karuna Banerjee        1919
48       152        Darsheel Safary        1997
49       153             Sunil Dutt        1929
50       154         Anushka Sharma        1988
51       155          Ranbir Kapoor        1982
52       156             Allu Arjun        1982
53       157          Fahadh Faasil        1982
54       158     N. T. Rama Rao Jr.        1983
55       159             Ram Charan        1985
56       160                Prabhas        1979
57       161         Rana Daggubati        1984
58       162     Mithun Chakraborty        1950
59       163            Anupam Kher        1955
60       164            Salman Khan        1965
61       165    Nawazuddin Siddiqui        1967
62       166        Tommy Lee Jones        1946
63       167         Sebastian Stan        1982
64       168            Anil Kapoor        1956
65       169      Sidharth Malhotra        1985
66       170           Kiara Advani        1991

In [6]:
import pandas as pd

# Adjust settings to display all columns without truncation
pd.set_option('display.max_columns', None)  # Display all columns
pd.set_option('display.max_rows', None)     # Display all rows if needed
pd.set_option('display.width', None)        # Adjust display width automatically

# Load the Excel file and specify the sheet name
df_movie_actor = pd.read_excel("movies_db.xlsx", sheet_name="movie_actor")

# Display the all rows
df_movie_actor

    movie_id  actor_id
0        101        50
1        101        51
2        102        52
3        102        53
4        103        54
5        103        55
6        103        56
7        104        54
8        104        56
9        105        54
10       105        55
11       106        57
12       106        58
13       107        59
14       107        60
15       108        61
16       108        62
17       108        63
18       109        59
19       109        57
20       109        64
21       110        65
22       110        66
23       111        67
24       111        68
25       112        69
26       112        70
27       113        71
28       113        72
29       114        73
30       114        74
31       115        75
32       115        76
33       116        77
34       116        78
35       117        69
36       117        79
37       118        80
38       118        81
39       119        82
40       119        83
41       120        84
42       120        85
43       121        86
44       121        87
45       122        88
46       122        89
47       123        90
48       123        91
49       124        92
50       124        93
51       125        94
52       125        95
53       125        54
54       126        94
55       126        95
56       126        54
57       127       150
58       127       151
59       128        61
60       128       152
61       129        51
62       129       153
63       130        61
64       130       154
65       131       155
66       131       154
67       132       156
68       132       157
69       133       158
70       133       159
71       134       160
72       134       161
73       135       162
74       135       163
75       136       164
76       136       165
77       137        95
78       137       166
79       138        95
80       138       167
81       139       164
82       139       168
83       140       169
84       140       170

In [7]:
import pandas as pd

# Adjust settings to display all columns without truncation
pd.set_option('display.max_columns', None)  # Display all columns
pd.set_option('display.max_rows', None)     # Display all rows if needed
pd.set_option('display.width', None)        # Adjust display width automatically

# Load the Excel file and specify the sheet name
df_languages = pd.read_excel("movies_db.xlsx", sheet_name="languages")

# Display the all rows
df_languages

   language_id      name
0            1     Hindi
1            2    Telugu
2            3   Kannada
3            4     Tamil
4            5   English
5            6    French
6            7   Bengali
7            8  Gujarati

#Now we will see in financial sheet where currency wrote like $$,USD,Dollars, but our target is to convert one type currency so LIKE USD.

In [9]:
import numpy as np
import pandas as pd

# Adjust settings to display all columns without truncation
pd.set_option('display.max_columns', None)  # Display all columns
pd.set_option('display.max_rows', None)     # Display all rows if needed
pd.set_option('display.width', None)        # Adjust display width automatically



def std_curr(x):
    if x == '$$' or x == 'Dollars':
        return "USD"
    return x 

df_financials = pd.read_excel("movies_db.xlsx", sheet_name= "financials",
                              
                              converters= {'currency': std_curr})
df_financials

    movie_id    budget   revenue       unit currency
0        101      1.00      12.5   Billions      INR
1        102    200.00     954.8   Millions      USD
2        103    165.00     644.8   Millions      USD
3        104    180.00     854.0   Millions      USD
4        105    250.00     670.0   Millions      USD
5        107    400.00    2000.0   Millions      INR
6        108    550.00    4000.0   Millions      INR
7        109    390.00    1360.0   Millions      INR
8        110      1.40       3.5   Billions      INR
9        111     25.00      73.3   Millions      USD
10       113    165.00     701.8   Millions      USD
11       114    205.00     365.3   Millions      USD
12       115     55.00     307.1   Millions      USD
13       116    103.00     460.5   Millions      USD
14       117    200.00    2202.0   Millions      USD
15       118      3.18       3.3   Millions      USD
16       119    237.00    2847.0   Millions      USD
17       120      7.20     291.0   Millions      USD
18       121    185.00    1006.0   Millions      USD
19       122     22.00     322.2   Millions      USD
20       123     63.00    1046.0   Millions      USD
21       124     15.50     263.1   Millions      USD
22       125    400.00    2798.0   Millions      USD
23       126    400.00    2048.0   Millions      USD
24       127  70000.00  100000.0  Thousands      INR
25       128    120.00    1350.0   Millions      INR
26       129    100.00     410.0   Millions      INR
27       130    850.00    8540.0   Millions      INR
28       131      1.00       5.9   Billions      INR
29       132      2.00       3.6   Billions      INR
30       133      5.50      12.0   Billions      INR
31       134      1.80       6.5   Billions      INR
32       135    250.00    3409.0   Millions      INR
33       136    900.00   11690.0   Millions      INR
34       137    216.70     370.6   Millions      USD
35       138    177.00     714.4   Millions      USD
36       139      1.80       3.1   Billions      INR
37       140    500.00     950.0   Millions      INR
38       406     30.00     350.0   Millions      INR
39       412    160.00     836.8   Millions      USD

#Data Joining

#INNER JOIN

#let assume client want to saw the movie financial situation

In [11]:
import pandas as pd

# Adjust settings to display all columns without truncation
pd.set_option('display.max_columns', None)  # Display all columns
pd.set_option('display.max_rows', None)     # Display all rows if needed
pd.set_option('display.width', None)        # Adjust display width automatically

# Load the Excel file
file_path = 'movies_db.xlsx'

# Load the two sheets into separate DataFrames
df_movies = pd.read_excel(file_path, sheet_name='movies')
df_financials = pd.read_excel(file_path, sheet_name='financials')

# Perform an inner join on a common column (e.g., director_id)
merged_df = pd.merge(df_movies, df_financials, on='movie_id', how='inner')

# Display the merged DataFrame
merged_df

,movie_id,title,industry,release_year,imdb_rating,studio,language_id,budget,revenue,unit,currency
0,101,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,3,1.00,12.5,Billions,INR
1,102,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,5,200.00,954.8,Millions,USD
2,103,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,5,165.00,644.8,Millions,$$
3,104,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,5,180.00,854.0,Millions,Dollars
4,105,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,5,250.00,670.0,Millions,USD
5,107,Dilwale Dulhania Le Jayenge,Bollywood,1995,8.0,Yash Raj Films,1,400.00,2000.0,Millions,INR
6,108,3 Idiots,Bollywood,2009,8.4,Vinod Chopra Films,1,550.00,4000.0,Millions,INR
7,109,Kabhi Khushi Kabhie Gham,Bollywood,2001,7.4,Dharma Productions,1,390.00,1360.0,Millions,INR
8,110,Bajirao Mastani,Bollywood,2015,7.2,NaN,1,1.40,3.5,Billions,INR
9,111,The Shawshank Redemption,Hollywood,1994,9.3,Castle Rock Entertainment,5,25.00,73.3,Millions,USD
10,113,Interstellar,Hollywood,2014,8.6,Warner Bros. Pictures,5,165.00,701.8,Millions,USD
11,115,The Pursuit of Happyness,Hollywood,2006,8.0,Columbia Pictures,5,55.00,307.1,Millions,USD
12,116,Gladiator,Hollywood,2000,8.5,Universal Pictures,5,103.00,460.5,Millions,USD
13,117,Titanic,Hollywood,1997,7.9,Paramount Pictures,5,200.00,2202.0,Millions,USD
14,118,It's a Wonderful Life,Hollywood,1946,8.6,Liberty Films,5,3.18,3.3,Millions,USD
15,119,Avatar,Hollywood,2009,7.8,20th Century Fox,5,237.00,2847.0,Millions,USD
16,120,The Godfather,Hollywood,1972,9.2,Paramount Pictures,5,7.20,291.0,Millions,USD
17,121,The Dark Knight,Hollywood,2008,9.0,Syncopy,5,185.00,1006.0,Millions,USD
18,122,Schindler's List,Hollywood,1993,9.0,Universal Pictures,5,22.00,322.2,Millions,USD
19,123,Jurassic Park,Hollywood,1993,8.2,Universal Pictures,5,63.00,1046.0,Millions,USD
20,124,Parasite,Hollywood,2019,8.5,NaN,5,15.50,263.1,Millions,USD
21,125,Avengers: Endgame,Hollywood,2019,8.4,Marvel Studios,5,400.00,2798.0,Millions,USD
22,126,Avengers: Infinity War,Hollywood,2018,8.4,Marvel Studios,5,400.00,2048.0,Millions,USD
23,127,Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,7,70000.00,100000.0,Thousands,INR
24,128,Taare Zameen Par,Bollywood,2007,8.3,NaN,1,120.00,1350.0,Millions,INR
25,129,Munna Bhai M.B.B.S.,Bollywood,2003,8.1,Vinod Chopra Productions,1,100.00,410.0,Millions,INR
26,130,PK,Bollywood,2014,8.1,Vinod Chopra Films,1,850.00,8540.0,Millions,INR
27,131,Sanju,Bollywood,2018,NaN,Vinod Chopra Films,1,1.00,5.9,Billions,INR
28,132,Pushpa: The Rise - Part 1,Bollywood,2021,7.6,Mythri Movie Makers,2,2.00,3.6,Billions,INR
29,133,RRR,Bollywood,2022,8.0,DVV Entertainment,2,5.50,12.0,Billions,INR
30,134,Baahubali: The Beginning,Bollywood,2015,8.0,Arka Media Works,2,1.80,6.5,Billions,INR
31,135,The Kashmir Files,Bollywood,2022,8.3,Zee Studios,1,250.00,3409.0,Millions,INR
32,136,Bajrangi Bhaijaan,Bollywood,2015,8.1,Salman Khan Films,1,900.00,11690.0,Millions,INR
33,137,Captain America: The First Avenger,Hollywood,2011,6.9,Marvel Studios,5,216.70,370.6,Millions,USD
34,138,Captain America: The Winter Soldier,Hollywood,2014,7.8,Marvel Studios,5,177.00,714.4,Millions,USD
35,139,Race 3,Bollywood,2018,1.9,Salman Khan Films,1,1.80,3.1,Billions,INR
36,140,Shershaah,Bollywood,2021,8.4,Dharma Productions,1,500.00,950.0,Millions,INR

#So export the file

In [12]:
merged_df.to_excel("movies_merged.xlsx", sheet_name= "merged movies", index=False)

#LEFT JOIN

In [13]:
merged_df02 = pd.merge(df_movies, df_financials, on='movie_id', how='left')
merged_df02

,movie_id,title,industry,release_year,imdb_rating,studio,language_id,budget,revenue,unit,currency
0,101,K.G.F: Chapter 2,Bollywood,2022,8.4,Hombale Films,3,1.00,12.5,Billions,INR
1,102,Doctor Strange in the Multiverse of Madness,Hollywood,2022,7.0,Marvel Studios,5,200.00,954.8,Millions,USD
2,103,Thor: The Dark World,Hollywood,2013,6.8,Marvel Studios,5,165.00,644.8,Millions,$$
3,104,Thor: Ragnarok,Hollywood,2017,7.9,Marvel Studios,5,180.00,854.0,Millions,Dollars
4,105,Thor: Love and Thunder,Hollywood,2022,6.8,Marvel Studios,5,250.00,670.0,Millions,USD
5,106,Sholay,Bollywood,1975,8.1,United Producers,1,NaN,NaN,NaN,NaN
6,107,Dilwale Dulhania Le Jayenge,Bollywood,1995,8.0,Yash Raj Films,1,400.00,2000.0,Millions,INR
7,108,3 Idiots,Bollywood,2009,8.4,Vinod Chopra Films,1,550.00,4000.0,Millions,INR
8,109,Kabhi Khushi Kabhie Gham,Bollywood,2001,7.4,Dharma Productions,1,390.00,1360.0,Millions,INR
9,110,Bajirao Mastani,Bollywood,2015,7.2,NaN,1,1.40,3.5,Billions,INR
10,111,The Shawshank Redemption,Hollywood,1994,9.3,Castle Rock Entertainment,5,25.00,73.3,Millions,USD
11,112,Inception,Hollywood,2010,8.8,Warner Bros. Pictures,5,NaN,NaN,NaN,NaN
12,113,Interstellar,Hollywood,2014,8.6,Warner Bros. Pictures,5,165.00,701.8,Millions,USD
13,115,The Pursuit of Happyness,Hollywood,2006,8.0,Columbia Pictures,5,55.00,307.1,Millions,USD
14,116,Gladiator,Hollywood,2000,8.5,Universal Pictures,5,103.00,460.5,Millions,USD
15,117,Titanic,Hollywood,1997,7.9,Paramount Pictures,5,200.00,2202.0,Millions,USD
16,118,It's a Wonderful Life,Hollywood,1946,8.6,Liberty Films,5,3.18,3.3,Millions,USD
17,119,Avatar,Hollywood,2009,7.8,20th Century Fox,5,237.00,2847.0,Millions,USD
18,120,The Godfather,Hollywood,1972,9.2,Paramount Pictures,5,7.20,291.0,Millions,USD
19,121,The Dark Knight,Hollywood,2008,9.0,Syncopy,5,185.00,1006.0,Millions,USD
20,122,Schindler's List,Hollywood,1993,9.0,Universal Pictures,5,22.00,322.2,Millions,USD
21,123,Jurassic Park,Hollywood,1993,8.2,Universal Pictures,5,63.00,1046.0,Millions,USD
22,124,Parasite,Hollywood,2019,8.5,NaN,5,15.50,263.1,Millions,USD
23,125,Avengers: Endgame,Hollywood,2019,8.4,Marvel Studios,5,400.00,2798.0,Millions,USD
24,126,Avengers: Infinity War,Hollywood,2018,8.4,Marvel Studios,5,400.00,2048.0,Millions,USD
25,127,Pather Panchali,Bollywood,1955,8.3,Government of West Bengal,7,70000.00,100000.0,Thousands,INR
26,128,Taare Zameen Par,Bollywood,2007,8.3,NaN,1,120.00,1350.0,Millions,INR
27,129,Munna Bhai M.B.B.S.,Bollywood,2003,8.1,Vinod Chopra Productions,1,100.00,410.0,Millions,INR
28,130,PK,Bollywood,2014,8.1,Vinod Chopra Films,1,850.00,8540.0,Millions,INR
29,131,Sanju,Bollywood,2018,NaN,Vinod Chopra Films,1,1.00,5.9,Billions,INR
30,132,Pushpa: The Rise - Part 1,Bollywood,2021,7.6,Mythri Movie Makers,2,2.00,3.6,Billions,INR
31,133,RRR,Bollywood,2022,8.0,DVV Entertainment,2,5.50,12.0,Billions,INR
32,134,Baahubali: The Beginning,Bollywood,2015,8.0,Arka Media Works,2,1.80,6.5,Billions,INR
33,135,The Kashmir Files,Bollywood,2022,8.3,Zee Studios,1,250.00,3409.0,Millions,INR
34,136,Bajrangi Bhaijaan,Bollywood,2015,8.1,Salman Khan Films,1,900.00,11690.0,Millions,INR
35,137,Captain America: The First Avenger,Hollywood,2011,6.9,Marvel Studios,5,216.70,370.6,Millions,USD
36,138,Captain America: The Winter Soldier,Hollywood,2014,7.8,Marvel Studios,5,177.00,714.4,Millions,USD
37,139,Race 3,Bollywood,2018,1.9,Salman Khan Films,1,1.80,3.1,Billions,INR
38,140,Shershaah,Bollywood,2021,8.4,Dharma Productions,1,500.00,950.0,Millions,INR

#Right Join

In [14]:
merged_df03 = pd.merge(df_movies, df_financials, on='movie_id', how='right')
merged_df03

,movie_id,title,industry,release_year,imdb_rating,studio,language_id,budget,revenue,unit,currency
0,101,K.G.F: Chapter 2,Bollywood,2022.0,8.4,Hombale Films,3.0,1.00,12.5,Billions,INR
1,102,Doctor Strange in the Multiverse of Madness,Hollywood,2022.0,7.0,Marvel Studios,5.0,200.00,954.8,Millions,USD
2,103,Thor: The Dark World,Hollywood,2013.0,6.8,Marvel Studios,5.0,165.00,644.8,Millions,$$
3,104,Thor: Ragnarok,Hollywood,2017.0,7.9,Marvel Studios,5.0,180.00,854.0,Millions,Dollars
4,105,Thor: Love and Thunder,Hollywood,2022.0,6.8,Marvel Studios,5.0,250.00,670.0,Millions,USD
5,107,Dilwale Dulhania Le Jayenge,Bollywood,1995.0,8.0,Yash Raj Films,1.0,400.00,2000.0,Millions,INR
6,108,3 Idiots,Bollywood,2009.0,8.4,Vinod Chopra Films,1.0,550.00,4000.0,Millions,INR
7,109,Kabhi Khushi Kabhie Gham,Bollywood,2001.0,7.4,Dharma Productions,1.0,390.00,1360.0,Millions,INR
8,110,Bajirao Mastani,Bollywood,2015.0,7.2,NaN,1.0,1.40,3.5,Billions,INR
9,111,The Shawshank Redemption,Hollywood,1994.0,9.3,Castle Rock Entertainment,5.0,25.00,73.3,Millions,USD
10,113,Interstellar,Hollywood,2014.0,8.6,Warner Bros. Pictures,5.0,165.00,701.8,Millions,USD
11,114,NaN,NaN,NaN,NaN,NaN,NaN,205.00,365.3,Millions,USD
12,115,The Pursuit of Happyness,Hollywood,2006.0,8.0,Columbia Pictures,5.0,55.00,307.1,Millions,USD
13,116,Gladiator,Hollywood,2000.0,8.5,Universal Pictures,5.0,103.00,460.5,Millions,USD
14,117,Titanic,Hollywood,1997.0,7.9,Paramount Pictures,5.0,200.00,2202.0,Millions,USD
15,118,It's a Wonderful Life,Hollywood,1946.0,8.6,Liberty Films,5.0,3.18,3.3,Millions,USD
16,119,Avatar,Hollywood,2009.0,7.8,20th Century Fox,5.0,237.00,2847.0,Millions,USD
17,120,The Godfather,Hollywood,1972.0,9.2,Paramount Pictures,5.0,7.20,291.0,Millions,USD
18,121,The Dark Knight,Hollywood,2008.0,9.0,Syncopy,5.0,185.00,1006.0,Millions,USD
19,122,Schindler's List,Hollywood,1993.0,9.0,Universal Pictures,5.0,22.00,322.2,Millions,USD
20,123,Jurassic Park,Hollywood,1993.0,8.2,Universal Pictures,5.0,63.00,1046.0,Millions,USD
21,124,Parasite,Hollywood,2019.0,8.5,NaN,5.0,15.50,263.1,Millions,USD
22,125,Avengers: Endgame,Hollywood,2019.0,8.4,Marvel Studios,5.0,400.00,2798.0,Millions,USD
23,126,Avengers: Infinity War,Hollywood,2018.0,8.4,Marvel Studios,5.0,400.00,2048.0,Millions,USD
24,127,Pather Panchali,Bollywood,1955.0,8.3,Government of West Bengal,7.0,70000.00,100000.0,Thousands,INR
25,128,Taare Zameen Par,Bollywood,2007.0,8.3,NaN,1.0,120.00,1350.0,Millions,INR
26,129,Munna Bhai M.B.B.S.,Bollywood,2003.0,8.1,Vinod Chopra Productions,1.0,100.00,410.0,Millions,INR
27,130,PK,Bollywood,2014.0,8.1,Vinod Chopra Films,1.0,850.00,8540.0,Millions,INR
28,131,Sanju,Bollywood,2018.0,NaN,Vinod Chopra Films,1.0,1.00,5.9,Billions,INR
29,132,Pushpa: The Rise - Part 1,Bollywood,2021.0,7.6,Mythri Movie Makers,2.0,2.00,3.6,Billions,INR
30,133,RRR,Bollywood,2022.0,8.0,DVV Entertainment,2.0,5.50,12.0,Billions,INR
31,134,Baahubali: The Beginning,Bollywood,2015.0,8.0,Arka Media Works,2.0,1.80,6.5,Billions,INR
32,135,The Kashmir Files,Bollywood,2022.0,8.3,Zee Studios,1.0,250.00,3409.0,Millions,INR
33,136,Bajrangi Bhaijaan,Bollywood,2015.0,8.1,Salman Khan Films,1.0,900.00,11690.0,Millions,INR
34,137,Captain America: The First Avenger,Hollywood,2011.0,6.9,Marvel Studios,5.0,216.70,370.6,Millions,USD
35,138,Captain America: The Winter Soldier,Hollywood,2014.0,7.8,Marvel Studios,5.0,177.00,714.4,Millions,USD
36,139,Race 3,Bollywood,2018.0,1.9,Salman Khan Films,1.0,1.80,3.1,Billions,INR
37,140,Shershaah,Bollywood,2021.0,8.4,Dharma Productions,1.0,500.00,950.0,Millions,INR
38,406,NaN,NaN,NaN,NaN,NaN,NaN,30.00,350.0,Millions,INR
39,412,NaN,NaN,NaN,NaN,NaN,NaN,160.00,836.8,Millions,USD

In [15]:
df = pd.read_csv("weather_data.csv")
df

         day  temperature  windspeed   event
0        NaN          NaN        NaN     NaN
1   1/4/2017          NaN        9.0   Sunny
2   1/5/2017         28.0        NaN    Snow
3   1/6/2017          NaN        7.0     NaN
4   1/7/2017         32.0        NaN    Rain
5   1/8/2017          NaN        NaN   Sunny
6   1/9/2017          NaN        NaN     NaN
7  1/10/2017         34.1        8.1  Cloudy
8  1/11/2017         40.0       12.0   Sunny

#Nan means Null values

In [16]:
type(df['day'][0])

float

#Convert Date Format

In [17]:
df = pd.read_csv("weather_data.csv", parse_dates= ['day'])
df

         day  temperature  windspeed   event
0        NaT          NaN        NaN     NaN
1 2017-01-04          NaN        9.0   Sunny
2 2017-01-05         28.0        NaN    Snow
3 2017-01-06          NaN        7.0     NaN
4 2017-01-07         32.0        NaN    Rain
5 2017-01-08          NaN        NaN   Sunny
6 2017-01-09          NaN        NaN     NaN
7 2017-01-10         34.1        8.1  Cloudy
8 2017-01-11         40.0       12.0   Sunny

#NULL or Missing Value Replace

In [18]:
new_df = df.fillna(0) #replace by 0
new_df

                   day  temperature  windspeed   event
0                    0          0.0        0.0       0
1  2017-01-04 00:00:00          0.0        9.0   Sunny
2  2017-01-05 00:00:00         28.0        0.0    Snow
3  2017-01-06 00:00:00          0.0        7.0       0
4  2017-01-07 00:00:00         32.0        0.0    Rain
5  2017-01-08 00:00:00          0.0        0.0   Sunny
6  2017-01-09 00:00:00          0.0        0.0       0
7  2017-01-10 00:00:00         34.1        8.1  Cloudy
8  2017-01-11 00:00:00         40.0       12.0   Sunny

In [19]:
new_df.head()

                   day  temperature  windspeed  event
0                    0          0.0        0.0      0
1  2017-01-04 00:00:00          0.0        9.0  Sunny
2  2017-01-05 00:00:00         28.0        0.0   Snow
3  2017-01-06 00:00:00          0.0        7.0      0
4  2017-01-07 00:00:00         32.0        0.0   Rain

#Empty Cell Value fill by different value

In [20]:
df = df.fillna({
    'temperature': df.temperature.mean(),
    'windspeed': df.windspeed.max(),
    'event': "No Event"
})
df

         day  temperature  windspeed     event
0        NaT       33.525       12.0  No Event
1 2017-01-04       33.525        9.0     Sunny
2 2017-01-05       28.000       12.0      Snow
3 2017-01-06       33.525        7.0  No Event
4 2017-01-07       32.000       12.0      Rain
5 2017-01-08       33.525       12.0     Sunny
6 2017-01-09       33.525       12.0  No Event
7 2017-01-10       34.100        8.1    Cloudy
8 2017-01-11       40.000       12.0     Sunny

#Forward Fill

#Forward Fill
Here value replace by previous value

In [21]:
df.ffill()

         day  temperature  windspeed     event
0        NaT       33.525       12.0  No Event
1 2017-01-04       33.525        9.0     Sunny
2 2017-01-05       28.000       12.0      Snow
3 2017-01-06       33.525        7.0  No Event
4 2017-01-07       32.000       12.0      Rain
5 2017-01-08       33.525       12.0     Sunny
6 2017-01-09       33.525       12.0  No Event
7 2017-01-10       34.100        8.1    Cloudy
8 2017-01-11       40.000       12.0     Sunny

#BackWard Fill

In [22]:
df.bfill()

         day  temperature  windspeed     event
0 2017-01-04       33.525       12.0  No Event
1 2017-01-04       33.525        9.0     Sunny
2 2017-01-05       28.000       12.0      Snow
3 2017-01-06       33.525        7.0  No Event
4 2017-01-07       32.000       12.0      Rain
5 2017-01-08       33.525       12.0     Sunny
6 2017-01-09       33.525       12.0  No Event
7 2017-01-10       34.100        8.1    Cloudy
8 2017-01-11       40.000       12.0     Sunny

In [23]:
df.dropna()

         day  temperature  windspeed     event
1 2017-01-04       33.525        9.0     Sunny
2 2017-01-05       28.000       12.0      Snow
3 2017-01-06       33.525        7.0  No Event
4 2017-01-07       32.000       12.0      Rain
5 2017-01-08       33.525       12.0     Sunny
6 2017-01-09       33.525       12.0  No Event
7 2017-01-10       34.100        8.1    Cloudy
8 2017-01-11       40.000       12.0     Sunny

In [24]:
df.dropna(how= 'all')

         day  temperature  windspeed     event
0        NaT       33.525       12.0  No Event
1 2017-01-04       33.525        9.0     Sunny
2 2017-01-05       28.000       12.0      Snow
3 2017-01-06       33.525        7.0  No Event
4 2017-01-07       32.000       12.0      Rain
5 2017-01-08       33.525       12.0     Sunny
6 2017-01-09       33.525       12.0  No Event
7 2017-01-10       34.100        8.1    Cloudy
8 2017-01-11       40.000       12.0     Sunny

In [25]:
#If row value null 2 columns, then that row will dismiss by this method
df.dropna(thresh= 2)

         day  temperature  windspeed     event
0        NaT       33.525       12.0  No Event
1 2017-01-04       33.525        9.0     Sunny
2 2017-01-05       28.000       12.0      Snow
3 2017-01-06       33.525        7.0  No Event
4 2017-01-07       32.000       12.0      Rain
5 2017-01-08       33.525       12.0     Sunny
6 2017-01-09       33.525       12.0  No Event
7 2017-01-10       34.100        8.1    Cloudy
8 2017-01-11       40.000       12.0     Sunny

In [26]:
df.describe()

                       day  temperature  windspeed
count                    8     9.000000   9.000000
mean   2017-01-07 12:00:00    33.525000  10.677778
min    2017-01-04 00:00:00    28.000000   7.000000
25%    2017-01-05 18:00:00    33.525000   9.000000
50%    2017-01-07 12:00:00    33.525000  12.000000
75%    2017-01-09 06:00:00    33.525000  12.000000
max    2017-01-11 00:00:00    40.000000  12.000000
std                    NaN     3.064056   2.045591

In [27]:
df['temperature'].value_counts()

temperature
33.525    5
28.000    1
32.000    1
34.100    1
40.000    1
Name: count, dtype: int64

#-temp replace by Nan

In [28]:
df.replace([-99999, -88888], value= np.nan)

         day  temperature  windspeed     event
0        NaT       33.525       12.0  No Event
1 2017-01-04       33.525        9.0     Sunny
2 2017-01-05       28.000       12.0      Snow
3 2017-01-06       33.525        7.0  No Event
4 2017-01-07       32.000       12.0      Rain
5 2017-01-08       33.525       12.0     Sunny
6 2017-01-09       33.525       12.0  No Event
7 2017-01-10       34.100        8.1    Cloudy
8 2017-01-11       40.000       12.0     Sunny

In [29]:
df.replace({
    -99999:0,
    "no event":"Sunny"
})

         day  temperature  windspeed     event
0        NaT       33.525       12.0  No Event
1 2017-01-04       33.525        9.0     Sunny
2 2017-01-05       28.000       12.0      Snow
3 2017-01-06       33.525        7.0  No Event
4 2017-01-07       32.000       12.0      Rain
5 2017-01-08       33.525       12.0     Sunny
6 2017-01-09       33.525       12.0  No Event
7 2017-01-10       34.100        8.1    Cloudy
8 2017-01-11       40.000       12.0     Sunny

In [30]:
df = pd.DataFrame({
    'score': ['Very good', "good", "okay","not good", "good", "okay"],
    'student': ['komol', 'shamol','vimol', 'kamrol', 'jamrol','amrol']
})

df

       score student
0  Very good   komol
1       good  shamol
2       okay   vimol
3   not good  kamrol
4       good  jamrol
5       okay   amrol

In [31]:
df.replace(['Very good', 'good', 'okay', 'not good'], [4, 3.5, 3, 2.5])

C:\Users\asus\AppData\Local\Temp\ipykernel_20028\1917812960.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace(['Very good', 'good', 'okay', 'not good'], [4, 3.5, 3, 2.5])

   score student
0    4.0   komol
1    3.5  shamol
2    3.0   vimol
3    2.5  kamrol
4    3.5  jamrol
5    3.0   amrol

In [32]:
df = pd.read_csv("weather_by_cities.csv")
df

         day      city  temperature  windspeed   event
0   1/1/2017  new york           32          6    Rain
1   1/2/2017  new york           36          7   Sunny
2   1/3/2017  new york           28         12    Snow
3   1/4/2017  new york           33          7   Sunny
4   1/1/2017    mumbai           90          5   Sunny
5   1/2/2017    mumbai           85         12     Fog
6   1/3/2017    mumbai           87         15     Fog
7   1/4/2017    mumbai           92          5    Rain
8   1/1/2017     paris           45         20   Sunny
9   1/2/2017     paris           50         13  Cloudy
10  1/3/2017     paris           54          8  Cloudy
11  1/4/2017     paris           42         10  Cloudy

In [33]:
g = df.groupby("city")
g

In [34]:
for city, data in g:
    print(data)
    print()

        day    city  temperature  windspeed  event
4  1/1/2017  mumbai           90          5  Sunny
5  1/2/2017  mumbai           85         12    Fog
6  1/3/2017  mumbai           87         15    Fog
7  1/4/2017  mumbai           92          5   Rain

        day      city  temperature  windspeed  event
0  1/1/2017  new york           32          6   Rain
1  1/2/2017  new york           36          7  Sunny
2  1/3/2017  new york           28         12   Snow
3  1/4/2017  new york           33          7  Sunny

         day   city  temperature  windspeed   event
8   1/1/2017  paris           45         20   Sunny
9   1/2/2017  paris           50         13  Cloudy
10  1/3/2017  paris           54          8  Cloudy
11  1/4/2017  paris           42         10  Cloudy

In [35]:
g.get_group('paris')

         day   city  temperature  windspeed   event
8   1/1/2017  paris           45         20   Sunny
9   1/2/2017  paris           50         13  Cloudy
10  1/3/2017  paris           54          8  Cloudy
11  1/4/2017  paris           42         10  Cloudy

In [36]:
g.get_group('paris').min()

day            1/1/2017
city              paris
temperature          42
windspeed             8
event            Cloudy
dtype: object

In [37]:
g.max()

               day  temperature  windspeed  event
city
mumbai    1/4/2017           92         15  Sunny
new york  1/4/2017           36         12  Sunny
paris     1/4/2017           54         20  Sunny

In [38]:
g.mean(numeric_only = True)

          temperature  windspeed
city
mumbai          88.50       9.25
new york        32.25       8.00
paris           47.75      12.75

In [39]:
g.describe().transpose()

city                  mumbai   new york      paris
temperature count   4.000000   4.000000   4.000000
            mean   88.500000  32.250000  47.750000
            std     3.109126   3.304038   5.315073
            min    85.000000  28.000000  42.000000
            25%    86.500000  31.000000  44.250000
            50%    88.500000  32.500000  47.500000
            75%    90.500000  33.750000  51.000000
            max    92.000000  36.000000  54.000000
windspeed   count   4.000000   4.000000   4.000000
            mean    9.250000   8.000000  12.750000
            std     5.057997   2.708013   5.251984
            min     5.000000   6.000000   8.000000
            25%     5.000000   6.750000   9.500000
            50%     8.500000   7.000000  11.500000
            75%    12.750000   8.250000  14.750000
            max    15.000000  12.000000  20.000000

In [40]:
g.size()

city
mumbai      4
new york    4
paris       4
dtype: int64