#What is a DataFrame?

A Pandas DataFrame is a 2 dimensional data structure, like a 2 dimensional array, or a table with rows and columns.

In [13]:
import numpy as np
import pandas as pd

data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

#load data into a DataFrame object:
df = pd.DataFrame(data)

print(df)

   calories  duration
0       420        50
1       380        40
2       390        45

In [7]:
#refer to the row index:
print(df.loc[0])

calories    420
duration     50
Name: 0, dtype: int64

In [8]:
#use a list of indexes:
print(df.loc[[0, 1]])

   calories  duration
0       420        50
1       380        40

In [19]:
import numpy as np
import pandas as pd

data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

df = pd.DataFrame(data, index = ["day1", "day2", "day3"])

print(df)

      calories  duration
day1       420        50
day2       380        40
day3       390        45

In [20]:
#refer to the named index:
print(df.loc["day2"])

calories    380
duration     40
Name: day2, dtype: int64

In [21]:
np.random.seed(101)
x = np.random.randint(0, 101, (4,3))
x

array([[95, 11, 81],
       [70, 63, 87],
       [75,  9, 77],
       [40,  4, 63]])

In [22]:
p = pd.DataFrame(x, columns= ['Polash', 'Mukul', 'Akbar'])
p

   Polash  Mukul  Akbar
0      95     11     81
1      70     63     87
2      75      9     77
3      40      4     63

In [23]:
x = np.arange(1,11)
y = np.arange(2,12)

pd.DataFrame({'Jamal':x ,'Kamal':y})

   Jamal  Kamal
0      1      2
1      2      3
2      3      4
3      4      5
4      5      6
5      6      7
6      7      8
7      8      9
8      9     10
9     10     11

In [29]:
A = np.arange(1,21)
B = np.arange(2,22)




pd.DataFrame({'X':A ,'Y':B})

     X   Y
0    1   2
1    2   3
2    3   4
3    4   5
4    5   6
5    6   7
6    7   8
7    8   9
8    9  10
9   10  11
10  11  12
11  12  13
12  13  14
13  14  15
14  15  16
15  16  17
16  17  18
17  18  19
18  19  20
19  20  21

In [2]:
pwd #working directory find out

'd:\\Data Science and Machine Learning Course\\Practice'

In [50]:


df = pd.read_csv('tips.csv')

print(df)

     total_bill    tip     sex smoker   day    time  size  price_per_person  \
0         16.99   1.01  Female     No   Sun  Dinner     2              8.49
1         10.34   1.66    Male     No   Sun  Dinner     3              3.45
2         21.01   3.50    Male     No   Sun  Dinner     3              7.00
3         23.68   3.31    Male     No   Sun  Dinner     2             11.84
4         24.59   3.61  Female     No   Sun  Dinner     4              6.15
5         25.29   4.71    Male     No   Sun  Dinner     4              6.32
6          8.77   2.00    Male     No   Sun  Dinner     2              4.38
7         26.88   3.12    Male     No   Sun  Dinner     4              6.72
8         15.04   1.96    Male     No   Sun  Dinner     2              7.52
9         14.78   3.23    Male     No   Sun  Dinner     2              7.39
10        10.27   1.71    Male     No   Sun  Dinner     2              5.14
11        35.26   5.00  Female     No   Sun  Dinner     4              8.82
12        15.42   1.57    Male     No   Sun  Dinner     2              7.71
13        18.43   3.00    Male     No   Sun  Dinner     4              4.61
14        14.83   3.02  Female     No   Sun  Dinner     2              7.42
15        21.58   3.92    Male     No   Sun  Dinner     2             10.79
16        10.33   1.67  Female     No   Sun  Dinner     3              3.44
17        16.29   3.71    Male     No   Sun  Dinner     3              5.43
18        16.97   3.50  Female     No   Sun  Dinner     3              5.66
19        20.65   3.35    Male     No   Sat  Dinner     3              6.88
20        17.92   4.08    Male     No   Sat  Dinner     2              8.96
21        20.29   2.75  Female     No   Sat  Dinner     2             10.14
22        15.77   2.23  Female     No   Sat  Dinner     2              7.88
23        39.42   7.58    Male     No   Sat  Dinner     4              9.86
24        19.82   3.18    Male     No   Sat  Dinner     2              9.91
25        17.81   2.34    Male     No   Sat  Dinner     4              4.45
26        13.37   2.00    Male     No   Sat  Dinner     2              6.68
27        12.69   2.00    Male     No   Sat  Dinner     2              6.34
28        21.70   4.30    Male     No   Sat  Dinner     2             10.85
29        19.65   3.00  Female     No   Sat  Dinner     2              9.82
30         9.55   1.45    Male     No   Sat  Dinner     2              4.78
31        18.35   2.50    Male     No   Sat  Dinner     4              4.59
32        15.06   3.00  Female     No   Sat  Dinner     2              7.53
33        20.69   2.45  Female     No   Sat  Dinner     4              5.17
34        17.78   3.27    Male     No   Sat  Dinner     2              8.89
35        24.06   3.60    Male     No   Sat  Dinner     3              8.02
36        16.31   2.00    Male     No   Sat  Dinner     3              5.44
37        16.93   3.07  Female     No   Sat  Dinner     3              5.64
38        18.69   2.31    Male     No   Sat  Dinner     3              6.23
39        31.27   5.00    Male     No   Sat  Dinner     3             10.42
40        16.04   2.24    Male     No   Sat  Dinner     3              5.35
41        17.46   2.54    Male     No   Sun  Dinner     2              8.73
42        13.94   3.06    Male     No   Sun  Dinner     2              6.97
43         9.68   1.32    Male     No   Sun  Dinner     2              4.84
44        30.40   5.60    Male     No   Sun  Dinner     4              7.60
45        18.29   3.00    Male     No   Sun  Dinner     2              9.14
46        22.23   5.00    Male     No   Sun  Dinner     2             11.12
47        32.40   6.00    Male     No   Sun  Dinner     4              8.10
48        28.55   2.05    Male     No   Sun  Dinner     3              9.52
49        18.04   3.00    Male     No   Sun  Dinner     2              9.02
50        12.54   2.50    Male     No   Sun  Dinner     2              6.27
51        10.29   2.60  Female     No   Sun  Dinner     2              5.14
52        34.81   5.20  Female     No   Sun  Dinner     4              8.70
53         9.94   1.56    Male     No   Sun  Dinner     2              4.97
54        25.56   4.34    Male     No   Sun  Dinner     4              6.39
55        19.49   3.51    Male     No   Sun  Dinner     2              9.74
56        38.01   3.00    Male    Yes   Sat  Dinner     4              9.50
57        26.41   1.50  Female     No   Sat  Dinner     2             13.20
58        11.24   1.76    Male    Yes   Sat  Dinner     2              5.62
59        48.27   6.73    Male     No   Sat  Dinner     4             12.07
60        20.29   3.21    Male    Yes   Sat  Dinner     2             10.14
61        13.81   2.00    Male    Yes   Sat  Dinner     2              6.90
62        11.02   1.98    Male    Yes   Sat  Dinner     2              5.51
63        18.29   3.76    Male    Yes   Sat  Dinner     4              4.57
64        17.59   2.64    Male     No   Sat  Dinner     3              5.86
65        20.08   3.15    Male     No   Sat  Dinner     3              6.69
66        16.45   2.47  Female     No   Sat  Dinner     2              8.22
67         3.07   1.00  Female    Yes   Sat  Dinner     1              3.07
68        20.23   2.01    Male     No   Sat  Dinner     2             10.12
69        15.01   2.09    Male    Yes   Sat  Dinner     2              7.50
70        12.02   1.97    Male     No   Sat  Dinner     2              6.01
71        17.07   3.00  Female     No   Sat  Dinner     3              5.69
72        26.86   3.14  Female    Yes   Sat  Dinner     2             13.43
73        25.28   5.00  Female    Yes   Sat  Dinner     2             12.64
74        14.73   2.20  Female     No   Sat  Dinner     2              7.36
75        10.51   1.25    Male     No   Sat  Dinner     2              5.26
76        17.92   3.08    Male    Yes   Sat  Dinner     2              8.96
77        27.20   4.00    Male     No  Thur   Lunch     4              6.80
78        22.76   3.00    Male     No  Thur   Lunch     2             11.38
79        17.29   2.71    Male     No  Thur   Lunch     2              8.64
80        19.44   3.00    Male    Yes  Thur   Lunch     2              9.72
81        16.66   3.40    Male     No  Thur   Lunch     2              8.33
82        10.07   1.83  Female     No  Thur   Lunch     1             10.07
83        32.68   5.00    Male    Yes  Thur   Lunch     2             16.34
84        15.98   2.03    Male     No  Thur   Lunch     2              7.99
85        34.83   5.17  Female     No  Thur   Lunch     4              8.71
86        13.03   2.00    Male     No  Thur   Lunch     2              6.52
87        18.28   4.00    Male     No  Thur   Lunch     2              9.14
88        24.71   5.85    Male     No  Thur   Lunch     2             12.36
89        21.16   3.00    Male     No  Thur   Lunch     2             10.58
90        28.97   3.00    Male    Yes   Fri  Dinner     2             14.48
91        22.49   3.50    Male     No   Fri  Dinner     2             11.24
92         5.75   1.00  Female    Yes   Fri  Dinner     2              2.88
93        16.32   4.30  Female    Yes   Fri  Dinner     2              8.16
94        22.75   3.25  Female     No   Fri  Dinner     2             11.38
95        40.17   4.73    Male    Yes   Fri  Dinner     4             10.04
96        27.28   4.00    Male    Yes   Fri  Dinner     2             13.64
97        12.03   1.50    Male    Yes   Fri  Dinner     2              6.02
98        21.01   3.00    Male    Yes   Fri  Dinner     2             10.50
99        12.46   1.50    Male     No   Fri  Dinner     2              6.23
100       11.35   2.50  Female    Yes   Fri  Dinner     2              5.68
101       15.38   3.00  Female    Yes   Fri  Dinner     2              7.69
102       44.30   2.50  Female    Yes   Sat  Dinner     3             14.77
103       22.42   3.48  Female    Yes   Sat  Dinner     2             11.21
104       20.92   4.08  Female     No   Sat  Dinner     2             10.46
105       15.36   1.64    Male    Yes   Sat  Dinner     2              7.68
106       20.49   4.06    Male    Yes   Sat  Dinner     2             10.24
107       25.21   4.29    Male    Yes   Sat  Dinner     2             12.60
108       18.24   3.76    Male     No   Sat  Dinner     2              9.12
109       14.31   4.00  Female    Yes   Sat  Dinner     2              7.16
110       14.00   3.00    Male     No   Sat  Dinner     2              7.00
111        7.25   1.00  Female     No   Sat  Dinner     1              7.25
112       38.07   4.00    Male     No   Sun  Dinner     3             12.69
113       23.95   2.55    Male     No   Sun  Dinner     2             11.98
114       25.71   4.00  Female     No   Sun  Dinner     3              8.57
115       17.31   3.50  Female     No   Sun  Dinner     2              8.65
116       29.93   5.07    Male     No   Sun  Dinner     4              7.48
117       10.65   1.50  Female     No  Thur   Lunch     2              5.32
118       12.43   1.80  Female     No  Thur   Lunch     2              6.22
119       24.08   2.92  Female     No  Thur   Lunch     4              6.02
120       11.69   2.31    Male     No  Thur   Lunch     2              5.84
121       13.42   1.68  Female     No  Thur   Lunch     2              6.71
122       14.26   2.50    Male     No  Thur   Lunch     2              7.13
123       15.95   2.00    Male     No  Thur   Lunch     2              7.98
124       12.48   2.52  Female     No  Thur   Lunch     2              6.24
125       29.80   4.20  Female     No  Thur   Lunch     6              4.97
126        8.52   1.48    Male     No  Thur   Lunch     2              4.26
127       14.52   2.00  Female     No  Thur   Lunch     2              7.26
128       11.38   2.00  Female     No  Thur   Lunch     2              5.69
129       22.82   2.18    Male     No  Thur   Lunch     3              7.61
130       19.08   1.50    Male     No  Thur   Lunch     2              9.54
131       20.27   2.83  Female     No  Thur   Lunch     2             10.14
132       11.17   1.50  Female     No  Thur   Lunch     2              5.58
133       12.26   2.00  Female     No  Thur   Lunch     2              6.13
134       18.26   3.25  Female     No  Thur   Lunch     2              9.13
135        8.51   1.25  Female     No  Thur   Lunch     2              4.26
136       10.33   2.00  Female     No  Thur   Lunch     2              5.16
137       14.15   2.00  Female     No  Thur   Lunch     2              7.08
138       16.00   2.00    Male    Yes  Thur   Lunch     2              8.00
139       13.16   2.75  Female     No  Thur   Lunch     2              6.58
140       17.47   3.50  Female     No  Thur   Lunch     2              8.74
141       34.30   6.70    Male     No  Thur   Lunch     6              5.72
142       41.19   5.00    Male     No  Thur   Lunch     5              8.24
143       27.05   5.00  Female     No  Thur   Lunch     6              4.51
144       16.43   2.30  Female     No  Thur   Lunch     2              8.22
145        8.35   1.50  Female     No  Thur   Lunch     2              4.18
146       18.64   1.36  Female     No  Thur   Lunch     3              6.21
147       11.87   1.63  Female     No  Thur   Lunch     2              5.94
148        9.78   1.73    Male     No  Thur   Lunch     2              4.89
149        7.51   2.00    Male     No  Thur   Lunch     2              3.76
150       14.07   2.50    Male     No   Sun  Dinner     2              7.04
151       13.13   2.00    Male     No   Sun  Dinner     2              6.56
152       17.26   2.74    Male     No   Sun  Dinner     3              5.75
153       24.55   2.00    Male     No   Sun  Dinner     4              6.14
154       19.77   2.00    Male     No   Sun  Dinner     4              4.94
155       29.85   5.14  Female     No   Sun  Dinner     5              5.97
156       48.17   5.00    Male     No   Sun  Dinner     6              8.03
157       25.00   3.75  Female     No   Sun  Dinner     4              6.25
158       13.39   2.61  Female     No   Sun  Dinner     2              6.70
159       16.49   2.00    Male     No   Sun  Dinner     4              4.12
160       21.50   3.50    Male     No   Sun  Dinner     4              5.38
161       12.66   2.50    Male     No   Sun  Dinner     2              6.33
162       16.21   2.00  Female     No   Sun  Dinner     3              5.40
163       13.81   2.00    Male     No   Sun  Dinner     2              6.90
164       17.51   3.00  Female    Yes   Sun  Dinner     2              8.76
165       24.52   3.48    Male     No   Sun  Dinner     3              8.17
166       20.76   2.24    Male     No   Sun  Dinner     2             10.38
167       31.71   4.50    Male     No   Sun  Dinner     4              7.93
168       10.59   1.61  Female    Yes   Sat  Dinner     2              5.30
169       10.63   2.00  Female    Yes   Sat  Dinner     2              5.32
170       50.81  10.00    Male    Yes   Sat  Dinner     3             16.94
171       15.81   3.16    Male    Yes   Sat  Dinner     2              7.90
172        7.25   5.15    Male    Yes   Sun  Dinner     2              3.62
173       31.85   3.18    Male    Yes   Sun  Dinner     2             15.92
174       16.82   4.00    Male    Yes   Sun  Dinner     2              8.41
175       32.90   3.11    Male    Yes   Sun  Dinner     2             16.45
176       17.89   2.00    Male    Yes   Sun  Dinner     2              8.94
177       14.48   2.00    Male    Yes   Sun  Dinner     2              7.24
178        9.60   4.00  Female    Yes   Sun  Dinner     2              4.80
179       34.63   3.55    Male    Yes   Sun  Dinner     2             17.32
180       34.65   3.68    Male    Yes   Sun  Dinner     4              8.66
181       23.33   5.65    Male    Yes   Sun  Dinner     2             11.66
182       45.35   3.50    Male    Yes   Sun  Dinner     3             15.12
183       23.17   6.50    Male    Yes   Sun  Dinner     4              5.79
184       40.55   3.00    Male    Yes   Sun  Dinner     2             20.27
185       20.69   5.00    Male     No   Sun  Dinner     5              4.14
186       20.90   3.50  Female    Yes   Sun  Dinner     3              6.97
187       30.46   2.00    Male    Yes   Sun  Dinner     5              6.09
188       18.15   3.50  Female    Yes   Sun  Dinner     3              6.05
189       23.10   4.00    Male    Yes   Sun  Dinner     3              7.70
190       15.69   1.50    Male    Yes   Sun  Dinner     2              7.84
191       19.81   4.19  Female    Yes  Thur   Lunch     2              9.90
192       28.44   2.56    Male    Yes  Thur   Lunch     2             14.22
193       15.48   2.02    Male    Yes  Thur   Lunch     2              7.74
194       16.58   4.00    Male    Yes  Thur   Lunch     2              8.29
195        7.56   1.44    Male     No  Thur   Lunch     2              3.78
196       10.34   2.00    Male    Yes  Thur   Lunch     2              5.17
197       43.11   5.00  Female    Yes  Thur   Lunch     4             10.78
198       13.00   2.00  Female    Yes  Thur   Lunch     2              6.50
199       13.51   2.00    Male    Yes  Thur   Lunch     2              6.76
200       18.71   4.00    Male    Yes  Thur   Lunch     3              6.24
201       12.74   2.01  Female    Yes  Thur   Lunch     2              6.37
202       13.00   2.00  Female    Yes  Thur   Lunch     2              6.50
203       16.40   2.50  Female    Yes  Thur   Lunch     2              8.20
204       20.53   4.00    Male    Yes  Thur   Lunch     4              5.13
205       16.47   3.23  Female    Yes  Thur   Lunch     3              5.49
206       26.59   3.41    Male    Yes   Sat  Dinner     3              8.86
207       38.73   3.00    Male    Yes   Sat  Dinner     4              9.68
208       24.27   2.03    Male    Yes   Sat  Dinner     2             12.14
209       12.76   2.23  Female    Yes   Sat  Dinner     2              6.38
210       30.06   2.00    Male    Yes   Sat  Dinner     3             10.02
211       25.89   5.16    Male    Yes   Sat  Dinner     4              6.47
212       48.33   9.00    Male     No   Sat  Dinner     4             12.08
213       13.27   2.50  Female    Yes   Sat  Dinner     2              6.64
214       28.17   6.50  Female    Yes   Sat  Dinner     3              9.39
215       12.90   1.10  Female    Yes   Sat  Dinner     2              6.45
216       28.15   3.00    Male    Yes   Sat  Dinner     5              5.63
217       11.59   1.50    Male    Yes   Sat  Dinner     2              5.80
218        7.74   1.44    Male    Yes   Sat  Dinner     2              3.87
219       30.14   3.09  Female    Yes   Sat  Dinner     4              7.54
220       12.16   2.20    Male    Yes   Fri   Lunch     2              6.08
221       13.42   3.48  Female    Yes   Fri   Lunch     2              6.71
222        8.58   1.92    Male    Yes   Fri   Lunch     1              8.58
223       15.98   3.00  Female     No   Fri   Lunch     3              5.33
224       13.42   1.58    Male    Yes   Fri   Lunch     2              6.71
225       16.27   2.50  Female    Yes   Fri   Lunch     2              8.14
226       10.09   2.00  Female    Yes   Fri   Lunch     2              5.04
227       20.45   3.00    Male     No   Sat  Dinner     4              5.11
228       13.28   2.72    Male     No   Sat  Dinner     2              6.64
229       22.12   2.88  Female    Yes   Sat  Dinner     2             11.06
230       24.01   2.00    Male    Yes   Sat  Dinner     4              6.00
231       15.69   3.00    Male    Yes   Sat  Dinner     3              5.23
232       11.61   3.39    Male     No   Sat  Dinner     2              5.80
233       10.77   1.47    Male     No   Sat  Dinner     2              5.38
234       15.53   3.00    Male    Yes   Sat  Dinner     2              7.76
235       10.07   1.25    Male     No   Sat  Dinner     2              5.04
236       12.60   1.00    Male    Yes   Sat  Dinner     2              6.30
237       32.83   1.17    Male    Yes   Sat  Dinner     2             16.42
238       35.83   4.67  Female     No   Sat  Dinner     3             11.94
239       29.03   5.92    Male     No   Sat  Dinner     3              9.68
240       27.18   2.00  Female    Yes   Sat  Dinner     2             13.59
241       22.67   2.00    Male    Yes   Sat  Dinner     2             11.34
242       17.82   1.75    Male     No   Sat  Dinner     2              8.91
243       18.78   3.00  Female     No  Thur  Dinner     2              9.39

                Payer Name     CC Number Payment ID
0       Christy Cunningham  3.560000e+15    Sun2959
1           Douglas Tucker  4.480000e+15    Sun4608
2           Travis Walters  6.010000e+15    Sun4458
3         Nathaniel Harris  4.680000e+15    Sun5260
4             Tonya Carter  4.830000e+15    Sun2251
5               Erik Smith  2.130000e+14    Sun9679
6       Kristopher Johnson  2.220000e+15    Sun5985
7              Robert Buck  3.510000e+15    Sun8157
8          Joseph Mcdonald  3.520000e+15    Sun6820
9            Jerome Abbott  3.530000e+15    Sun3775
10           William Riley  5.660000e+11    Sun2546
11            Diane Macias  4.580000e+15    Sun6686
12         Chad Harrington  5.770000e+11    Sun1300
13            Joshua Jones  6.010000e+15    Sun2971
14           Vanessa Jones  3.000000e+13    Sun3848
15          Matthew Reilly  1.800000e+14    Sun1878
16        Elizabeth Foster  4.240000e+15    Sun9715
17            John Pittman  6.520000e+15    Sun2998
18          Laura Martinez  3.040000e+13    Sun2789
19           Timothy Oneal  6.570000e+15    Sat9213
20             Thomas Rice  4.400000e+15    Sat1709
21         Natalie Gardner  5.450000e+15    Sat9618
22          Ashley Shelton  3.520000e+15    Sat9786
23          Lance Peterson  3.540000e+15     Sat239
24        Christopher Ross  3.670000e+13    Sat6236

In [51]:
import pandas as pd

df = pd.read_csv('tips.csv')

print(df.to_string())

     total_bill    tip     sex smoker   day    time  size  price_per_person             Payer Name     CC Number Payment ID
0         16.99   1.01  Female     No   Sun  Dinner     2              8.49     Christy Cunningham  3.560000e+15    Sun2959
1         10.34   1.66    Male     No   Sun  Dinner     3              3.45         Douglas Tucker  4.480000e+15    Sun4608
2         21.01   3.50    Male     No   Sun  Dinner     3              7.00         Travis Walters  6.010000e+15    Sun4458
3         23.68   3.31    Male     No   Sun  Dinner     2             11.84       Nathaniel Harris  4.680000e+15    Sun5260
4         24.59   3.61  Female     No   Sun  Dinner     4              6.15           Tonya Carter  4.830000e+15    Sun2251
5         25.29   4.71    Male     No   Sun  Dinner     4              6.32             Erik Smith  2.130000e+14    Sun9679
6          8.77   2.00    Male     No   Sun  Dinner     2              4.38     Kristopher Johnson  2.220000e+15    Sun5985
7         26.88   3.12    Male     No   Sun  Dinner     4              6.72            Robert Buck  3.510000e+15    Sun8157
8         15.04   1.96    Male     No   Sun  Dinner     2              7.52        Joseph Mcdonald  3.520000e+15    Sun6820
9         14.78   3.23    Male     No   Sun  Dinner     2              7.39          Jerome Abbott  3.530000e+15    Sun3775
10        10.27   1.71    Male     No   Sun  Dinner     2              5.14          William Riley  5.660000e+11    Sun2546
11        35.26   5.00  Female     No   Sun  Dinner     4              8.82           Diane Macias  4.580000e+15    Sun6686
12        15.42   1.57    Male     No   Sun  Dinner     2              7.71        Chad Harrington  5.770000e+11    Sun1300
13        18.43   3.00    Male     No   Sun  Dinner     4              4.61           Joshua Jones  6.010000e+15    Sun2971
14        14.83   3.02  Female     No   Sun  Dinner     2              7.42          Vanessa Jones  3.000000e+13    Sun3848
15        21.58   3.92    Male     No   Sun  Dinner     2             10.79         Matthew Reilly  1.800000e+14    Sun1878
16        10.33   1.67  Female     No   Sun  Dinner     3              3.44       Elizabeth Foster  4.240000e+15    Sun9715
17        16.29   3.71    Male     No   Sun  Dinner     3              5.43           John Pittman  6.520000e+15    Sun2998
18        16.97   3.50  Female     No   Sun  Dinner     3              5.66         Laura Martinez  3.040000e+13    Sun2789
19        20.65   3.35    Male     No   Sat  Dinner     3              6.88          Timothy Oneal  6.570000e+15    Sat9213
20        17.92   4.08    Male     No   Sat  Dinner     2              8.96            Thomas Rice  4.400000e+15    Sat1709
21        20.29   2.75  Female     No   Sat  Dinner     2             10.14        Natalie Gardner  5.450000e+15    Sat9618
22        15.77   2.23  Female     No   Sat  Dinner     2              7.88         Ashley Shelton  3.520000e+15    Sat9786
23        39.42   7.58    Male     No   Sat  Dinner     4              9.86         Lance Peterson  3.540000e+15     Sat239
24        19.82   3.18    Male     No   Sat  Dinner     2              9.91       Christopher Ross  3.670000e+13    Sat6236
25        17.81   2.34    Male     No   Sat  Dinner     4              4.45         Robert Perkins  3.050000e+13     Sat907
26        13.37   2.00    Male     No   Sat  Dinner     2              6.68             Kyle Avery  6.530000e+15    Sat6651
27        12.69   2.00    Male     No   Sat  Dinner     2              6.34         Patrick Barber  3.020000e+13     Sat394
28        21.70   4.30    Male     No   Sat  Dinner     2             10.85          David Collier  5.530000e+15    Sat3697
29        19.65   3.00  Female     No   Sat  Dinner     2              9.82         Melinda Murphy  5.490000e+15    Sat2467
30         9.55   1.45    Male     No   Sat  Dinner     2              4.78             Grant Hall  3.020000e+13    Sat4099
31        18.35   2.50    Male     No   Sat  Dinner     4              4.59         Danny Santiago  6.300000e+11    Sat4947
32        15.06   3.00  Female     No   Sat  Dinner     2              7.53          Amanda Wilson  2.130000e+14    Sat1327
33        20.69   2.45  Female     No   Sat  Dinner     4              5.17          Amber Francis  3.780000e+14    Sat6649
34        17.78   3.27    Male     No   Sat  Dinner     2              8.89         Jacob Castillo  3.550000e+15    Sat8124
35        24.06   3.60    Male     No   Sat  Dinner     3              8.02         Joseph Mullins  5.520000e+15     Sat632
36        16.31   2.00    Male     No   Sat  Dinner     3              5.44           William Ford  3.530000e+15    Sat9139
37        16.93   3.07  Female     No   Sat  Dinner     3              5.64             Erin Lewis  5.160000e+15    Sat6406
38        18.69   2.31    Male     No   Sat  Dinner     3              6.23        Brandon Bradley  4.430000e+15    Sat4056
39        31.27   5.00    Male     No   Sat  Dinner     3             10.42      Mr. Brandon Berry  6.010000e+15    Sat6373
40        16.04   2.24    Male     No   Sat  Dinner     3              5.35           Adam Edwards  3.540000e+15    Sat8549
41        17.46   2.54    Male     No   Sun  Dinner     2              8.73            David Boyer  3.540000e+15    Sun9460
42        13.94   3.06    Male     No   Sun  Dinner     2              6.97            Bryan Brown  3.620000e+13    Sun1699
43         9.68   1.32    Male     No   Sun  Dinner     2              4.84     Christopher Spears  4.390000e+15    Sun3279
44        30.40   5.60    Male     No   Sun  Dinner     4              7.60            Todd Cooper  5.040000e+11    Sun2274
45        18.29   3.00    Male     No   Sun  Dinner     2              9.14     Richard Fitzgerald  3.750000e+14    Sun8643
46        22.23   5.00    Male     No   Sun  Dinner     2             11.12         Joshua Gilmore  4.290000e+12    Sun7097
47        32.40   6.00    Male     No   Sun  Dinner     4              8.10           James Barnes  3.550000e+15    Sun9677
48        28.55   2.05    Male     No   Sun  Dinner     3              9.52          Austin Fisher  6.010000e+15    Sun4142
49        18.04   3.00    Male     No   Sun  Dinner     2              9.02           William Roth  6.570000e+15    Sun9774
50        12.54   2.50    Male     No   Sun  Dinner     2              6.27          Jeremiah Neal  2.230000e+15    Sun2021
51        10.29   2.60  Female     No   Sun  Dinner     2              5.14         Jessica Ibarra  5.000000e+12    Sun4474
52        34.81   5.20  Female     No   Sun  Dinner     4              8.70           Emily Daniel  4.290000e+15    Sun6165
53         9.94   1.56    Male     No   Sun  Dinner     2              4.97          Curtis Morgan  4.630000e+15    Sun4561
54        25.56   4.34    Male     No   Sun  Dinner     4              6.39           Ronald Owens  6.570000e+15    Sun9470
55        19.49   3.51    Male     No   Sun  Dinner     2              9.74       Michael Hamilton  6.500000e+15    Sun1118
56        38.01   3.00    Male    Yes   Sat  Dinner     4              9.50  James Christensen DDS  3.500000e+14    Sat8903
57        26.41   1.50  Female     No   Sat  Dinner     2             13.20           Melody Simon  4.750000e+15    Sat8980
58        11.24   1.76    Male    Yes   Sat  Dinner     2              5.62          Troy Guerrero  3.560000e+15    Sat6683
59        48.27   6.73    Male     No   Sat  Dinner     4             12.07            Brian Ortiz  6.600000e+15    Sat8139
60        20.29   3.21    Male    Yes   Sat  Dinner     2             10.14         Anthony Mclean  3.480000e+14    Sat2353
61        13.81   2.00    Male    Yes   Sat  Dinner     2              6.90         Ryan Hernandez  4.770000e+12    Sat3030
62        11.02   1.98    Male    Yes   Sat  Dinner     2              5.51            Joseph Hart  1.800000e+14    Sat2265
63        18.29   3.76    Male    Yes   Sat  Dinner     4              4.57              Chad Hart  5.800000e+11    Sat4178
64        17.59   2.64    Male     No   Sat  Dinner     3              5.86        Michael Johnson  2.220000e+15    Sat1667
65        20.08   3.15    Male     No   Sat  Dinner     3              6.69           Justin Dixon  1.800000e+14    Sat6840
66        16.45   2.47  Female     No   Sat  Dinner     2              8.22          Rachel Vaughn  3.570000e+15    Sat4750
67         3.07   1.00  Female    Yes   Sat  Dinner     1              3.07          Tiffany Brock  4.360000e+15    Sat3455
68        20.23   2.01    Male     No   Sat  Dinner     2             10.12  Mr. Travis Bailey Jr.  6.040679e+10     Sat561
69        15.01   2.09    Male    Yes   Sat  Dinner     2              7.50              Adam Hall  4.700000e+15     Sat855
70        12.02   1.97    Male     No   Sat  Dinner     2              6.01              Max Brown  2.130000e+14    Sat2100
71        17.07   3.00  Female     No   Sat  Dinner     3              5.69          Teresa Fisher  5.440000e+15    Sat3469
72        26.86   3.14  Female    Yes   Sat  Dinner     2             13.43     Victoria Obrien MD  4.220000e+12    Sat1967
73        25.28   5.00  Female    Yes   Sat  Dinner     2             12.64           Julie Holmes  5.420000e+15    Sat6065
74        14.73   2.20  Female     No   Sat  Dinner     2              7.36          Ashley Harris  5.020000e+11    Sat6548
75        10.51   1.25    Male     No   Sat  Dinner     2              5.26          Kenneth Hayes  2.130000e+14    Sat5056
76        17.92   3.08    Male    Yes   Sat  Dinner     2              8.96             Mark Smith  6.760000e+11    Sat9908
77        27.20   4.00    Male     No  Thur   Lunch     4              6.80             John Davis  3.030000e+13   Thur4924
78        22.76   3.00    Male     No  Thur   Lunch     2             11.38             Chris Hahn  3.590000e+15   Thur2863
79        17.29   2.71    Male     No  Thur   Lunch     2              8.64             Brian Diaz  4.760000e+15   Thur9501
80        19.44   3.00    Male    Yes  Thur   Lunch     2              9.72           Louis Torres  3.880000e+13   Thur6453
81        16.66   3.40    Male     No  Thur   Lunch     2              8.33         William Martin  4.550000e+15   Thur8232
82        10.07   1.83  Female     No  Thur   Lunch     1             10.07            Julie Moody  6.300000e+11   Thur4909
83        32.68   5.00    Male    Yes  Thur   Lunch     2             16.34          Daniel Murphy  5.360000e+15   Thur8801
84        15.98   2.03    Male     No  Thur   Lunch     2              7.99            Jason Jones  4.440000e+15   Thur1944
85        34.83   5.17  Female     No  Thur   Lunch     4              8.71            Shawna Cook  6.010000e+15   Thur7972
86        13.03   2.00    Male     No  Thur   Lunch     2              6.52           Derek Thomas  2.130000e+14   Thur6793
87        18.28   4.00    Male     No  Thur   Lunch     2              9.14        Donald Williams  5.360000e+15   Thur3636
88        24.71   5.85    Male     No  Thur   Lunch     2             12.36           Roger Taylor  4.410000e+12   Thur9003
89        21.16   3.00    Male     No  Thur   Lunch     2             10.58            Keith Lewis  4.360000e+15   Thur6273
90        28.97   3.00    Male    Yes   Fri  Dinner     2             14.48           Daniel Mason  3.600000e+15    Fri4175
91        22.49   3.50    Male     No   Fri  Dinner     2             11.24              Earl Horn  6.010000e+15    Fri5700
92         5.75   1.00  Female    Yes   Fri  Dinner     2              2.88           Leah Ramirez  3.510000e+15    Fri3780
93        16.32   4.30  Female    Yes   Fri  Dinner     2              8.16         Natalie Nguyen  5.180000e+15    Fri6963
94        22.75   3.25  Female     No   Fri  Dinner     2             11.38            Jamie Garza  6.760000e+11    Fri2318
95        40.17   4.73    Male    Yes   Fri  Dinner     4             10.04          Aaron Bentley  1.800000e+14    Fri9628
96        27.28   4.00    Male    Yes   Fri  Dinner     2             13.64            Eric Carter  4.560000e+15    Fri3159
97        12.03   1.50    Male    Yes   Fri  Dinner     2              6.02           Eric Herrera  5.800000e+11    Fri9268
98        21.01   3.00    Male    Yes   Fri  Dinner     2             10.50             Michael Li  4.830000e+15     Fri144
99        12.46   1.50    Male     No   Fri  Dinner     2              6.23          Edward Carter  3.470000e+14    Fri5575
100       11.35   2.50  Female    Yes   Fri  Dinner     2              5.68             Lori Lynch  3.860000e+13    Fri4106
101       15.38   3.00  Female    Yes   Fri  Dinner     2              7.69          Tiffany Colon  6.010000e+15    Fri8382
102       44.30   2.50  Female    Yes   Sat  Dinner     3             14.77          Heather Cohen  3.800000e+14    Sat6240
103       22.42   3.48  Female    Yes   Sat  Dinner     2             11.21       Kathleen Hawkins  3.480000e+14    Sat1015
104       20.92   4.08  Female     No   Sat  Dinner     2             10.46    Gabrielle Frederick  4.010000e+15    Sat3194
105       15.36   1.64    Male    Yes   Sat  Dinner     2              7.68            David Price  4.030000e+12    Sat5106
106       20.49   4.06    Male    Yes   Sat  Dinner     2             10.24          Karl Mcdaniel  1.800000e+14    Sat7865
107       25.21   4.29    Male    Yes   Sat  Dinner     2             12.60           Jason Mullen  4.740000e+12    Sat5196
108       18.24   3.76    Male     No   Sat  Dinner     2              9.12           Steven Grant  4.110000e+15    Sat6376
109       14.31   4.00  Female    Yes   Sat  Dinner     2              7.16        Amanda Anderson  3.760000e+14    Sat2614
110       14.00   3.00    Male     No   Sat  Dinner     2              7.00          James Sanchez  3.450000e+14    Sat6801
111        7.25   1.00  Female     No   Sat  Dinner     1              7.25            Terri Jones  3.560000e+15    Sat4801
112       38.07   4.00    Male     No   Sun  Dinner     3             12.69             Jeff Lopez  3.570000e+15     Sun591
113       23.95   2.55    Male     No   Sun  Dinner     2             11.98             John Joyce  6.570000e+15    Sun1885
114       25.71   4.00  Female     No   Sun  Dinner     3              8.57            Katie Smith  5.400000e+15    Sun6492
115       17.31   3.50  Female     No   Sun  Dinner     2              8.65            Kayla Stone  3.790000e+14    Sun8746
116       29.93   5.07    Male     No   Sun  Dinner     4              7.48            Shawn Blake  4.690000e+15      Sun22
117       10.65   1.50  Female     No  Thur   Lunch     2              5.32            Linda Zhang  3.560000e+15   Thur9593
118       12.43   1.80  Female     No  Thur   Lunch     2              6.22    Dr. Caroline Tucker  5.020000e+11   Thur8084
119       24.08   2.92  Female     No  Thur   Lunch     4              6.02         Melanie Jordan  6.760000e+11   Thur8063
120       11.69   2.31    Male     No  Thur   Lunch     2              5.84        Kenneth Goodman  4.890000e+12   Thur8289
121       13.42   1.68  Female     No  Thur   Lunch     2              6.71           Laura Garcia  5.180000e+15   Thur2158
122       14.26   2.50    Male     No  Thur   Lunch     2              7.13           Perry Garcia  1.800000e+14   Thur3579
123       15.95   2.00    Male     No  Thur   Lunch     2              7.98       Christopher Lang  4.820000e+15   Thur1992
124       12.48   2.52  Female     No  Thur   Lunch     2              6.24            Jordan Diaz  4.470000e+15    Thur208
125       29.80   4.20  Female     No  Thur   Lunch     6              4.97         Angela Sanchez  5.040000e+11   Thur3948
126        8.52   1.48    Male     No  Thur   Lunch     2              4.26         Mario Bradshaw  4.520000e+15   Thur6719
127       14.52   2.00  Female     No  Thur   Lunch     2              7.26        Jessica Simmons  2.130000e+14   Thur1512
128       11.38   2.00  Female     No  Thur   Lunch     2              5.69      Christine Perkins  3.550000e+15   Thur8551
129       22.82   2.18    Male     No  Thur   Lunch     3              7.61         Raymond Torres  4.860000e+12   Thur9424
130       19.08   1.50    Male     No  Thur   Lunch     2              9.54            Seth Sexton  2.130000e+14   Thur1446
131       20.27   2.83  Female     No  Thur   Lunch     2             10.14           Ashley Burke  5.390000e+15   Thur9005
132       11.17   1.50  Female     No  Thur   Lunch     2              5.58        Taylor Gonzalez  6.010000e+15   Thur7783
133       12.26   2.00  Female     No  Thur   Lunch     2              6.13           Kaitlin Wolf  6.760000e+11   Thur1561
134       18.26   3.25  Female     No  Thur   Lunch     2              9.13        Karen Rodriguez  4.950000e+12     Thur75
135        8.51   1.25  Female     No  Thur   Lunch     2              4.26         Rebecca Harris  4.320000e+15   Thur6600
136       10.33   2.00  Female     No  Thur   Lunch     2              5.16            Donna Kelly  1.800000e+14   Thur1393
137       14.15   2.00  Female     No  Thur   Lunch     2              7.08         Vanessa Morris  2.130000e+14   Thur3890
138       16.00   2.00    Male    Yes  Thur   Lunch     2              8.00          Jason Burgess  3.560000e+15   Thur2710
139       13.16   2.75  Female     No  Thur   Lunch     2              6.58          Lindsey Meyer  6.760000e+11   Thur6245
140       17.47   3.50  Female     No  Thur   Lunch     2              8.74             Kayla Rios  5.230000e+15   Thur3906
141       34.30   6.70    Male     No  Thur   Lunch     6              5.72         Steven Carlson  3.530000e+15   Thur1025
142       41.19   5.00    Male     No  Thur   Lunch     5              8.24           Eric Andrews  4.360000e+15   Thur3621
143       27.05   5.00  Female     No  Thur   Lunch     6              4.51           Regina Jones  4.310000e+12   Thur6179
144       16.43   2.30  Female     No  Thur   Lunch     2              8.22            Linda Jones  6.540000e+15   Thur9002
145        8.35   1.50  Female     No  Thur   Lunch     2              4.18              Amy Young  4.290000e+12   Thur9331
146       18.64   1.36  Female     No  Thur   Lunch     3              6.21          Kelly Estrada  6.046330e+10   Thur3941
147       11.87   1.63  Female     No  Thur   Lunch     2              5.94     Annette Cunningham  6.760000e+11   Thur4780
148        9.78   1.73    Male     No  Thur   Lunch     2              4.89          David Stewart  3.580000e+15   Thur7276
149        7.51   2.00    Male     No  Thur   Lunch     2              3.76         Daniel Robbins  4.820000e+15   Thur6321
150       14.07   2.50    Male     No   Sun  Dinner     2              7.04              Luke Rice  4.810000e+15    Sun8863
151       13.13   2.00    Male     No   Sun  Dinner     2              6.56           Jason Arnold  3.570000e+15    Sun2127
152       17.26   2.74    Male     No   Sun  Dinner     3              5.75          Gregory Smith  4.290000e+12    Sun5205
153       24.55   2.00    Male     No   Sun  Dinner     4              6.14         Todd Patterson  4.420000e+15    Sun8670
154       19.77   2.00    Male     No   Sun  Dinner     4              4.94            James Smith  2.130000e+14    Sun5814
155       29.85   5.14  Female     No   Sun  Dinner     5              5.97         Madison Wilson  4.210000e+15    Sun9176
156       48.17   5.00    Male     No   Sun  Dinner     6              8.03          Ryan Gonzales  3.520000e+15    Sun7518
157       25.00   3.75  Female     No   Sun  Dinner     4              6.25           Laura Robles  2.130000e+14    Sun7015
158       13.39   2.61  Female     No   Sun  Dinner     2              6.70            Ashley Boyd  3.570000e+15     Sun982
159       16.49   2.00    Male     No   Sun  Dinner     4              4.12       Christopher Soto  3.050000e+13    Sun1781

#max_rows

The number of rows returned is defined in Pandas option settings.

You can check your system's maximum rows with the pd.options.display.max_rows statement.

In [53]:
import pandas as pd

print(pd.options.display.max_rows)

None

In [54]:
import pandas as pd

print(pd.options.display.max_columns)

None

#Increase the maximum number of rows to display the entire DataFrame:

In [55]:
import pandas as pd

pd.options.display.max_rows = 9999

df = pd.read_csv('tips.csv')

print(df)

     total_bill    tip     sex smoker   day    time  size  price_per_person  \
0         16.99   1.01  Female     No   Sun  Dinner     2              8.49
1         10.34   1.66    Male     No   Sun  Dinner     3              3.45
2         21.01   3.50    Male     No   Sun  Dinner     3              7.00
3         23.68   3.31    Male     No   Sun  Dinner     2             11.84
4         24.59   3.61  Female     No   Sun  Dinner     4              6.15
5         25.29   4.71    Male     No   Sun  Dinner     4              6.32
6          8.77   2.00    Male     No   Sun  Dinner     2              4.38
7         26.88   3.12    Male     No   Sun  Dinner     4              6.72
8         15.04   1.96    Male     No   Sun  Dinner     2              7.52
9         14.78   3.23    Male     No   Sun  Dinner     2              7.39
10        10.27   1.71    Male     No   Sun  Dinner     2              5.14
11        35.26   5.00  Female     No   Sun  Dinner     4              8.82
12        15.42   1.57    Male     No   Sun  Dinner     2              7.71
13        18.43   3.00    Male     No   Sun  Dinner     4              4.61
14        14.83   3.02  Female     No   Sun  Dinner     2              7.42
15        21.58   3.92    Male     No   Sun  Dinner     2             10.79
16        10.33   1.67  Female     No   Sun  Dinner     3              3.44
17        16.29   3.71    Male     No   Sun  Dinner     3              5.43
18        16.97   3.50  Female     No   Sun  Dinner     3              5.66
19        20.65   3.35    Male     No   Sat  Dinner     3              6.88
20        17.92   4.08    Male     No   Sat  Dinner     2              8.96
21        20.29   2.75  Female     No   Sat  Dinner     2             10.14
22        15.77   2.23  Female     No   Sat  Dinner     2              7.88
23        39.42   7.58    Male     No   Sat  Dinner     4              9.86
24        19.82   3.18    Male     No   Sat  Dinner     2              9.91
25        17.81   2.34    Male     No   Sat  Dinner     4              4.45
26        13.37   2.00    Male     No   Sat  Dinner     2              6.68
27        12.69   2.00    Male     No   Sat  Dinner     2              6.34
28        21.70   4.30    Male     No   Sat  Dinner     2             10.85
29        19.65   3.00  Female     No   Sat  Dinner     2              9.82
30         9.55   1.45    Male     No   Sat  Dinner     2              4.78
31        18.35   2.50    Male     No   Sat  Dinner     4              4.59
32        15.06   3.00  Female     No   Sat  Dinner     2              7.53
33        20.69   2.45  Female     No   Sat  Dinner     4              5.17
34        17.78   3.27    Male     No   Sat  Dinner     2              8.89
35        24.06   3.60    Male     No   Sat  Dinner     3              8.02
36        16.31   2.00    Male     No   Sat  Dinner     3              5.44
37        16.93   3.07  Female     No   Sat  Dinner     3              5.64
38        18.69   2.31    Male     No   Sat  Dinner     3              6.23
39        31.27   5.00    Male     No   Sat  Dinner     3             10.42
40        16.04   2.24    Male     No   Sat  Dinner     3              5.35
41        17.46   2.54    Male     No   Sun  Dinner     2              8.73
42        13.94   3.06    Male     No   Sun  Dinner     2              6.97
43         9.68   1.32    Male     No   Sun  Dinner     2              4.84
44        30.40   5.60    Male     No   Sun  Dinner     4              7.60
45        18.29   3.00    Male     No   Sun  Dinner     2              9.14
46        22.23   5.00    Male     No   Sun  Dinner     2             11.12
47        32.40   6.00    Male     No   Sun  Dinner     4              8.10
48        28.55   2.05    Male     No   Sun  Dinner     3              9.52
49        18.04   3.00    Male     No   Sun  Dinner     2              9.02
50        12.54   2.50    Male     No   Sun  Dinner     2              6.27
51        10.29   2.60  Female     No   Sun  Dinner     2              5.14
52        34.81   5.20  Female     No   Sun  Dinner     4              8.70
53         9.94   1.56    Male     No   Sun  Dinner     2              4.97
54        25.56   4.34    Male     No   Sun  Dinner     4              6.39
55        19.49   3.51    Male     No   Sun  Dinner     2              9.74
56        38.01   3.00    Male    Yes   Sat  Dinner     4              9.50
57        26.41   1.50  Female     No   Sat  Dinner     2             13.20
58        11.24   1.76    Male    Yes   Sat  Dinner     2              5.62
59        48.27   6.73    Male     No   Sat  Dinner     4             12.07
60        20.29   3.21    Male    Yes   Sat  Dinner     2             10.14
61        13.81   2.00    Male    Yes   Sat  Dinner     2              6.90
62        11.02   1.98    Male    Yes   Sat  Dinner     2              5.51
63        18.29   3.76    Male    Yes   Sat  Dinner     4              4.57
64        17.59   2.64    Male     No   Sat  Dinner     3              5.86
65        20.08   3.15    Male     No   Sat  Dinner     3              6.69
66        16.45   2.47  Female     No   Sat  Dinner     2              8.22
67         3.07   1.00  Female    Yes   Sat  Dinner     1              3.07
68        20.23   2.01    Male     No   Sat  Dinner     2             10.12
69        15.01   2.09    Male    Yes   Sat  Dinner     2              7.50
70        12.02   1.97    Male     No   Sat  Dinner     2              6.01
71        17.07   3.00  Female     No   Sat  Dinner     3              5.69
72        26.86   3.14  Female    Yes   Sat  Dinner     2             13.43
73        25.28   5.00  Female    Yes   Sat  Dinner     2             12.64
74        14.73   2.20  Female     No   Sat  Dinner     2              7.36
75        10.51   1.25    Male     No   Sat  Dinner     2              5.26
76        17.92   3.08    Male    Yes   Sat  Dinner     2              8.96
77        27.20   4.00    Male     No  Thur   Lunch     4              6.80
78        22.76   3.00    Male     No  Thur   Lunch     2             11.38
79        17.29   2.71    Male     No  Thur   Lunch     2              8.64
80        19.44   3.00    Male    Yes  Thur   Lunch     2              9.72
81        16.66   3.40    Male     No  Thur   Lunch     2              8.33
82        10.07   1.83  Female     No  Thur   Lunch     1             10.07
83        32.68   5.00    Male    Yes  Thur   Lunch     2             16.34
84        15.98   2.03    Male     No  Thur   Lunch     2              7.99
85        34.83   5.17  Female     No  Thur   Lunch     4              8.71
86        13.03   2.00    Male     No  Thur   Lunch     2              6.52
87        18.28   4.00    Male     No  Thur   Lunch     2              9.14
88        24.71   5.85    Male     No  Thur   Lunch     2             12.36
89        21.16   3.00    Male     No  Thur   Lunch     2             10.58
90        28.97   3.00    Male    Yes   Fri  Dinner     2             14.48
91        22.49   3.50    Male     No   Fri  Dinner     2             11.24
92         5.75   1.00  Female    Yes   Fri  Dinner     2              2.88
93        16.32   4.30  Female    Yes   Fri  Dinner     2              8.16
94        22.75   3.25  Female     No   Fri  Dinner     2             11.38
95        40.17   4.73    Male    Yes   Fri  Dinner     4             10.04
96        27.28   4.00    Male    Yes   Fri  Dinner     2             13.64
97        12.03   1.50    Male    Yes   Fri  Dinner     2              6.02
98        21.01   3.00    Male    Yes   Fri  Dinner     2             10.50
99        12.46   1.50    Male     No   Fri  Dinner     2              6.23
100       11.35   2.50  Female    Yes   Fri  Dinner     2              5.68
101       15.38   3.00  Female    Yes   Fri  Dinner     2              7.69
102       44.30   2.50  Female    Yes   Sat  Dinner     3             14.77
103       22.42   3.48  Female    Yes   Sat  Dinner     2             11.21
104       20.92   4.08  Female     No   Sat  Dinner     2             10.46
105       15.36   1.64    Male    Yes   Sat  Dinner     2              7.68
106       20.49   4.06    Male    Yes   Sat  Dinner     2             10.24
107       25.21   4.29    Male    Yes   Sat  Dinner     2             12.60
108       18.24   3.76    Male     No   Sat  Dinner     2              9.12
109       14.31   4.00  Female    Yes   Sat  Dinner     2              7.16
110       14.00   3.00    Male     No   Sat  Dinner     2              7.00
111        7.25   1.00  Female     No   Sat  Dinner     1              7.25
112       38.07   4.00    Male     No   Sun  Dinner     3             12.69
113       23.95   2.55    Male     No   Sun  Dinner     2             11.98
114       25.71   4.00  Female     No   Sun  Dinner     3              8.57
115       17.31   3.50  Female     No   Sun  Dinner     2              8.65
116       29.93   5.07    Male     No   Sun  Dinner     4              7.48
117       10.65   1.50  Female     No  Thur   Lunch     2              5.32
118       12.43   1.80  Female     No  Thur   Lunch     2              6.22
119       24.08   2.92  Female     No  Thur   Lunch     4              6.02
120       11.69   2.31    Male     No  Thur   Lunch     2              5.84
121       13.42   1.68  Female     No  Thur   Lunch     2              6.71
122       14.26   2.50    Male     No  Thur   Lunch     2              7.13
123       15.95   2.00    Male     No  Thur   Lunch     2              7.98
124       12.48   2.52  Female     No  Thur   Lunch     2              6.24
125       29.80   4.20  Female     No  Thur   Lunch     6              4.97
126        8.52   1.48    Male     No  Thur   Lunch     2              4.26
127       14.52   2.00  Female     No  Thur   Lunch     2              7.26
128       11.38   2.00  Female     No  Thur   Lunch     2              5.69
129       22.82   2.18    Male     No  Thur   Lunch     3              7.61
130       19.08   1.50    Male     No  Thur   Lunch     2              9.54
131       20.27   2.83  Female     No  Thur   Lunch     2             10.14
132       11.17   1.50  Female     No  Thur   Lunch     2              5.58
133       12.26   2.00  Female     No  Thur   Lunch     2              6.13
134       18.26   3.25  Female     No  Thur   Lunch     2              9.13
135        8.51   1.25  Female     No  Thur   Lunch     2              4.26
136       10.33   2.00  Female     No  Thur   Lunch     2              5.16
137       14.15   2.00  Female     No  Thur   Lunch     2              7.08
138       16.00   2.00    Male    Yes  Thur   Lunch     2              8.00
139       13.16   2.75  Female     No  Thur   Lunch     2              6.58
140       17.47   3.50  Female     No  Thur   Lunch     2              8.74
141       34.30   6.70    Male     No  Thur   Lunch     6              5.72
142       41.19   5.00    Male     No  Thur   Lunch     5              8.24
143       27.05   5.00  Female     No  Thur   Lunch     6              4.51
144       16.43   2.30  Female     No  Thur   Lunch     2              8.22
145        8.35   1.50  Female     No  Thur   Lunch     2              4.18
146       18.64   1.36  Female     No  Thur   Lunch     3              6.21
147       11.87   1.63  Female     No  Thur   Lunch     2              5.94
148        9.78   1.73    Male     No  Thur   Lunch     2              4.89
149        7.51   2.00    Male     No  Thur   Lunch     2              3.76
150       14.07   2.50    Male     No   Sun  Dinner     2              7.04
151       13.13   2.00    Male     No   Sun  Dinner     2              6.56
152       17.26   2.74    Male     No   Sun  Dinner     3              5.75
153       24.55   2.00    Male     No   Sun  Dinner     4              6.14
154       19.77   2.00    Male     No   Sun  Dinner     4              4.94
155       29.85   5.14  Female     No   Sun  Dinner     5              5.97
156       48.17   5.00    Male     No   Sun  Dinner     6              8.03
157       25.00   3.75  Female     No   Sun  Dinner     4              6.25
158       13.39   2.61  Female     No   Sun  Dinner     2              6.70
159       16.49   2.00    Male     No   Sun  Dinner     4              4.12
160       21.50   3.50    Male     No   Sun  Dinner     4              5.38
161       12.66   2.50    Male     No   Sun  Dinner     2              6.33
162       16.21   2.00  Female     No   Sun  Dinner     3              5.40
163       13.81   2.00    Male     No   Sun  Dinner     2              6.90
164       17.51   3.00  Female    Yes   Sun  Dinner     2              8.76
165       24.52   3.48    Male     No   Sun  Dinner     3              8.17
166       20.76   2.24    Male     No   Sun  Dinner     2             10.38
167       31.71   4.50    Male     No   Sun  Dinner     4              7.93
168       10.59   1.61  Female    Yes   Sat  Dinner     2              5.30
169       10.63   2.00  Female    Yes   Sat  Dinner     2              5.32
170       50.81  10.00    Male    Yes   Sat  Dinner     3             16.94
171       15.81   3.16    Male    Yes   Sat  Dinner     2              7.90
172        7.25   5.15    Male    Yes   Sun  Dinner     2              3.62
173       31.85   3.18    Male    Yes   Sun  Dinner     2             15.92
174       16.82   4.00    Male    Yes   Sun  Dinner     2              8.41
175       32.90   3.11    Male    Yes   Sun  Dinner     2             16.45
176       17.89   2.00    Male    Yes   Sun  Dinner     2              8.94
177       14.48   2.00    Male    Yes   Sun  Dinner     2              7.24
178        9.60   4.00  Female    Yes   Sun  Dinner     2              4.80
179       34.63   3.55    Male    Yes   Sun  Dinner     2             17.32
180       34.65   3.68    Male    Yes   Sun  Dinner     4              8.66
181       23.33   5.65    Male    Yes   Sun  Dinner     2             11.66
182       45.35   3.50    Male    Yes   Sun  Dinner     3             15.12
183       23.17   6.50    Male    Yes   Sun  Dinner     4              5.79
184       40.55   3.00    Male    Yes   Sun  Dinner     2             20.27
185       20.69   5.00    Male     No   Sun  Dinner     5              4.14
186       20.90   3.50  Female    Yes   Sun  Dinner     3              6.97
187       30.46   2.00    Male    Yes   Sun  Dinner     5              6.09
188       18.15   3.50  Female    Yes   Sun  Dinner     3              6.05
189       23.10   4.00    Male    Yes   Sun  Dinner     3              7.70
190       15.69   1.50    Male    Yes   Sun  Dinner     2              7.84
191       19.81   4.19  Female    Yes  Thur   Lunch     2              9.90
192       28.44   2.56    Male    Yes  Thur   Lunch     2             14.22
193       15.48   2.02    Male    Yes  Thur   Lunch     2              7.74
194       16.58   4.00    Male    Yes  Thur   Lunch     2              8.29
195        7.56   1.44    Male     No  Thur   Lunch     2              3.78
196       10.34   2.00    Male    Yes  Thur   Lunch     2              5.17
197       43.11   5.00  Female    Yes  Thur   Lunch     4             10.78
198       13.00   2.00  Female    Yes  Thur   Lunch     2              6.50
199       13.51   2.00    Male    Yes  Thur   Lunch     2              6.76
200       18.71   4.00    Male    Yes  Thur   Lunch     3              6.24
201       12.74   2.01  Female    Yes  Thur   Lunch     2              6.37
202       13.00   2.00  Female    Yes  Thur   Lunch     2              6.50
203       16.40   2.50  Female    Yes  Thur   Lunch     2              8.20
204       20.53   4.00    Male    Yes  Thur   Lunch     4              5.13
205       16.47   3.23  Female    Yes  Thur   Lunch     3              5.49
206       26.59   3.41    Male    Yes   Sat  Dinner     3              8.86
207       38.73   3.00    Male    Yes   Sat  Dinner     4              9.68
208       24.27   2.03    Male    Yes   Sat  Dinner     2             12.14
209       12.76   2.23  Female    Yes   Sat  Dinner     2              6.38
210       30.06   2.00    Male    Yes   Sat  Dinner     3             10.02
211       25.89   5.16    Male    Yes   Sat  Dinner     4              6.47
212       48.33   9.00    Male     No   Sat  Dinner     4             12.08
213       13.27   2.50  Female    Yes   Sat  Dinner     2              6.64
214       28.17   6.50  Female    Yes   Sat  Dinner     3              9.39
215       12.90   1.10  Female    Yes   Sat  Dinner     2              6.45
216       28.15   3.00    Male    Yes   Sat  Dinner     5              5.63
217       11.59   1.50    Male    Yes   Sat  Dinner     2              5.80
218        7.74   1.44    Male    Yes   Sat  Dinner     2              3.87
219       30.14   3.09  Female    Yes   Sat  Dinner     4              7.54
220       12.16   2.20    Male    Yes   Fri   Lunch     2              6.08
221       13.42   3.48  Female    Yes   Fri   Lunch     2              6.71
222        8.58   1.92    Male    Yes   Fri   Lunch     1              8.58
223       15.98   3.00  Female     No   Fri   Lunch     3              5.33
224       13.42   1.58    Male    Yes   Fri   Lunch     2              6.71
225       16.27   2.50  Female    Yes   Fri   Lunch     2              8.14
226       10.09   2.00  Female    Yes   Fri   Lunch     2              5.04
227       20.45   3.00    Male     No   Sat  Dinner     4              5.11
228       13.28   2.72    Male     No   Sat  Dinner     2              6.64
229       22.12   2.88  Female    Yes   Sat  Dinner     2             11.06
230       24.01   2.00    Male    Yes   Sat  Dinner     4              6.00
231       15.69   3.00    Male    Yes   Sat  Dinner     3              5.23
232       11.61   3.39    Male     No   Sat  Dinner     2              5.80
233       10.77   1.47    Male     No   Sat  Dinner     2              5.38
234       15.53   3.00    Male    Yes   Sat  Dinner     2              7.76
235       10.07   1.25    Male     No   Sat  Dinner     2              5.04
236       12.60   1.00    Male    Yes   Sat  Dinner     2              6.30
237       32.83   1.17    Male    Yes   Sat  Dinner     2             16.42
238       35.83   4.67  Female     No   Sat  Dinner     3             11.94
239       29.03   5.92    Male     No   Sat  Dinner     3              9.68
240       27.18   2.00  Female    Yes   Sat  Dinner     2             13.59
241       22.67   2.00    Male    Yes   Sat  Dinner     2             11.34
242       17.82   1.75    Male     No   Sat  Dinner     2              8.91
243       18.78   3.00  Female     No  Thur  Dinner     2              9.39

                Payer Name     CC Number Payment ID
0       Christy Cunningham  3.560000e+15    Sun2959
1           Douglas Tucker  4.480000e+15    Sun4608
2           Travis Walters  6.010000e+15    Sun4458
3         Nathaniel Harris  4.680000e+15    Sun5260
4             Tonya Carter  4.830000e+15    Sun2251
5               Erik Smith  2.130000e+14    Sun9679
6       Kristopher Johnson  2.220000e+15    Sun5985
7              Robert Buck  3.510000e+15    Sun8157
8          Joseph Mcdonald  3.520000e+15    Sun6820
9            Jerome Abbott  3.530000e+15    Sun3775
10           William Riley  5.660000e+11    Sun2546
11            Diane Macias  4.580000e+15    Sun6686
12         Chad Harrington  5.770000e+11    Sun1300
13            Joshua Jones  6.010000e+15    Sun2971
14           Vanessa Jones  3.000000e+13    Sun3848
15          Matthew Reilly  1.800000e+14    Sun1878
16        Elizabeth Foster  4.240000e+15    Sun9715
17            John Pittman  6.520000e+15    Sun2998
18          Laura Martinez  3.040000e+13    Sun2789
19           Timothy Oneal  6.570000e+15    Sat9213
20             Thomas Rice  4.400000e+15    Sat1709
21         Natalie Gardner  5.450000e+15    Sat9618
22          Ashley Shelton  3.520000e+15    Sat9786
23          Lance Peterson  3.540000e+15     Sat239
24        Christopher Ross  3.670000e+13    Sat6236

#Pandas - Analyzing DataFrames

#Viewing the Data

One of the most used method for getting a quick overview of the DataFrame, is the head() method.


The head() method returns the headers and a specified number of rows, starting from the top.

In [56]:
import pandas as pd

# Adjust settings to display all columns without truncation
pd.set_option('display.max_columns', None)  # Display all columns
pd.set_option('display.max_rows', None)     # Display all rows (if needed)
pd.set_option('display.width', None)        # Make sure it fits to screen width

# Read the CSV file
df = pd.read_csv('tips.csv')

# Print the first 10 rows row-wise
print(df.head(10).to_string())

   total_bill   tip     sex smoker  day    time  size  price_per_person          Payer Name     CC Number Payment ID
0       16.99  1.01  Female     No  Sun  Dinner     2              8.49  Christy Cunningham  3.560000e+15    Sun2959
1       10.34  1.66    Male     No  Sun  Dinner     3              3.45      Douglas Tucker  4.480000e+15    Sun4608
2       21.01  3.50    Male     No  Sun  Dinner     3              7.00      Travis Walters  6.010000e+15    Sun4458
3       23.68  3.31    Male     No  Sun  Dinner     2             11.84    Nathaniel Harris  4.680000e+15    Sun5260
4       24.59  3.61  Female     No  Sun  Dinner     4              6.15        Tonya Carter  4.830000e+15    Sun2251
5       25.29  4.71    Male     No  Sun  Dinner     4              6.32          Erik Smith  2.130000e+14    Sun9679
6        8.77  2.00    Male     No  Sun  Dinner     2              4.38  Kristopher Johnson  2.220000e+15    Sun5985
7       26.88  3.12    Male     No  Sun  Dinner     4              6.72         Robert Buck  3.510000e+15    Sun8157
8       15.04  1.96    Male     No  Sun  Dinner     2              7.52     Joseph Mcdonald  3.520000e+15    Sun6820
9       14.78  3.23    Male     No  Sun  Dinner     2              7.39       Jerome Abbott  3.530000e+15    Sun3775

#Last  Rows print

In [57]:
import pandas as pd

# Adjust settings to display all columns without truncation
pd.set_option('display.max_columns', None)  # Display all columns
pd.set_option('display.max_rows', None)     # Display all rows (if needed)
pd.set_option('display.width', None)        # Make sure it fits to screen width

# Read the CSV file
df = pd.read_csv('tips.csv')

# Print the first 10 rows row-wise
print(df.tail(5).to_string())

     total_bill   tip     sex smoker   day    time  size  price_per_person       Payer Name     CC Number Payment ID
239       29.03  5.92    Male     No   Sat  Dinner     3              9.68    Michael Avila  5.300000e+15    Sat2657
240       27.18  2.00  Female    Yes   Sat  Dinner     2             13.59   Monica Sanders  3.510000e+15    Sat1766
241       22.67  2.00    Male    Yes   Sat  Dinner     2             11.34       Keith Wong  6.010000e+15    Sat3880
242       17.82  1.75    Male     No   Sat  Dinner     2              8.91     Dennis Dixon  4.380000e+12      Sat17
243       18.78  3.00  Female     No  Thur  Dinner     2              9.39  Michelle Hardin  3.510000e+15    Thur672

#Info About the Data

In [58]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   total_bill        244 non-null    float64
 1   tip               244 non-null    float64
 2   sex               244 non-null    object
 3   smoker            244 non-null    object
 4   day               244 non-null    object
 5   time              244 non-null    object
 6   size              244 non-null    int64
 7   price_per_person  244 non-null    float64
 8   Payer Name        244 non-null    object
 9   CC Number         244 non-null    float64
 10  Payment ID        244 non-null    object
dtypes: float64(4), int64(1), object(6)
memory usage: 21.1+ KB
None

#Pandas - Cleaning Data

#Data Cleaning

Data cleaning means fixing bad data in your data set.

Bad data could be:

#Empty cells

#Data in wrong format

#Wrong data

#Duplicates

In this tutorial you will learn how to deal with all of them.

#Remove Rows

In [59]:
import pandas as pd

df = pd.read_csv('tips.csv')

new_df = df.dropna()

print(new_df.to_string())

     total_bill    tip     sex smoker   day    time  size  price_per_person             Payer Name     CC Number Payment ID
0         16.99   1.01  Female     No   Sun  Dinner     2              8.49     Christy Cunningham  3.560000e+15    Sun2959
1         10.34   1.66    Male     No   Sun  Dinner     3              3.45         Douglas Tucker  4.480000e+15    Sun4608
2         21.01   3.50    Male     No   Sun  Dinner     3              7.00         Travis Walters  6.010000e+15    Sun4458
3         23.68   3.31    Male     No   Sun  Dinner     2             11.84       Nathaniel Harris  4.680000e+15    Sun5260
4         24.59   3.61  Female     No   Sun  Dinner     4              6.15           Tonya Carter  4.830000e+15    Sun2251
5         25.29   4.71    Male     No   Sun  Dinner     4              6.32             Erik Smith  2.130000e+14    Sun9679
6          8.77   2.00    Male     No   Sun  Dinner     2              4.38     Kristopher Johnson  2.220000e+15    Sun5985
7         26.88   3.12    Male     No   Sun  Dinner     4              6.72            Robert Buck  3.510000e+15    Sun8157
8         15.04   1.96    Male     No   Sun  Dinner     2              7.52        Joseph Mcdonald  3.520000e+15    Sun6820
9         14.78   3.23    Male     No   Sun  Dinner     2              7.39          Jerome Abbott  3.530000e+15    Sun3775
10        10.27   1.71    Male     No   Sun  Dinner     2              5.14          William Riley  5.660000e+11    Sun2546
11        35.26   5.00  Female     No   Sun  Dinner     4              8.82           Diane Macias  4.580000e+15    Sun6686
12        15.42   1.57    Male     No   Sun  Dinner     2              7.71        Chad Harrington  5.770000e+11    Sun1300
13        18.43   3.00    Male     No   Sun  Dinner     4              4.61           Joshua Jones  6.010000e+15    Sun2971
14        14.83   3.02  Female     No   Sun  Dinner     2              7.42          Vanessa Jones  3.000000e+13    Sun3848
15        21.58   3.92    Male     No   Sun  Dinner     2             10.79         Matthew Reilly  1.800000e+14    Sun1878
16        10.33   1.67  Female     No   Sun  Dinner     3              3.44       Elizabeth Foster  4.240000e+15    Sun9715
17        16.29   3.71    Male     No   Sun  Dinner     3              5.43           John Pittman  6.520000e+15    Sun2998
18        16.97   3.50  Female     No   Sun  Dinner     3              5.66         Laura Martinez  3.040000e+13    Sun2789
19        20.65   3.35    Male     No   Sat  Dinner     3              6.88          Timothy Oneal  6.570000e+15    Sat9213
20        17.92   4.08    Male     No   Sat  Dinner     2              8.96            Thomas Rice  4.400000e+15    Sat1709
21        20.29   2.75  Female     No   Sat  Dinner     2             10.14        Natalie Gardner  5.450000e+15    Sat9618
22        15.77   2.23  Female     No   Sat  Dinner     2              7.88         Ashley Shelton  3.520000e+15    Sat9786
23        39.42   7.58    Male     No   Sat  Dinner     4              9.86         Lance Peterson  3.540000e+15     Sat239
24        19.82   3.18    Male     No   Sat  Dinner     2              9.91       Christopher Ross  3.670000e+13    Sat6236
25        17.81   2.34    Male     No   Sat  Dinner     4              4.45         Robert Perkins  3.050000e+13     Sat907
26        13.37   2.00    Male     No   Sat  Dinner     2              6.68             Kyle Avery  6.530000e+15    Sat6651
27        12.69   2.00    Male     No   Sat  Dinner     2              6.34         Patrick Barber  3.020000e+13     Sat394
28        21.70   4.30    Male     No   Sat  Dinner     2             10.85          David Collier  5.530000e+15    Sat3697
29        19.65   3.00  Female     No   Sat  Dinner     2              9.82         Melinda Murphy  5.490000e+15    Sat2467
30         9.55   1.45    Male     No   Sat  Dinner     2              4.78             Grant Hall  3.020000e+13    Sat4099
31        18.35   2.50    Male     No   Sat  Dinner     4              4.59         Danny Santiago  6.300000e+11    Sat4947
32        15.06   3.00  Female     No   Sat  Dinner     2              7.53          Amanda Wilson  2.130000e+14    Sat1327
33        20.69   2.45  Female     No   Sat  Dinner     4              5.17          Amber Francis  3.780000e+14    Sat6649
34        17.78   3.27    Male     No   Sat  Dinner     2              8.89         Jacob Castillo  3.550000e+15    Sat8124
35        24.06   3.60    Male     No   Sat  Dinner     3              8.02         Joseph Mullins  5.520000e+15     Sat632
36        16.31   2.00    Male     No   Sat  Dinner     3              5.44           William Ford  3.530000e+15    Sat9139
37        16.93   3.07  Female     No   Sat  Dinner     3              5.64             Erin Lewis  5.160000e+15    Sat6406
38        18.69   2.31    Male     No   Sat  Dinner     3              6.23        Brandon Bradley  4.430000e+15    Sat4056
39        31.27   5.00    Male     No   Sat  Dinner     3             10.42      Mr. Brandon Berry  6.010000e+15    Sat6373
40        16.04   2.24    Male     No   Sat  Dinner     3              5.35           Adam Edwards  3.540000e+15    Sat8549
41        17.46   2.54    Male     No   Sun  Dinner     2              8.73            David Boyer  3.540000e+15    Sun9460
42        13.94   3.06    Male     No   Sun  Dinner     2              6.97            Bryan Brown  3.620000e+13    Sun1699
43         9.68   1.32    Male     No   Sun  Dinner     2              4.84     Christopher Spears  4.390000e+15    Sun3279
44        30.40   5.60    Male     No   Sun  Dinner     4              7.60            Todd Cooper  5.040000e+11    Sun2274
45        18.29   3.00    Male     No   Sun  Dinner     2              9.14     Richard Fitzgerald  3.750000e+14    Sun8643
46        22.23   5.00    Male     No   Sun  Dinner     2             11.12         Joshua Gilmore  4.290000e+12    Sun7097
47        32.40   6.00    Male     No   Sun  Dinner     4              8.10           James Barnes  3.550000e+15    Sun9677
48        28.55   2.05    Male     No   Sun  Dinner     3              9.52          Austin Fisher  6.010000e+15    Sun4142
49        18.04   3.00    Male     No   Sun  Dinner     2              9.02           William Roth  6.570000e+15    Sun9774
50        12.54   2.50    Male     No   Sun  Dinner     2              6.27          Jeremiah Neal  2.230000e+15    Sun2021
51        10.29   2.60  Female     No   Sun  Dinner     2              5.14         Jessica Ibarra  5.000000e+12    Sun4474
52        34.81   5.20  Female     No   Sun  Dinner     4              8.70           Emily Daniel  4.290000e+15    Sun6165
53         9.94   1.56    Male     No   Sun  Dinner     2              4.97          Curtis Morgan  4.630000e+15    Sun4561
54        25.56   4.34    Male     No   Sun  Dinner     4              6.39           Ronald Owens  6.570000e+15    Sun9470
55        19.49   3.51    Male     No   Sun  Dinner     2              9.74       Michael Hamilton  6.500000e+15    Sun1118
56        38.01   3.00    Male    Yes   Sat  Dinner     4              9.50  James Christensen DDS  3.500000e+14    Sat8903
57        26.41   1.50  Female     No   Sat  Dinner     2             13.20           Melody Simon  4.750000e+15    Sat8980
58        11.24   1.76    Male    Yes   Sat  Dinner     2              5.62          Troy Guerrero  3.560000e+15    Sat6683
59        48.27   6.73    Male     No   Sat  Dinner     4             12.07            Brian Ortiz  6.600000e+15    Sat8139
60        20.29   3.21    Male    Yes   Sat  Dinner     2             10.14         Anthony Mclean  3.480000e+14    Sat2353
61        13.81   2.00    Male    Yes   Sat  Dinner     2              6.90         Ryan Hernandez  4.770000e+12    Sat3030
62        11.02   1.98    Male    Yes   Sat  Dinner     2              5.51            Joseph Hart  1.800000e+14    Sat2265
63        18.29   3.76    Male    Yes   Sat  Dinner     4              4.57              Chad Hart  5.800000e+11    Sat4178
64        17.59   2.64    Male     No   Sat  Dinner     3              5.86        Michael Johnson  2.220000e+15    Sat1667
65        20.08   3.15    Male     No   Sat  Dinner     3              6.69           Justin Dixon  1.800000e+14    Sat6840
66        16.45   2.47  Female     No   Sat  Dinner     2              8.22          Rachel Vaughn  3.570000e+15    Sat4750
67         3.07   1.00  Female    Yes   Sat  Dinner     1              3.07          Tiffany Brock  4.360000e+15    Sat3455
68        20.23   2.01    Male     No   Sat  Dinner     2             10.12  Mr. Travis Bailey Jr.  6.040679e+10     Sat561
69        15.01   2.09    Male    Yes   Sat  Dinner     2              7.50              Adam Hall  4.700000e+15     Sat855
70        12.02   1.97    Male     No   Sat  Dinner     2              6.01              Max Brown  2.130000e+14    Sat2100
71        17.07   3.00  Female     No   Sat  Dinner     3              5.69          Teresa Fisher  5.440000e+15    Sat3469
72        26.86   3.14  Female    Yes   Sat  Dinner     2             13.43     Victoria Obrien MD  4.220000e+12    Sat1967
73        25.28   5.00  Female    Yes   Sat  Dinner     2             12.64           Julie Holmes  5.420000e+15    Sat6065
74        14.73   2.20  Female     No   Sat  Dinner     2              7.36          Ashley Harris  5.020000e+11    Sat6548
75        10.51   1.25    Male     No   Sat  Dinner     2              5.26          Kenneth Hayes  2.130000e+14    Sat5056
76        17.92   3.08    Male    Yes   Sat  Dinner     2              8.96             Mark Smith  6.760000e+11    Sat9908
77        27.20   4.00    Male     No  Thur   Lunch     4              6.80             John Davis  3.030000e+13   Thur4924
78        22.76   3.00    Male     No  Thur   Lunch     2             11.38             Chris Hahn  3.590000e+15   Thur2863
79        17.29   2.71    Male     No  Thur   Lunch     2              8.64             Brian Diaz  4.760000e+15   Thur9501
80        19.44   3.00    Male    Yes  Thur   Lunch     2              9.72           Louis Torres  3.880000e+13   Thur6453
81        16.66   3.40    Male     No  Thur   Lunch     2              8.33         William Martin  4.550000e+15   Thur8232
82        10.07   1.83  Female     No  Thur   Lunch     1             10.07            Julie Moody  6.300000e+11   Thur4909
83        32.68   5.00    Male    Yes  Thur   Lunch     2             16.34          Daniel Murphy  5.360000e+15   Thur8801
84        15.98   2.03    Male     No  Thur   Lunch     2              7.99            Jason Jones  4.440000e+15   Thur1944
85        34.83   5.17  Female     No  Thur   Lunch     4              8.71            Shawna Cook  6.010000e+15   Thur7972
86        13.03   2.00    Male     No  Thur   Lunch     2              6.52           Derek Thomas  2.130000e+14   Thur6793
87        18.28   4.00    Male     No  Thur   Lunch     2              9.14        Donald Williams  5.360000e+15   Thur3636
88        24.71   5.85    Male     No  Thur   Lunch     2             12.36           Roger Taylor  4.410000e+12   Thur9003
89        21.16   3.00    Male     No  Thur   Lunch     2             10.58            Keith Lewis  4.360000e+15   Thur6273
90        28.97   3.00    Male    Yes   Fri  Dinner     2             14.48           Daniel Mason  3.600000e+15    Fri4175
91        22.49   3.50    Male     No   Fri  Dinner     2             11.24              Earl Horn  6.010000e+15    Fri5700
92         5.75   1.00  Female    Yes   Fri  Dinner     2              2.88           Leah Ramirez  3.510000e+15    Fri3780
93        16.32   4.30  Female    Yes   Fri  Dinner     2              8.16         Natalie Nguyen  5.180000e+15    Fri6963
94        22.75   3.25  Female     No   Fri  Dinner     2             11.38            Jamie Garza  6.760000e+11    Fri2318
95        40.17   4.73    Male    Yes   Fri  Dinner     4             10.04          Aaron Bentley  1.800000e+14    Fri9628
96        27.28   4.00    Male    Yes   Fri  Dinner     2             13.64            Eric Carter  4.560000e+15    Fri3159
97        12.03   1.50    Male    Yes   Fri  Dinner     2              6.02           Eric Herrera  5.800000e+11    Fri9268
98        21.01   3.00    Male    Yes   Fri  Dinner     2             10.50             Michael Li  4.830000e+15     Fri144
99        12.46   1.50    Male     No   Fri  Dinner     2              6.23          Edward Carter  3.470000e+14    Fri5575
100       11.35   2.50  Female    Yes   Fri  Dinner     2              5.68             Lori Lynch  3.860000e+13    Fri4106
101       15.38   3.00  Female    Yes   Fri  Dinner     2              7.69          Tiffany Colon  6.010000e+15    Fri8382
102       44.30   2.50  Female    Yes   Sat  Dinner     3             14.77          Heather Cohen  3.800000e+14    Sat6240
103       22.42   3.48  Female    Yes   Sat  Dinner     2             11.21       Kathleen Hawkins  3.480000e+14    Sat1015
104       20.92   4.08  Female     No   Sat  Dinner     2             10.46    Gabrielle Frederick  4.010000e+15    Sat3194
105       15.36   1.64    Male    Yes   Sat  Dinner     2              7.68            David Price  4.030000e+12    Sat5106
106       20.49   4.06    Male    Yes   Sat  Dinner     2             10.24          Karl Mcdaniel  1.800000e+14    Sat7865
107       25.21   4.29    Male    Yes   Sat  Dinner     2             12.60           Jason Mullen  4.740000e+12    Sat5196
108       18.24   3.76    Male     No   Sat  Dinner     2              9.12           Steven Grant  4.110000e+15    Sat6376
109       14.31   4.00  Female    Yes   Sat  Dinner     2              7.16        Amanda Anderson  3.760000e+14    Sat2614
110       14.00   3.00    Male     No   Sat  Dinner     2              7.00          James Sanchez  3.450000e+14    Sat6801
111        7.25   1.00  Female     No   Sat  Dinner     1              7.25            Terri Jones  3.560000e+15    Sat4801
112       38.07   4.00    Male     No   Sun  Dinner     3             12.69             Jeff Lopez  3.570000e+15     Sun591
113       23.95   2.55    Male     No   Sun  Dinner     2             11.98             John Joyce  6.570000e+15    Sun1885
114       25.71   4.00  Female     No   Sun  Dinner     3              8.57            Katie Smith  5.400000e+15    Sun6492
115       17.31   3.50  Female     No   Sun  Dinner     2              8.65            Kayla Stone  3.790000e+14    Sun8746
116       29.93   5.07    Male     No   Sun  Dinner     4              7.48            Shawn Blake  4.690000e+15      Sun22
117       10.65   1.50  Female     No  Thur   Lunch     2              5.32            Linda Zhang  3.560000e+15   Thur9593
118       12.43   1.80  Female     No  Thur   Lunch     2              6.22    Dr. Caroline Tucker  5.020000e+11   Thur8084
119       24.08   2.92  Female     No  Thur   Lunch     4              6.02         Melanie Jordan  6.760000e+11   Thur8063
120       11.69   2.31    Male     No  Thur   Lunch     2              5.84        Kenneth Goodman  4.890000e+12   Thur8289
121       13.42   1.68  Female     No  Thur   Lunch     2              6.71           Laura Garcia  5.180000e+15   Thur2158
122       14.26   2.50    Male     No  Thur   Lunch     2              7.13           Perry Garcia  1.800000e+14   Thur3579
123       15.95   2.00    Male     No  Thur   Lunch     2              7.98       Christopher Lang  4.820000e+15   Thur1992
124       12.48   2.52  Female     No  Thur   Lunch     2              6.24            Jordan Diaz  4.470000e+15    Thur208
125       29.80   4.20  Female     No  Thur   Lunch     6              4.97         Angela Sanchez  5.040000e+11   Thur3948
126        8.52   1.48    Male     No  Thur   Lunch     2              4.26         Mario Bradshaw  4.520000e+15   Thur6719
127       14.52   2.00  Female     No  Thur   Lunch     2              7.26        Jessica Simmons  2.130000e+14   Thur1512
128       11.38   2.00  Female     No  Thur   Lunch     2              5.69      Christine Perkins  3.550000e+15   Thur8551
129       22.82   2.18    Male     No  Thur   Lunch     3              7.61         Raymond Torres  4.860000e+12   Thur9424
130       19.08   1.50    Male     No  Thur   Lunch     2              9.54            Seth Sexton  2.130000e+14   Thur1446
131       20.27   2.83  Female     No  Thur   Lunch     2             10.14           Ashley Burke  5.390000e+15   Thur9005
132       11.17   1.50  Female     No  Thur   Lunch     2              5.58        Taylor Gonzalez  6.010000e+15   Thur7783
133       12.26   2.00  Female     No  Thur   Lunch     2              6.13           Kaitlin Wolf  6.760000e+11   Thur1561
134       18.26   3.25  Female     No  Thur   Lunch     2              9.13        Karen Rodriguez  4.950000e+12     Thur75
135        8.51   1.25  Female     No  Thur   Lunch     2              4.26         Rebecca Harris  4.320000e+15   Thur6600
136       10.33   2.00  Female     No  Thur   Lunch     2              5.16            Donna Kelly  1.800000e+14   Thur1393
137       14.15   2.00  Female     No  Thur   Lunch     2              7.08         Vanessa Morris  2.130000e+14   Thur3890
138       16.00   2.00    Male    Yes  Thur   Lunch     2              8.00          Jason Burgess  3.560000e+15   Thur2710
139       13.16   2.75  Female     No  Thur   Lunch     2              6.58          Lindsey Meyer  6.760000e+11   Thur6245
140       17.47   3.50  Female     No  Thur   Lunch     2              8.74             Kayla Rios  5.230000e+15   Thur3906
141       34.30   6.70    Male     No  Thur   Lunch     6              5.72         Steven Carlson  3.530000e+15   Thur1025
142       41.19   5.00    Male     No  Thur   Lunch     5              8.24           Eric Andrews  4.360000e+15   Thur3621
143       27.05   5.00  Female     No  Thur   Lunch     6              4.51           Regina Jones  4.310000e+12   Thur6179
144       16.43   2.30  Female     No  Thur   Lunch     2              8.22            Linda Jones  6.540000e+15   Thur9002
145        8.35   1.50  Female     No  Thur   Lunch     2              4.18              Amy Young  4.290000e+12   Thur9331
146       18.64   1.36  Female     No  Thur   Lunch     3              6.21          Kelly Estrada  6.046330e+10   Thur3941
147       11.87   1.63  Female     No  Thur   Lunch     2              5.94     Annette Cunningham  6.760000e+11   Thur4780
148        9.78   1.73    Male     No  Thur   Lunch     2              4.89          David Stewart  3.580000e+15   Thur7276
149        7.51   2.00    Male     No  Thur   Lunch     2              3.76         Daniel Robbins  4.820000e+15   Thur6321
150       14.07   2.50    Male     No   Sun  Dinner     2              7.04              Luke Rice  4.810000e+15    Sun8863
151       13.13   2.00    Male     No   Sun  Dinner     2              6.56           Jason Arnold  3.570000e+15    Sun2127
152       17.26   2.74    Male     No   Sun  Dinner     3              5.75          Gregory Smith  4.290000e+12    Sun5205
153       24.55   2.00    Male     No   Sun  Dinner     4              6.14         Todd Patterson  4.420000e+15    Sun8670
154       19.77   2.00    Male     No   Sun  Dinner     4              4.94            James Smith  2.130000e+14    Sun5814
155       29.85   5.14  Female     No   Sun  Dinner     5              5.97         Madison Wilson  4.210000e+15    Sun9176
156       48.17   5.00    Male     No   Sun  Dinner     6              8.03          Ryan Gonzales  3.520000e+15    Sun7518
157       25.00   3.75  Female     No   Sun  Dinner     4              6.25           Laura Robles  2.130000e+14    Sun7015
158       13.39   2.61  Female     No   Sun  Dinner     2              6.70            Ashley Boyd  3.570000e+15     Sun982
159       16.49   2.00    Male     No   Sun  Dinner     4              4.12       Christopher Soto  3.050000e+13    Sun1781

#Random Row

In [60]:
df.sample()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
121,13.42,1.68,Female,No,Thur,Lunch,2,6.71,Laura Garcia,5.180000e+15,Thur2158

In [61]:
#10 random row

df.sample(10)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
34,17.78,3.27,Male,No,Sat,Dinner,2,8.89,Jacob Castillo,3.550000e+15,Sat8124
71,17.07,3.00,Female,No,Sat,Dinner,3,5.69,Teresa Fisher,5.440000e+15,Sat3469
156,48.17,5.00,Male,No,Sun,Dinner,6,8.03,Ryan Gonzales,3.520000e+15,Sun7518
130,19.08,1.50,Male,No,Thur,Lunch,2,9.54,Seth Sexton,2.130000e+14,Thur1446
66,16.45,2.47,Female,No,Sat,Dinner,2,8.22,Rachel Vaughn,3.570000e+15,Sat4750
236,12.60,1.00,Male,Yes,Sat,Dinner,2,6.30,Matthew Myers,3.540000e+15,Sat5032
126,8.52,1.48,Male,No,Thur,Lunch,2,4.26,Mario Bradshaw,4.520000e+15,Thur6719
196,10.34,2.00,Male,Yes,Thur,Lunch,2,5.17,Eric Martin,3.040000e+13,Thur9862
36,16.31,2.00,Male,No,Sat,Dinner,3,5.44,William Ford,3.530000e+15,Sat9139
110,14.00,3.00,Male,No,Sat,Dinner,2,7.00,James Sanchez,3.450000e+14,Sat6801

#DataFrame Size

In [62]:
df.shape

(244, 11)

#Specific Column selection :

In [63]:
df["sex"]

0      Female
1        Male
2        Male
3        Male
4      Female
5        Male
6        Male
7        Male
8        Male
9        Male
10       Male
11     Female
12       Male
13       Male
14     Female
15       Male
16     Female
17       Male
18     Female
19       Male
20       Male
21     Female
22     Female
23       Male
24       Male
25       Male
26       Male
27       Male
28       Male
29     Female
30       Male
31       Male
32     Female
33     Female
34       Male
35       Male
36       Male
37     Female
38       Male
39       Male
40       Male
41       Male
42       Male
43       Male
44       Male
45       Male
46       Male
47       Male
48       Male
49       Male
50       Male
51     Female
52     Female
53       Male
54       Male
55       Male
56       Male
57     Female
58       Male
59       Male
60       Male
61       Male
62       Male
63       Male
64       Male
65       Male
66     Female
67     Female
68       Male
69       Male
70       Male
71     Female
72     Female
73     Female
74     Female
75       Male
76       Male
77       Male
78       Male
79       Male
80       Male
81       Male
82     Female
83       Male
84       Male
85     Female
86       Male
87       Male
88       Male
89       Male
90       Male
91       Male
92     Female
93     Female
94     Female
95       Male
96       Male
97       Male
98       Male
99       Male
100    Female
101    Female
102    Female
103    Female
104    Female
105      Male
106      Male
107      Male
108      Male
109    Female
110      Male
111    Female
112      Male
113      Male
114    Female
115    Female
116      Male
117    Female
118    Female
119    Female
120      Male
121    Female
122      Male
123      Male
124    Female
125    Female
126      Male
127    Female
128    Female
129      Male
130      Male
131    Female
132    Female
133    Female
134    Female
135    Female
136    Female
137    Female
138      Male
139    Female
140    Female
141      Male
142      Male
143    Female
144    Female
145    Female
146    Female
147    Female
148      Male
149      Male
150      Male
151      Male
152      Male
153      Male
154      Male
155    Female
156      Male
157    Female
158    Female
159      Male
160      Male
161      Male
162    Female
163      Male
164    Female
165      Male
166      Male
167      Male
168    Female
169    Female
170      Male
171      Male
172      Male
173      Male
174      Male
175      Male
176      Male
177      Male
178    Female
179      Male
180      Male
181      Male
182      Male
183      Male
184      Male
185      Male
186    Female
187      Male
188    Female
189      Male
190      Male
191    Female
192      Male
193      Male
194      Male
195      Male
196      Male
197    Female
198    Female
199      Male
200      Male
201    Female
202    Female
203    Female
204      Male
205    Female
206      Male
207      Male
208      Male
209    Female
210      Male
211      Male
212      Male
213    Female
214    Female
215    Female
216      Male
217      Male
218      Male
219    Female
220      Male
221    Female
222      Male
223    Female
224      Male
225    Female
226    Female
227      Male
228      Male
229    Female
230      Male
231      Male
232      Male
233      Male
234      Male
235      Male
236      Male
237      Male
238    Female
239      Male
240    Female
241      Male
242      Male
243    Female
Name: sex, dtype: object

#Multiple Column:

In [65]:
df[["sex","smoker","time"]]

        sex smoker    time
0    Female     No  Dinner
1      Male     No  Dinner
2      Male     No  Dinner
3      Male     No  Dinner
4    Female     No  Dinner
5      Male     No  Dinner
6      Male     No  Dinner
7      Male     No  Dinner
8      Male     No  Dinner
9      Male     No  Dinner
10     Male     No  Dinner
11   Female     No  Dinner
12     Male     No  Dinner
13     Male     No  Dinner
14   Female     No  Dinner
15     Male     No  Dinner
16   Female     No  Dinner
17     Male     No  Dinner
18   Female     No  Dinner
19     Male     No  Dinner
20     Male     No  Dinner
21   Female     No  Dinner
22   Female     No  Dinner
23     Male     No  Dinner
24     Male     No  Dinner
25     Male     No  Dinner
26     Male     No  Dinner
27     Male     No  Dinner
28     Male     No  Dinner
29   Female     No  Dinner
30     Male     No  Dinner
31     Male     No  Dinner
32   Female     No  Dinner
33   Female     No  Dinner
34     Male     No  Dinner
35     Male     No  Dinner
36     Male     No  Dinner
37   Female     No  Dinner
38     Male     No  Dinner
39     Male     No  Dinner
40     Male     No  Dinner
41     Male     No  Dinner
42     Male     No  Dinner
43     Male     No  Dinner
44     Male     No  Dinner
45     Male     No  Dinner
46     Male     No  Dinner
47     Male     No  Dinner
48     Male     No  Dinner
49     Male     No  Dinner
50     Male     No  Dinner
51   Female     No  Dinner
52   Female     No  Dinner
53     Male     No  Dinner
54     Male     No  Dinner
55     Male     No  Dinner
56     Male    Yes  Dinner
57   Female     No  Dinner
58     Male    Yes  Dinner
59     Male     No  Dinner
60     Male    Yes  Dinner
61     Male    Yes  Dinner
62     Male    Yes  Dinner
63     Male    Yes  Dinner
64     Male     No  Dinner
65     Male     No  Dinner
66   Female     No  Dinner
67   Female    Yes  Dinner
68     Male     No  Dinner
69     Male    Yes  Dinner
70     Male     No  Dinner
71   Female     No  Dinner
72   Female    Yes  Dinner
73   Female    Yes  Dinner
74   Female     No  Dinner
75     Male     No  Dinner
76     Male    Yes  Dinner
77     Male     No   Lunch
78     Male     No   Lunch
79     Male     No   Lunch
80     Male    Yes   Lunch
81     Male     No   Lunch
82   Female     No   Lunch
83     Male    Yes   Lunch
84     Male     No   Lunch
85   Female     No   Lunch
86     Male     No   Lunch
87     Male     No   Lunch
88     Male     No   Lunch
89     Male     No   Lunch
90     Male    Yes  Dinner
91     Male     No  Dinner
92   Female    Yes  Dinner
93   Female    Yes  Dinner
94   Female     No  Dinner
95     Male    Yes  Dinner
96     Male    Yes  Dinner
97     Male    Yes  Dinner
98     Male    Yes  Dinner
99     Male     No  Dinner
100  Female    Yes  Dinner
101  Female    Yes  Dinner
102  Female    Yes  Dinner
103  Female    Yes  Dinner
104  Female     No  Dinner
105    Male    Yes  Dinner
106    Male    Yes  Dinner
107    Male    Yes  Dinner
108    Male     No  Dinner
109  Female    Yes  Dinner
110    Male     No  Dinner
111  Female     No  Dinner
112    Male     No  Dinner
113    Male     No  Dinner
114  Female     No  Dinner
115  Female     No  Dinner
116    Male     No  Dinner
117  Female     No   Lunch
118  Female     No   Lunch
119  Female     No   Lunch
120    Male     No   Lunch
121  Female     No   Lunch
122    Male     No   Lunch
123    Male     No   Lunch
124  Female     No   Lunch
125  Female     No   Lunch
126    Male     No   Lunch
127  Female     No   Lunch
128  Female     No   Lunch
129    Male     No   Lunch
130    Male     No   Lunch
131  Female     No   Lunch
132  Female     No   Lunch
133  Female     No   Lunch
134  Female     No   Lunch
135  Female     No   Lunch
136  Female     No   Lunch
137  Female     No   Lunch
138    Male    Yes   Lunch
139  Female     No   Lunch
140  Female     No   Lunch
141    Male     No   Lunch
142    Male     No   Lunch
143  Female     No   Lunch
144  Female     No   Lunch
145  Female     No   Lunch
146  Female     No   Lunch
147  Female     No   Lunch
148    Male     No   Lunch
149    Male     No   Lunch
150    Male     No  Dinner
151    Male     No  Dinner
152    Male     No  Dinner
153    Male     No  Dinner
154    Male     No  Dinner
155  Female     No  Dinner
156    Male     No  Dinner
157  Female     No  Dinner
158  Female     No  Dinner
159    Male     No  Dinner
160    Male     No  Dinner
161    Male     No  Dinner
162  Female     No  Dinner
163    Male     No  Dinner
164  Female    Yes  Dinner
165    Male     No  Dinner
166    Male     No  Dinner
167    Male     No  Dinner
168  Female    Yes  Dinner
169  Female    Yes  Dinner
170    Male    Yes  Dinner
171    Male    Yes  Dinner
172    Male    Yes  Dinner
173    Male    Yes  Dinner
174    Male    Yes  Dinner
175    Male    Yes  Dinner
176    Male    Yes  Dinner
177    Male    Yes  Dinner
178  Female    Yes  Dinner
179    Male    Yes  Dinner
180    Male    Yes  Dinner
181    Male    Yes  Dinner
182    Male    Yes  Dinner
183    Male    Yes  Dinner
184    Male    Yes  Dinner
185    Male     No  Dinner
186  Female    Yes  Dinner
187    Male    Yes  Dinner
188  Female    Yes  Dinner
189    Male    Yes  Dinner
190    Male    Yes  Dinner
191  Female    Yes   Lunch
192    Male    Yes   Lunch
193    Male    Yes   Lunch
194    Male    Yes   Lunch
195    Male     No   Lunch
196    Male    Yes   Lunch
197  Female    Yes   Lunch
198  Female    Yes   Lunch
199    Male    Yes   Lunch
200    Male    Yes   Lunch
201  Female    Yes   Lunch
202  Female    Yes   Lunch
203  Female    Yes   Lunch
204    Male    Yes   Lunch
205  Female    Yes   Lunch
206    Male    Yes  Dinner
207    Male    Yes  Dinner
208    Male    Yes  Dinner
209  Female    Yes  Dinner
210    Male    Yes  Dinner
211    Male    Yes  Dinner
212    Male     No  Dinner
213  Female    Yes  Dinner
214  Female    Yes  Dinner
215  Female    Yes  Dinner
216    Male    Yes  Dinner
217    Male    Yes  Dinner
218    Male    Yes  Dinner
219  Female    Yes  Dinner
220    Male    Yes   Lunch
221  Female    Yes   Lunch
222    Male    Yes   Lunch
223  Female     No   Lunch
224    Male    Yes   Lunch
225  Female    Yes   Lunch
226  Female    Yes   Lunch
227    Male     No  Dinner
228    Male     No  Dinner
229  Female    Yes  Dinner
230    Male    Yes  Dinner
231    Male    Yes  Dinner
232    Male     No  Dinner
233    Male     No  Dinner
234    Male    Yes  Dinner
235    Male     No  Dinner
236    Male    Yes  Dinner
237    Male    Yes  Dinner
238  Female     No  Dinner
239    Male     No  Dinner
240  Female    Yes  Dinner
241    Male    Yes  Dinner
242    Male     No  Dinner
243  Female     No  Dinner

In [66]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size',
       'price_per_person', 'Payer Name', 'CC Number', 'Payment ID'],
      dtype='object')

#ALL ROW and Specific Columns

In [67]:
df.iloc[:,[0,1,3]]

     total_bill    tip smoker
0         16.99   1.01     No
1         10.34   1.66     No
2         21.01   3.50     No
3         23.68   3.31     No
4         24.59   3.61     No
5         25.29   4.71     No
6          8.77   2.00     No
7         26.88   3.12     No
8         15.04   1.96     No
9         14.78   3.23     No
10        10.27   1.71     No
11        35.26   5.00     No
12        15.42   1.57     No
13        18.43   3.00     No
14        14.83   3.02     No
15        21.58   3.92     No
16        10.33   1.67     No
17        16.29   3.71     No
18        16.97   3.50     No
19        20.65   3.35     No
20        17.92   4.08     No
21        20.29   2.75     No
22        15.77   2.23     No
23        39.42   7.58     No
24        19.82   3.18     No
25        17.81   2.34     No
26        13.37   2.00     No
27        12.69   2.00     No
28        21.70   4.30     No
29        19.65   3.00     No
30         9.55   1.45     No
31        18.35   2.50     No
32        15.06   3.00     No
33        20.69   2.45     No
34        17.78   3.27     No
35        24.06   3.60     No
36        16.31   2.00     No
37        16.93   3.07     No
38        18.69   2.31     No
39        31.27   5.00     No
40        16.04   2.24     No
41        17.46   2.54     No
42        13.94   3.06     No
43         9.68   1.32     No
44        30.40   5.60     No
45        18.29   3.00     No
46        22.23   5.00     No
47        32.40   6.00     No
48        28.55   2.05     No
49        18.04   3.00     No
50        12.54   2.50     No
51        10.29   2.60     No
52        34.81   5.20     No
53         9.94   1.56     No
54        25.56   4.34     No
55        19.49   3.51     No
56        38.01   3.00    Yes
57        26.41   1.50     No
58        11.24   1.76    Yes
59        48.27   6.73     No
60        20.29   3.21    Yes
61        13.81   2.00    Yes
62        11.02   1.98    Yes
63        18.29   3.76    Yes
64        17.59   2.64     No
65        20.08   3.15     No
66        16.45   2.47     No
67         3.07   1.00    Yes
68        20.23   2.01     No
69        15.01   2.09    Yes
70        12.02   1.97     No
71        17.07   3.00     No
72        26.86   3.14    Yes
73        25.28   5.00    Yes
74        14.73   2.20     No
75        10.51   1.25     No
76        17.92   3.08    Yes
77        27.20   4.00     No
78        22.76   3.00     No
79        17.29   2.71     No
80        19.44   3.00    Yes
81        16.66   3.40     No
82        10.07   1.83     No
83        32.68   5.00    Yes
84        15.98   2.03     No
85        34.83   5.17     No
86        13.03   2.00     No
87        18.28   4.00     No
88        24.71   5.85     No
89        21.16   3.00     No
90        28.97   3.00    Yes
91        22.49   3.50     No
92         5.75   1.00    Yes
93        16.32   4.30    Yes
94        22.75   3.25     No
95        40.17   4.73    Yes
96        27.28   4.00    Yes
97        12.03   1.50    Yes
98        21.01   3.00    Yes
99        12.46   1.50     No
100       11.35   2.50    Yes
101       15.38   3.00    Yes
102       44.30   2.50    Yes
103       22.42   3.48    Yes
104       20.92   4.08     No
105       15.36   1.64    Yes
106       20.49   4.06    Yes
107       25.21   4.29    Yes
108       18.24   3.76     No
109       14.31   4.00    Yes
110       14.00   3.00     No
111        7.25   1.00     No
112       38.07   4.00     No
113       23.95   2.55     No
114       25.71   4.00     No
115       17.31   3.50     No
116       29.93   5.07     No
117       10.65   1.50     No
118       12.43   1.80     No
119       24.08   2.92     No
120       11.69   2.31     No
121       13.42   1.68     No
122       14.26   2.50     No
123       15.95   2.00     No
124       12.48   2.52     No
125       29.80   4.20     No
126        8.52   1.48     No
127       14.52   2.00     No
128       11.38   2.00     No
129       22.82   2.18     No
130       19.08   1.50     No
131       20.27   2.83     No
132       11.17   1.50     No
133       12.26   2.00     No
134       18.26   3.25     No
135        8.51   1.25     No
136       10.33   2.00     No
137       14.15   2.00     No
138       16.00   2.00    Yes
139       13.16   2.75     No
140       17.47   3.50     No
141       34.30   6.70     No
142       41.19   5.00     No
143       27.05   5.00     No
144       16.43   2.30     No
145        8.35   1.50     No
146       18.64   1.36     No
147       11.87   1.63     No
148        9.78   1.73     No
149        7.51   2.00     No
150       14.07   2.50     No
151       13.13   2.00     No
152       17.26   2.74     No
153       24.55   2.00     No
154       19.77   2.00     No
155       29.85   5.14     No
156       48.17   5.00     No
157       25.00   3.75     No
158       13.39   2.61     No
159       16.49   2.00     No
160       21.50   3.50     No
161       12.66   2.50     No
162       16.21   2.00     No
163       13.81   2.00     No
164       17.51   3.00    Yes
165       24.52   3.48     No
166       20.76   2.24     No
167       31.71   4.50     No
168       10.59   1.61    Yes
169       10.63   2.00    Yes
170       50.81  10.00    Yes
171       15.81   3.16    Yes
172        7.25   5.15    Yes
173       31.85   3.18    Yes
174       16.82   4.00    Yes
175       32.90   3.11    Yes
176       17.89   2.00    Yes
177       14.48   2.00    Yes
178        9.60   4.00    Yes
179       34.63   3.55    Yes
180       34.65   3.68    Yes
181       23.33   5.65    Yes
182       45.35   3.50    Yes
183       23.17   6.50    Yes
184       40.55   3.00    Yes
185       20.69   5.00     No
186       20.90   3.50    Yes
187       30.46   2.00    Yes
188       18.15   3.50    Yes
189       23.10   4.00    Yes
190       15.69   1.50    Yes
191       19.81   4.19    Yes
192       28.44   2.56    Yes
193       15.48   2.02    Yes
194       16.58   4.00    Yes
195        7.56   1.44     No
196       10.34   2.00    Yes
197       43.11   5.00    Yes
198       13.00   2.00    Yes
199       13.51   2.00    Yes
200       18.71   4.00    Yes
201       12.74   2.01    Yes
202       13.00   2.00    Yes
203       16.40   2.50    Yes
204       20.53   4.00    Yes
205       16.47   3.23    Yes
206       26.59   3.41    Yes
207       38.73   3.00    Yes
208       24.27   2.03    Yes
209       12.76   2.23    Yes
210       30.06   2.00    Yes
211       25.89   5.16    Yes
212       48.33   9.00     No
213       13.27   2.50    Yes
214       28.17   6.50    Yes
215       12.90   1.10    Yes
216       28.15   3.00    Yes
217       11.59   1.50    Yes
218        7.74   1.44    Yes
219       30.14   3.09    Yes
220       12.16   2.20    Yes
221       13.42   3.48    Yes
222        8.58   1.92    Yes
223       15.98   3.00     No
224       13.42   1.58    Yes
225       16.27   2.50    Yes
226       10.09   2.00    Yes
227       20.45   3.00     No
228       13.28   2.72     No
229       22.12   2.88    Yes
230       24.01   2.00    Yes
231       15.69   3.00    Yes
232       11.61   3.39     No
233       10.77   1.47     No
234       15.53   3.00    Yes
235       10.07   1.25     No
236       12.60   1.00    Yes
237       32.83   1.17    Yes
238       35.83   4.67     No
239       29.03   5.92     No
240       27.18   2.00    Yes
241       22.67   2.00    Yes
242       17.82   1.75     No
243       18.78   3.00     No

#ALL COLUMN and Specific Rows

In [68]:
df.iloc[0:51,:]

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3.560000e+15,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4.480000e+15,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6.010000e+15,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4.680000e+15,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4.830000e+15,Sun2251
5,25.29,4.71,Male,No,Sun,Dinner,4,6.32,Erik Smith,2.130000e+14,Sun9679
6,8.77,2.00,Male,No,Sun,Dinner,2,4.38,Kristopher Johnson,2.220000e+15,Sun5985
7,26.88,3.12,Male,No,Sun,Dinner,4,6.72,Robert Buck,3.510000e+15,Sun8157
8,15.04,1.96,Male,No,Sun,Dinner,2,7.52,Joseph Mcdonald,3.520000e+15,Sun6820
9,14.78,3.23,Male,No,Sun,Dinner,2,7.39,Jerome Abbott,3.530000e+15,Sun3775
10,10.27,1.71,Male,No,Sun,Dinner,2,5.14,William Riley,5.660000e+11,Sun2546
11,35.26,5.00,Female,No,Sun,Dinner,4,8.82,Diane Macias,4.580000e+15,Sun6686
12,15.42,1.57,Male,No,Sun,Dinner,2,7.71,Chad Harrington,5.770000e+11,Sun1300
13,18.43,3.00,Male,No,Sun,Dinner,4,4.61,Joshua Jones,6.010000e+15,Sun2971
14,14.83,3.02,Female,No,Sun,Dinner,2,7.42,Vanessa Jones,3.000000e+13,Sun3848
15,21.58,3.92,Male,No,Sun,Dinner,2,10.79,Matthew Reilly,1.800000e+14,Sun1878
16,10.33,1.67,Female,No,Sun,Dinner,3,3.44,Elizabeth Foster,4.240000e+15,Sun9715
17,16.29,3.71,Male,No,Sun,Dinner,3,5.43,John Pittman,6.520000e+15,Sun2998
18,16.97,3.50,Female,No,Sun,Dinner,3,5.66,Laura Martinez,3.040000e+13,Sun2789
19,20.65,3.35,Male,No,Sat,Dinner,3,6.88,Timothy Oneal,6.570000e+15,Sat9213
20,17.92,4.08,Male,No,Sat,Dinner,2,8.96,Thomas Rice,4.400000e+15,Sat1709
21,20.29,2.75,Female,No,Sat,Dinner,2,10.14,Natalie Gardner,5.450000e+15,Sat9618
22,15.77,2.23,Female,No,Sat,Dinner,2,7.88,Ashley Shelton,3.520000e+15,Sat9786
23,39.42,7.58,Male,No,Sat,Dinner,4,9.86,Lance Peterson,3.540000e+15,Sat239
24,19.82,3.18,Male,No,Sat,Dinner,2,9.91,Christopher Ross,3.670000e+13,Sat6236
25,17.81,2.34,Male,No,Sat,Dinner,4,4.45,Robert Perkins,3.050000e+13,Sat907
26,13.37,2.00,Male,No,Sat,Dinner,2,6.68,Kyle Avery,6.530000e+15,Sat6651
27,12.69,2.00,Male,No,Sat,Dinner,2,6.34,Patrick Barber,3.020000e+13,Sat394
28,21.70,4.30,Male,No,Sat,Dinner,2,10.85,David Collier,5.530000e+15,Sat3697
29,19.65,3.00,Female,No,Sat,Dinner,2,9.82,Melinda Murphy,5.490000e+15,Sat2467
30,9.55,1.45,Male,No,Sat,Dinner,2,4.78,Grant Hall,3.020000e+13,Sat4099
31,18.35,2.50,Male,No,Sat,Dinner,4,4.59,Danny Santiago,6.300000e+11,Sat4947
32,15.06,3.00,Female,No,Sat,Dinner,2,7.53,Amanda Wilson,2.130000e+14,Sat1327
33,20.69,2.45,Female,No,Sat,Dinner,4,5.17,Amber Francis,3.780000e+14,Sat6649
34,17.78,3.27,Male,No,Sat,Dinner,2,8.89,Jacob Castillo,3.550000e+15,Sat8124
35,24.06,3.60,Male,No,Sat,Dinner,3,8.02,Joseph Mullins,5.520000e+15,Sat632
36,16.31,2.00,Male,No,Sat,Dinner,3,5.44,William Ford,3.530000e+15,Sat9139
37,16.93,3.07,Female,No,Sat,Dinner,3,5.64,Erin Lewis,5.160000e+15,Sat6406
38,18.69,2.31,Male,No,Sat,Dinner,3,6.23,Brandon Bradley,4.430000e+15,Sat4056
39,31.27,5.00,Male,No,Sat,Dinner,3,10.42,Mr. Brandon Berry,6.010000e+15,Sat6373
40,16.04,2.24,Male,No,Sat,Dinner,3,5.35,Adam Edwards,3.540000e+15,Sat8549
41,17.46,2.54,Male,No,Sun,Dinner,2,8.73,David Boyer,3.540000e+15,Sun9460
42,13.94,3.06,Male,No,Sun,Dinner,2,6.97,Bryan Brown,3.620000e+13,Sun1699
43,9.68,1.32,Male,No,Sun,Dinner,2,4.84,Christopher Spears,4.390000e+15,Sun3279
44,30.40,5.60,Male,No,Sun,Dinner,4,7.60,Todd Cooper,5.040000e+11,Sun2274
45,18.29,3.00,Male,No,Sun,Dinner,2,9.14,Richard Fitzgerald,3.750000e+14,Sun8643
46,22.23,5.00,Male,No,Sun,Dinner,2,11.12,Joshua Gilmore,4.290000e+12,Sun7097
47,32.40,6.00,Male,No,Sun,Dinner,4,8.10,James Barnes,3.550000e+15,Sun9677
48,28.55,2.05,Male,No,Sun,Dinner,3,9.52,Austin Fisher,6.010000e+15,Sun4142
49,18.04,3.00,Male,No,Sun,Dinner,2,9.02,William Roth,6.570000e+15,Sun9774
50,12.54,2.50,Male,No,Sun,Dinner,2,6.27,Jeremiah Neal,2.230000e+15,Sun2021

#Condition for seeing data

In [71]:
tips_over_5 = df[df['tip'] > 5]

#Multiple condition

In [72]:
filtering_cond = (df['tip'] > 5) & (df['day'] == "Sat")


tips_over_5 = df[filtering_cond]
tips_over_5

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
23,39.42,7.58,Male,No,Sat,Dinner,4,9.86,Lance Peterson,3.540000e+15,Sat239
59,48.27,6.73,Male,No,Sat,Dinner,4,12.07,Brian Ortiz,6.600000e+15,Sat8139
170,50.81,10.00,Male,Yes,Sat,Dinner,3,16.94,Gregory Clark,5.470000e+15,Sat1954
211,25.89,5.16,Male,Yes,Sat,Dinner,4,6.47,Christopher Li,6.010000e+15,Sat6735
212,48.33,9.00,Male,No,Sat,Dinner,4,12.08,Alex Williamson,6.760000e+11,Sat4590
214,28.17,6.50,Female,Yes,Sat,Dinner,3,9.39,Marissa Jackson,4.920000e+15,Sat3374
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5.300000e+15,Sat2657

#MaximumTips Value

In [73]:
df["tip"].max()

10.0

#MinimumTips Value

In [74]:
df["tip"].min()

1.0

#ALL INFO min,max,sum.........etc

In [75]:
df.describe()

       total_bill         tip        size  price_per_person     CC Number
count  244.000000  244.000000  244.000000        244.000000  2.440000e+02
mean    19.785943    2.998279    2.569672          7.888197  2.563313e+15
std      8.902412    1.383638    0.951100          2.914234  2.369139e+15
min      3.070000    1.000000    1.000000          2.880000  6.040679e+10
25%     13.347500    2.000000    2.000000          5.800000  3.040000e+13
50%     17.795000    2.900000    2.000000          7.255000  3.525000e+15
75%     24.127500    3.562500    3.000000          9.390000  4.552500e+15
max     50.810000   10.000000    6.000000         20.270000  6.600000e+15

In [78]:
df.describe().transpose() #reverse hbe

,count,mean,std,min,25%,50%,75%,max
total_bill,244.0,1.978594e+01,8.902412e+00,3.070000e+00,1.334750e+01,1.779500e+01,2.412750e+01,5.081000e+01
tip,244.0,2.998279e+00,1.383638e+00,1.000000e+00,2.000000e+00,2.900000e+00,3.562500e+00,1.000000e+01
size,244.0,2.569672e+00,9.510998e-01,1.000000e+00,2.000000e+00,2.000000e+00,3.000000e+00,6.000000e+00
price_per_person,244.0,7.888197e+00,2.914234e+00,2.880000e+00,5.800000e+00,7.255000e+00,9.390000e+00,2.027000e+01
CC Number,244.0,2.563313e+15,2.369139e+15,6.040679e+10,3.040000e+13,3.525000e+15,4.552500e+15,6.600000e+15

#Value Counts Functions

In [79]:
df['sex'].value_counts()

sex
Male      157
Female     87
Name: count, dtype: int64

In [81]:
df['day'].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [82]:
df['tip'].value_counts()

tip
2.00     33
3.00     23
4.00     12
5.00     10
2.50     10
1.50      9
3.50      9
1.00      4
3.48      3
1.25      3
3.18      2
4.30      2
1.44      2
2.01      2
2.75      2
6.50      2
2.31      2
2.24      2
3.76      2
2.23      2
2.20      2
4.08      2
3.25      2
2.03      2
3.23      2
5.14      1
2.74      1
1.73      1
1.63      1
2.55      1
1.36      1
2.30      1
6.70      1
1.80      1
5.07      1
3.75      1
2.83      1
2.18      1
2.92      1
1.68      1
2.52      1
1.48      1
4.20      1
1.01      1
3.55      1
2.61      1
4.50      1
5.92      1
4.67      1
1.17      1
1.47      1
3.39      1
2.88      1
2.72      1
1.58      1
1.92      1
3.09      1
1.10      1
9.00      1
5.16      1
3.41      1
2.02      1
2.56      1
4.19      1
5.65      1
3.68      1
4.06      1
3.11      1
5.15      1
3.16      1
10.00     1
1.61      1
4.29      1
3.08      1
1.64      1
5.60      1
3.06      1
2.54      1
3.07      1
3.60      1
3.27      1
2.45      1
1.45      1
2.34      1
7.58      1
3.35      1
3.71      1
1.67      1
3.92      1
3.02      1
1.57      1
1.71      1
1.96      1
3.12      1
4.71      1
3.61      1
3.31      1
1.32      1
6.00      1
4.73      1
2.05      1
5.85      1
5.17      1
1.83      1
3.40      1
2.71      1
1.66      1
3.14      1
1.97      1
2.09      1
2.47      1
3.15      1
2.64      1
1.98      1
3.21      1
6.73      1
1.76      1
3.51      1
4.34      1
1.56      1
5.20      1
2.60      1
1.75      1
Name: count, dtype: int64

#Unique Value

In [83]:
df["Payer Name"].unique()

array(['Christy Cunningham', 'Douglas Tucker', 'Travis Walters',
       'Nathaniel Harris', 'Tonya Carter', 'Erik Smith',
       'Kristopher Johnson', 'Robert Buck', 'Joseph Mcdonald',
       'Jerome Abbott', 'William Riley', 'Diane Macias',
       'Chad Harrington', 'Joshua Jones', 'Vanessa Jones',
       'Matthew Reilly', 'Elizabeth Foster', 'John Pittman',
       'Laura Martinez', 'Timothy Oneal', 'Thomas Rice',
       'Natalie Gardner', 'Ashley Shelton', 'Lance Peterson',
       'Christopher Ross', 'Robert Perkins', 'Kyle Avery',
       'Patrick Barber', 'David Collier', 'Melinda Murphy', 'Grant Hall',
       'Danny Santiago', 'Amanda Wilson', 'Amber Francis',
       'Jacob Castillo', 'Joseph Mullins', 'William Ford', 'Erin Lewis',
       'Brandon Bradley', 'Mr. Brandon Berry', 'Adam Edwards',
       'David Boyer', 'Bryan Brown', 'Christopher Spears', 'Todd Cooper',
       'Richard Fitzgerald', 'Joshua Gilmore', 'James Barnes',
       'Austin Fisher', 'William Roth', 'Jeremiah Neal', 'Jessica Ibarra',
       'Emily Daniel', 'Curtis Morgan', 'Ronald Owens',
       'Michael Hamilton', 'James Christensen DDS', 'Melody Simon',
       'Troy Guerrero', 'Brian Ortiz', 'Anthony Mclean', 'Ryan Hernandez',
       'Joseph Hart', 'Chad Hart', 'Michael Johnson', 'Justin Dixon',
       'Rachel Vaughn', 'Tiffany Brock', 'Mr. Travis Bailey Jr.',
       'Adam Hall', 'Max Brown', 'Teresa Fisher', 'Victoria Obrien MD',
       'Julie Holmes', 'Ashley Harris', 'Kenneth Hayes', 'Mark Smith',
       'John Davis', 'Chris Hahn', 'Brian Diaz', 'Louis Torres',
       'William Martin', 'Julie Moody', 'Daniel Murphy', 'Jason Jones',
       'Shawna Cook', 'Derek Thomas', 'Donald Williams', 'Roger Taylor',
       'Keith Lewis', 'Daniel Mason', 'Earl Horn', 'Leah Ramirez',
       'Natalie Nguyen', 'Jamie Garza', 'Aaron Bentley', 'Eric Carter',
       'Eric Herrera', 'Michael Li', 'Edward Carter', 'Lori Lynch',
       'Tiffany Colon', 'Heather Cohen', 'Kathleen Hawkins',
       'Gabrielle Frederick', 'David Price', 'Karl Mcdaniel',
       'Jason Mullen', 'Steven Grant', 'Amanda Anderson', 'James Sanchez',
       'Terri Jones', 'Jeff Lopez', 'John Joyce', 'Katie Smith',
       'Kayla Stone', 'Shawn Blake', 'Linda Zhang', 'Dr. Caroline Tucker',
       'Melanie Jordan', 'Kenneth Goodman', 'Laura Garcia',
       'Perry Garcia', 'Christopher Lang', 'Jordan Diaz',
       'Angela Sanchez', 'Mario Bradshaw', 'Jessica Simmons',
       'Christine Perkins', 'Raymond Torres', 'Seth Sexton',
       'Ashley Burke', 'Taylor Gonzalez', 'Kaitlin Wolf',
       'Karen Rodriguez', 'Rebecca Harris', 'Donna Kelly',
       'Vanessa Morris', 'Jason Burgess', 'Lindsey Meyer', 'Kayla Rios',
       'Steven Carlson', 'Eric Andrews', 'Regina Jones', 'Linda Jones',
       'Amy Young', 'Kelly Estrada', 'Annette Cunningham',
       'David Stewart', 'Daniel Robbins', 'Luke Rice', 'Jason Arnold',
       'Gregory Smith', 'Todd Patterson', 'James Smith', 'Madison Wilson',
       'Ryan Gonzales', 'Laura Robles', 'Ashley Boyd', 'Christopher Soto',
       'Travis Gonzalez', 'Brandon Oconnor', 'Jennifer Baird',
       'Charles Newton', 'Audrey Griffin', 'Jacob Hansen', 'Gordon Lane',
       'Michael Lawson', 'Sara Jimenez', 'Amy Hill', 'Gregory Clark',
       'David Hall', 'Larry White', 'Scott Perez', 'Brian Miles',
       'Nathan Reynolds', 'Walter Simmons', 'John Dudley', 'Melanie Gray',
       'Brian Bailey', 'James Hebert DDS', 'Jason Cox', 'Jose Parsons',
       'Dr. Michael James', 'Stephen Cox', 'Joseph Howell',
       'Heidi Atkinson', 'David Barrett', 'Glenda Wiggins',
       'Richard Stevens', 'Riley Barnes', 'Kristy Boyd',
       'Dr. Jeffrey Rich', 'Raymond Sullivan', 'Benjamin Weber',
       'Michael White', 'Eric Martin', 'Brooke Soto', 'Katherine Bond',
       'Joseph Murphy MD', 'Jason Conrad', 'Abigail Parks', 'Ashley Shaw',
       'Toni Brooks', 'Scott Kim', 'Carly Reyes', 'Daniel Owens',
       'Ricky Ramirez', 'Jason Carter', 'Sarah Cunningham',
       'Shawn Mendoza', 'Christopher Li', 'Alex Williamson',
       'Robin Andersen', 'Marissa Jackson', 'Jessica Owen',
       'Shawn Barnett PhD', 'Gary Orr', 'Nicholas Archer', 'Shelby House',
       'Ricky Johnson', 'Leslie Kaufman', 'Jason Lawrence', 'Mary Rivera',
       'Ronald Vaughn DVM', 'Whitney Arnold', 'Ruth Weiss',
       'Robert Bradley', 'Glenn Jones', 'Jennifer Russell',
       'Michael Osborne', 'Jason Parks', 'James Taylor', 'Paul Novak',
       'Tracy Douglas', 'Sean Gonzalez', 'Matthew Myers', 'Thomas Brown',
       'Kimberly Crane', 'Michael Avila', 'Monica Sanders', 'Keith Wong',
       'Dennis Dixon', 'Michelle Hardin'], dtype=object)

In [106]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size',
       'price_per_person', 'Payer Name', 'CC Number', 'Payment ID',
       'total_amt'],
      dtype='object')

#New_Columns

In [107]:
df.loc[:, "total_amt"] = df["total_bill"] + df["tip"]

In [108]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,total_amt
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3.560000e+15,Sun2959,18.00
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4.480000e+15,Sun4608,12.00
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6.010000e+15,Sun4458,24.51
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4.680000e+15,Sun5260,26.99
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4.830000e+15,Sun2251,28.20

#upto 2decimal point

In [112]:
import numpy as np
df['total_amt'] = np.round(df['total_amt'],2)

In [111]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,total_amt
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3.560000e+15,Sun2959,18.0
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4.480000e+15,Sun4608,12.0
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6.010000e+15,Sun4458,25.0
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4.680000e+15,Sun5260,27.0
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4.830000e+15,Sun2251,28.0

#Column Delete

In [114]:
df.drop(['total_amt'], axis=1) #axis 1 means column drop

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3.560000e+15,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4.480000e+15,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6.010000e+15,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4.680000e+15,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4.830000e+15,Sun2251
5,25.29,4.71,Male,No,Sun,Dinner,4,6.32,Erik Smith,2.130000e+14,Sun9679
6,8.77,2.00,Male,No,Sun,Dinner,2,4.38,Kristopher Johnson,2.220000e+15,Sun5985
7,26.88,3.12,Male,No,Sun,Dinner,4,6.72,Robert Buck,3.510000e+15,Sun8157
8,15.04,1.96,Male,No,Sun,Dinner,2,7.52,Joseph Mcdonald,3.520000e+15,Sun6820
9,14.78,3.23,Male,No,Sun,Dinner,2,7.39,Jerome Abbott,3.530000e+15,Sun3775
10,10.27,1.71,Male,No,Sun,Dinner,2,5.14,William Riley,5.660000e+11,Sun2546
11,35.26,5.00,Female,No,Sun,Dinner,4,8.82,Diane Macias,4.580000e+15,Sun6686
12,15.42,1.57,Male,No,Sun,Dinner,2,7.71,Chad Harrington,5.770000e+11,Sun1300
13,18.43,3.00,Male,No,Sun,Dinner,4,4.61,Joshua Jones,6.010000e+15,Sun2971
14,14.83,3.02,Female,No,Sun,Dinner,2,7.42,Vanessa Jones,3.000000e+13,Sun3848
15,21.58,3.92,Male,No,Sun,Dinner,2,10.79,Matthew Reilly,1.800000e+14,Sun1878
16,10.33,1.67,Female,No,Sun,Dinner,3,3.44,Elizabeth Foster,4.240000e+15,Sun9715
17,16.29,3.71,Male,No,Sun,Dinner,3,5.43,John Pittman,6.520000e+15,Sun2998
18,16.97,3.50,Female,No,Sun,Dinner,3,5.66,Laura Martinez,3.040000e+13,Sun2789
19,20.65,3.35,Male,No,Sat,Dinner,3,6.88,Timothy Oneal,6.570000e+15,Sat9213
20,17.92,4.08,Male,No,Sat,Dinner,2,8.96,Thomas Rice,4.400000e+15,Sat1709
21,20.29,2.75,Female,No,Sat,Dinner,2,10.14,Natalie Gardner,5.450000e+15,Sat9618
22,15.77,2.23,Female,No,Sat,Dinner,2,7.88,Ashley Shelton,3.520000e+15,Sat9786
23,39.42,7.58,Male,No,Sat,Dinner,4,9.86,Lance Peterson,3.540000e+15,Sat239
24,19.82,3.18,Male,No,Sat,Dinner,2,9.91,Christopher Ross,3.670000e+13,Sat6236
25,17.81,2.34,Male,No,Sat,Dinner,4,4.45,Robert Perkins,3.050000e+13,Sat907
26,13.37,2.00,Male,No,Sat,Dinner,2,6.68,Kyle Avery,6.530000e+15,Sat6651
27,12.69,2.00,Male,No,Sat,Dinner,2,6.34,Patrick Barber,3.020000e+13,Sat394
28,21.70,4.30,Male,No,Sat,Dinner,2,10.85,David Collier,5.530000e+15,Sat3697
29,19.65,3.00,Female,No,Sat,Dinner,2,9.82,Melinda Murphy,5.490000e+15,Sat2467
30,9.55,1.45,Male,No,Sat,Dinner,2,4.78,Grant Hall,3.020000e+13,Sat4099
31,18.35,2.50,Male,No,Sat,Dinner,4,4.59,Danny Santiago,6.300000e+11,Sat4947
32,15.06,3.00,Female,No,Sat,Dinner,2,7.53,Amanda Wilson,2.130000e+14,Sat1327
33,20.69,2.45,Female,No,Sat,Dinner,4,5.17,Amber Francis,3.780000e+14,Sat6649
34,17.78,3.27,Male,No,Sat,Dinner,2,8.89,Jacob Castillo,3.550000e+15,Sat8124
35,24.06,3.60,Male,No,Sat,Dinner,3,8.02,Joseph Mullins,5.520000e+15,Sat632
36,16.31,2.00,Male,No,Sat,Dinner,3,5.44,William Ford,3.530000e+15,Sat9139
37,16.93,3.07,Female,No,Sat,Dinner,3,5.64,Erin Lewis,5.160000e+15,Sat6406
38,18.69,2.31,Male,No,Sat,Dinner,3,6.23,Brandon Bradley,4.430000e+15,Sat4056
39,31.27,5.00,Male,No,Sat,Dinner,3,10.42,Mr. Brandon Berry,6.010000e+15,Sat6373
40,16.04,2.24,Male,No,Sat,Dinner,3,5.35,Adam Edwards,3.540000e+15,Sat8549
41,17.46,2.54,Male,No,Sun,Dinner,2,8.73,David Boyer,3.540000e+15,Sun9460
42,13.94,3.06,Male,No,Sun,Dinner,2,6.97,Bryan Brown,3.620000e+13,Sun1699
43,9.68,1.32,Male,No,Sun,Dinner,2,4.84,Christopher Spears,4.390000e+15,Sun3279
44,30.40,5.60,Male,No,Sun,Dinner,4,7.60,Todd Cooper,5.040000e+11,Sun2274
45,18.29,3.00,Male,No,Sun,Dinner,2,9.14,Richard Fitzgerald,3.750000e+14,Sun8643
46,22.23,5.00,Male,No,Sun,Dinner,2,11.12,Joshua Gilmore,4.290000e+12,Sun7097
47,32.40,6.00,Male,No,Sun,Dinner,4,8.10,James Barnes,3.550000e+15,Sun9677
48,28.55,2.05,Male,No,Sun,Dinner,3,9.52,Austin Fisher,6.010000e+15,Sun4142
49,18.04,3.00,Male,No,Sun,Dinner,2,9.02,William Roth,6.570000e+15,Sun9774
50,12.54,2.50,Male,No,Sun,Dinner,2,6.27,Jeremiah Neal,2.230000e+15,Sun2021
51,10.29,2.60,Female,No,Sun,Dinner,2,5.14,Jessica Ibarra,5.000000e+12,Sun4474
52,34.81,5.20,Female,No,Sun,Dinner,4,8.70,Emily Daniel,4.290000e+15,Sun6165
53,9.94,1.56,Male,No,Sun,Dinner,2,4.97,Curtis Morgan,4.630000e+15,Sun4561
54,25.56,4.34,Male,No,Sun,Dinner,4,6.39,Ronald Owens,6.570000e+15,Sun9470
55,19.49,3.51,Male,No,Sun,Dinner,2,9.74,Michael Hamilton,6.500000e+15,Sun1118
56,38.01,3.00,Male,Yes,Sat,Dinner,4,9.50,James Christensen DDS,3.500000e+14,Sat8903
57,26.41,1.50,Female,No,Sat,Dinner,2,13.20,Melody Simon,4.750000e+15,Sat8980
58,11.24,1.76,Male,Yes,Sat,Dinner,2,5.62,Troy Guerrero,3.560000e+15,Sat6683
59,48.27,6.73,Male,No,Sat,Dinner,4,12.07,Brian Ortiz,6.600000e+15,Sat8139
60,20.29,3.21,Male,Yes,Sat,Dinner,2,10.14,Anthony Mclean,3.480000e+14,Sat2353
61,13.81,2.00,Male,Yes,Sat,Dinner,2,6.90,Ryan Hernandez,4.770000e+12,Sat3030
62,11.02,1.98,Male,Yes,Sat,Dinner,2,5.51,Joseph Hart,1.800000e+14,Sat2265
63,18.29,3.76,Male,Yes,Sat,Dinner,4,4.57,Chad Hart,5.800000e+11,Sat4178
64,17.59,2.64,Male,No,Sat,Dinner,3,5.86,Michael Johnson,2.220000e+15,Sat1667
65,20.08,3.15,Male,No,Sat,Dinner,3,6.69,Justin Dixon,1.800000e+14,Sat6840
66,16.45,2.47,Female,No,Sat,Dinner,2,8.22,Rachel Vaughn,3.570000e+15,Sat4750
67,3.07,1.00,Female,Yes,Sat,Dinner,1,3.07,Tiffany Brock,4.360000e+15,Sat3455
68,20.23,2.01,Male,No,Sat,Dinner,2,10.12,Mr. Travis Bailey Jr.,6.040679e+10,Sat561
69,15.01,2.09,Male,Yes,Sat,Dinner,2,7.50,Adam Hall,4.700000e+15,Sat855
70,12.02,1.97,Male,No,Sat,Dinner,2,6.01,Max Brown,2.130000e+14,Sat2100
71,17.07,3.00,Female,No,Sat,Dinner,3,5.69,Teresa Fisher,5.440000e+15,Sat3469
72,26.86,3.14,Female,Yes,Sat,Dinner,2,13.43,Victoria Obrien MD,4.220000e+12,Sat1967
73,25.28,5.00,Female,Yes,Sat,Dinner,2,12.64,Julie Holmes,5.420000e+15,Sat6065
74,14.73,2.20,Female,No,Sat,Dinner,2,7.36,Ashley Harris,5.020000e+11,Sat6548
75,10.51,1.25,Male,No,Sat,Dinner,2,5.26,Kenneth Hayes,2.130000e+14,Sat5056
76,17.92,3.08,Male,Yes,Sat,Dinner,2,8.96,Mark Smith,6.760000e+11,Sat9908
77,27.20,4.00,Male,No,Thur,Lunch,4,6.80,John Davis,3.030000e+13,Thur4924
78,22.76,3.00,Male,No,Thur,Lunch,2,11.38,Chris Hahn,3.590000e+15,Thur2863
79,17.29,2.71,Male,No,Thur,Lunch,2,8.64,Brian Diaz,4.760000e+15,Thur9501
80,19.44,3.00,Male,Yes,Thur,Lunch,2,9.72,Louis Torres,3.880000e+13,Thur6453
81,16.66,3.40,Male,No,Thur,Lunch,2,8.33,William Martin,4.550000e+15,Thur8232
82,10.07,1.83,Female,No,Thur,Lunch,1,10.07,Julie Moody,6.300000e+11,Thur4909
83,32.68,5.00,Male,Yes,Thur,Lunch,2,16.34,Daniel Murphy,5.360000e+15,Thur8801
84,15.98,2.03,Male,No,Thur,Lunch,2,7.99,Jason Jones,4.440000e+15,Thur1944
85,34.83,5.17,Female,No,Thur,Lunch,4,8.71,Shawna Cook,6.010000e+15,Thur7972
86,13.03,2.00,Male,No,Thur,Lunch,2,6.52,Derek Thomas,2.130000e+14,Thur6793
87,18.28,4.00,Male,No,Thur,Lunch,2,9.14,Donald Williams,5.360000e+15,Thur3636
88,24.71,5.85,Male,No,Thur,Lunch,2,12.36,Roger Taylor,4.410000e+12,Thur9003
89,21.16,3.00,Male,No,Thur,Lunch,2,10.58,Keith Lewis,4.360000e+15,Thur6273
90,28.97,3.00,Male,Yes,Fri,Dinner,2,14.48,Daniel Mason,3.600000e+15,Fri4175
91,22.49,3.50,Male,No,Fri,Dinner,2,11.24,Earl Horn,6.010000e+15,Fri5700
92,5.75,1.00,Female,Yes,Fri,Dinner,2,2.88,Leah Ramirez,3.510000e+15,Fri3780
93,16.32,4.30,Female,Yes,Fri,Dinner,2,8.16,Natalie Nguyen,5.180000e+15,Fri6963
94,22.75,3.25,Female,No,Fri,Dinner,2,11.38,Jamie Garza,6.760000e+11,Fri2318
95,40.17,4.73,Male,Yes,Fri,Dinner,4,10.04,Aaron Bentley,1.800000e+14,Fri9628
96,27.28,4.00,Male,Yes,Fri,Dinner,2,13.64,Eric Carter,4.560000e+15,Fri3159
97,12.03,1.50,Male,Yes,Fri,Dinner,2,6.02,Eric Herrera,5.800000e+11,Fri9268
98,21.01,3.00,Male,Yes,Fri,Dinner,2,10.50,Michael Li,4.830000e+15,Fri144
99,12.46,1.50,Male,No,Fri,Dinner,2,6.23,Edward Carter,3.470000e+14,Fri5575
100,11.35,2.50,Female,Yes,Fri,Dinner,2,5.68,Lori Lynch,3.860000e+13,Fri4106
101,15.38,3.00,Female,Yes,Fri,Dinner,2,7.69,Tiffany Colon,6.010000e+15,Fri8382
102,44.30,2.50,Female,Yes,Sat,Dinner,3,14.77,Heather Cohen,3.800000e+14,Sat6240
103,22.42,3.48,Female,Yes,Sat,Dinner,2,11.21,Kathleen Hawkins,3.480000e+14,Sat1015
104,20.92,4.08,Female,No,Sat,Dinner,2,10.46,Gabrielle Frederick,4.010000e+15,Sat3194
105,15.36,1.64,Male,Yes,Sat,Dinner,2,7.68,David Price,4.030000e+12,Sat5106
106,20.49,4.06,Male,Yes,Sat,Dinner,2,10.24,Karl Mcdaniel,1.800000e+14,Sat7865
107,25.21,4.29,Male,Yes,Sat,Dinner,2,12.60,Jason Mullen,4.740000e+12,Sat5196
108,18.24,3.76,Male,No,Sat,Dinner,2,9.12,Steven Grant,4.110000e+15,Sat6376
109,14.31,4.00,Female,Yes,Sat,Dinner,2,7.16,Amanda Anderson,3.760000e+14,Sat2614
110,14.00,3.00,Male,No,Sat,Dinner,2,7.00,James Sanchez,3.450000e+14,Sat6801
111,7.25,1.00,Female,No,Sat,Dinner,1,7.25,Terri Jones,3.560000e+15,Sat4801
112,38.07,4.00,Male,No,Sun,Dinner,3,12.69,Jeff Lopez,3.570000e+15,Sun591
113,23.95,2.55,Male,No,Sun,Dinner,2,11.98,John Joyce,6.570000e+15,Sun1885
114,25.71,4.00,Female,No,Sun,Dinner,3,8.57,Katie Smith,5.400000e+15,Sun6492
115,17.31,3.50,Female,No,Sun,Dinner,2,8.65,Kayla Stone,3.790000e+14,Sun8746
116,29.93,5.07,Male,No,Sun,Dinner,4,7.48,Shawn Blake,4.690000e+15,Sun22
117,10.65,1.50,Female,No,Thur,Lunch,2,5.32,Linda Zhang,3.560000e+15,Thur9593
118,12.43,1.80,Female,No,Thur,Lunch,2,6.22,Dr. Caroline Tucker,5.020000e+11,Thur8084
119,24.08,2.92,Female,No,Thur,Lunch,4,6.02,Melanie Jordan,6.760000e+11,Thur8063
120,11.69,2.31,Male,No,Thur,Lunch,2,5.84,Kenneth Goodman,4.890000e+12,Thur8289
121,13.42,1.68,Female,No,Thur,Lunch,2,6.71,Laura Garcia,5.180000e+15,Thur2158
122,14.26,2.50,Male,No,Thur,Lunch,2,7.13,Perry Garcia,1.800000e+14,Thur3579
123,15.95,2.00,Male,No,Thur,Lunch,2,7.98,Christopher Lang,4.820000e+15,Thur1992
124,12.48,2.52,Female,No,Thur,Lunch,2,6.24,Jordan Diaz,4.470000e+15,Thur208
125,29.80,4.20,Female,No,Thur,Lunch,6,4.97,Angela Sanchez,5.040000e+11,Thur3948
126,8.52,1.48,Male,No,Thur,Lunch,2,4.26,Mario Bradshaw,4.520000e+15,Thur6719
127,14.52,2.00,Female,No,Thur,Lunch,2,7.26,Jessica Simmons,2.130000e+14,Thur1512
128,11.38,2.00,Female,No,Thur,Lunch,2,5.69,Christine Perkins,3.550000e+15,Thur8551
129,22.82,2.18,Male,No,Thur,Lunch,3,7.61,Raymond Torres,4.860000e+12,Thur9424
130,19.08,1.50,Male,No,Thur,Lunch,2,9.54,Seth Sexton,2.130000e+14,Thur1446
131,20.27,2.83,Female,No,Thur,Lunch,2,10.14,Ashley Burke,5.390000e+15,Thur9005
132,11.17,1.50,Female,No,Thur,Lunch,2,5.58,Taylor Gonzalez,6.010000e+15,Thur7783
133,12.26,2.00,Female,No,Thur,Lunch,2,6.13,Kaitlin Wolf,6.760000e+11,Thur1561
134,18.26,3.25,Female,No,Thur,Lunch,2,9.13,Karen Rodriguez,4.950000e+12,Thur75
135,8.51,1.25,Female,No,Thur,Lunch,2,4.26,Rebecca Harris,4.320000e+15,Thur6600
136,10.33,2.00,Female,No,Thur,Lunch,2,5.16,Donna Kelly,1.800000e+14,Thur1393
137,14.15,2.00,Female,No,Thur,Lunch,2,7.08,Vanessa Morris,2.130000e+14,Thur3890
138,16.00,2.00,Male,Yes,Thur,Lunch,2,8.00,Jason Burgess,3.560000e+15,Thur2710
139,13.16,2.75,Female,No,Thur,Lunch,2,6.58,Lindsey Meyer,6.760000e+11,Thur6245
140,17.47,3.50,Female,No,Thur,Lunch,2,8.74,Kayla Rios,5.230000e+15,Thur3906
141,34.30,6.70,Male,No,Thur,Lunch,6,5.72,Steven Carlson,3.530000e+15,Thur1025
142,41.19,5.00,Male,No,Thur,Lunch,5,8.24,Eric Andrews,4.360000e+15,Thur3621
143,27.05,5.00,Female,No,Thur,Lunch,6,4.51,Regina Jones,4.310000e+12,Thur6179
144,16.43,2.30,Female,No,Thur,Lunch,2,8.22,Linda Jones,6.540000e+15,Thur9002
145,8.35,1.50,Female,No,Thur,Lunch,2,4.18,Amy Young,4.290000e+12,Thur9331
146,18.64,1.36,Female,No,Thur,Lunch,3,6.21,Kelly Estrada,6.046330e+10,Thur3941
147,11.87,1.63,Female,No,Thur,Lunch,2,5.94,Annette Cunningham,6.760000e+11,Thur4780
148,9.78,1.73,Male,No,Thur,Lunch,2,4.89,David Stewart,3.580000e+15,Thur7276
149,7.51,2.00,Male,No,Thur,Lunch,2,3.76,Daniel Robbins,4.820000e+15,Thur6321
150,14.07,2.50,Male,No,Sun,Dinner,2,7.04,Luke Rice,4.810000e+15,Sun8863
151,13.13,2.00,Male,No,Sun,Dinner,2,6.56,Jason Arnold,3.570000e+15,Sun2127
152,17.26,2.74,Male,No,Sun,Dinner,3,5.75,Gregory Smith,4.290000e+12,Sun5205
153,24.55,2.00,Male,No,Sun,Dinner,4,6.14,Todd Patterson,4.420000e+15,Sun8670
154,19.77,2.00,Male,No,Sun,Dinner,4,4.94,James Smith,2.130000e+14,Sun5814
155,29.85,5.14,Female,No,Sun,Dinner,5,5.97,Madison Wilson,4.210000e+15,Sun9176
156,48.17,5.00,Male,No,Sun,Dinner,6,8.03,Ryan Gonzales,3.520000e+15,Sun7518
157,25.00,3.75,Female,No,Sun,Dinner,4,6.25,Laura Robles,2.130000e+14,Sun7015
158,13.39,2.61,Female,No,Sun,Dinner,2,6.70,Ashley Boyd,3.570000e+15,Sun982
159,16.49,2.00,Male,No,Sun,Dinner,4,4.12,Christopher Soto,3.050000e+13,Sun1781
160,21.50,3.50,Male,No,Sun,Dinner,4,5.38,Travis Gonzalez,3.530000e+15,Sun245
161,12.66,2.50,Male,No,Sun,Dinner,2,6.33,Brandon Oconnor,4.410000e+15,Sun5879
162,16.21,2.00,Female,No,Sun,Dinner,3,5.40,Jennifer Baird,4.230000e+15,Sun5521
163,13.81,2.00,Male,No,Sun,Dinner,2,6.90,Charles Newton,5.550000e+15,Sun8594
164,17.51,3.00,Female,Yes,Sun,Dinner,2,8.76,Audrey Griffin,3.500000e+15,Sun444
165,24.52,3.48,Male,No,Sun,Dinner,3,8.17,Jacob Hansen,4.030000e+12,Sun9043
166,20.76,2.24,Male,No,Sun,Dinner,2,10.38,Gordon Lane,4.110000e+15,Sun6738
167,31.71,4.50,Male,No,Sun,Dinner,4,7.93,Michael Lawson,3.570000e+15,Sun3719
168,10.59,1.61,Female,Yes,Sat,Dinner,2,5.30,Sara Jimenez,5.020000e+11,Sat9795
169,10.63,2.00,Female,Yes,Sat,Dinner,2,5.32,Amy Hill,3.540000e+15,Sat1788
170,50.81,10.00,Male,Yes,Sat,Dinner,3,16.94,Gregory Clark,5.470000e+15,Sat1954
171,15.81,3.16,Male,Yes,Sat,Dinner,2,7.90,David Hall,5.020000e+11,Sat6750
172,7.25,5.15,Male,Yes,Sun,Dinner,2,3.62,Larry White,3.040000e+13,Sun9209
173,31.85,3.18,Male,Yes,Sun,Dinner,2,15.92,Scott Perez,3.580000e+15,Sun9335
174,16.82,4.00,Male,Yes,Sun,Dinner,2,8.41,Brian Miles,3.590000e+15,Sun7621
175,32.90,3.11,Male,Yes,Sun,Dinner,2,16.45,Nathan Reynolds,3.700000e+14,Sun5109
176,17.89,2.00,Male,Yes,Sun,Dinner,2,8.94,Walter Simmons,6.010000e+15,Sun5961
177,14.48,2.00,Male,Yes,Sun,Dinner,2,7.24,John Dudley,4.570000e+15,Sun6203
178,9.60,4.00,Female,Yes,Sun,Dinner,2,4.80,Melanie Gray,4.210000e+12,Sun4598
179,34.63,3.55,Male,Yes,Sun,Dinner,2,17.32,Brian Bailey,3.470000e+14,Sun9851
180,34.65,3.68,Male,Yes,Sun,Dinner,4,8.66,James Hebert DDS,6.760000e+11,Sun7544
181,23.33,5.65,Male,Yes,Sun,Dinner,2,11.66,Jason Cox,6.560000e+15,Sun3402
182,45.35,3.50,Male,Yes,Sun,Dinner,3,15.12,Jose Parsons,4.110000e+15,Sun2337
183,23.17,6.50,Male,Yes,Sun,Dinner,4,5.79,Dr. Michael James,4.720000e+12,Sun6059
184,40.55,3.00,Male,Yes,Sun,Dinner,2,20.27,Stephen Cox,3.550000e+15,Sun5140
185,20.69,5.00,Male,No,Sun,Dinner,5,4.14,Joseph Howell,3.040000e+13,Sun5842
186,20.90,3.50,Female,Yes,Sun,Dinner,3,6.97,Heidi Atkinson,4.420000e+15,Sun4254
187,30.46,2.00,Male,Yes,Sun,Dinner,5,6.09,David Barrett,4.790000e+15,Sun9987
188,18.15,3.50,Female,Yes,Sun,Dinner,3,6.05,Glenda Wiggins,5.780000e+11,Sun430
189,23.10,4.00,Male,Yes,Sun,Dinner,3,7.70,Richard Stevens,3.560000e+15,Sun1821
190,15.69,1.50,Male,Yes,Sun,Dinner,2,7.84,Riley Barnes,1.800000e+14,Sun5104
191,19.81,4.19,Female,Yes,Thur,Lunch,2,9.90,Kristy Boyd,4.320000e+15,Thur967
192,28.44,2.56,Male,Yes,Thur,Lunch,2,14.22,Dr. Jeffrey Rich,4.740000e+12,Thur4334
193,15.48,2.02,Male,Yes,Thur,Lunch,2,7.74,Raymond Sullivan,1.800000e+14,Thur606
194,16.58,4.00,Male,Yes,Thur,Lunch,2,8.29,Benjamin Weber,6.760000e+11,Thur9318
195,7.56,1.44,Male,No,Thur,Lunch,2,3.78,Michael White,4.870000e+15,Thur697
196,10.34,2.00,Male,Yes,Thur,Lunch,2,5.17,Eric Martin,3.040000e+13,Thur9862
197,43.11,5.00,Female,Yes,Thur,Lunch,4,10.78,Brooke Soto,5.540000e+15,Thur9313
198,13.00,2.00,Female,Yes,Thur,Lunch,2,6.50,Katherine Bond,4.930000e+12,Thur437
199,13.51,2.00,Male,Yes,Thur,Lunch,2,6.76,Joseph Murphy MD,6.550000e+15,Thur2428
200,18.71,4.00,Male,Yes,Thur,Lunch,3,6.24,Jason Conrad,4.580000e+12,Thur6048
201,12.74,2.01,Female,Yes,Thur,Lunch,2,6.37,Abigail Parks,3.590000e+15,Thur2544
202,13.00,2.00,Female,Yes,Thur,Lunch,2,6.50,Ashley Shaw,1.800000e+14,Thur1301
203,16.40,2.50,Female,Yes,Thur,Lunch,2,8.20,Toni Brooks,3.580000e+15,Thur7770
204,20.53,4.00,Male,Yes,Thur,Lunch,4,5.13,Scott Kim,3.570000e+15,Thur2160
205,16.47,3.23,Female,Yes,Thur,Lunch,3,5.49,Carly Reyes,4.790000e+12,Thur8084
206,26.59,3.41,Male,Yes,Sat,Dinner,3,8.86,Daniel Owens,3.900000e+13,Sat1
207,38.73,3.00,Male,Yes,Sat,Dinner,4,9.68,Ricky Ramirez,3.480000e+14,Sat4505
208,24.27,2.03,Male,Yes,Sat,Dinner,2,12.14,Jason Carter,4.270000e+15,Sat6048
209,12.76,2.23,Female,Yes,Sat,Dinner,2,6.38,Sarah Cunningham,3.420000e+14,Sat1274
210,30.06,2.00,Male,Yes,Sat,Dinner,3,10.02,Shawn Mendoza,3.020000e+13,Sat8361
211,25.89,5.16,Male,Yes,Sat,Dinner,4,6.47,Christopher Li,6.010000e+15,Sat6735
212,48.33,9.00,Male,No,Sat,Dinner,4,12.08,Alex Williamson,6.760000e+11,Sat4590
213,13.27,2.50,Female,Yes,Sat,Dinner,2,6.64,Robin Andersen,5.800000e+11,Sat1374
214,28.17,6.50,Female,Yes,Sat,Dinner,3,9.39,Marissa Jackson,4.920000e+15,Sat3374
215,12.90,1.10,Female,Yes,Sat,Dinner,2,6.45,Jessica Owen,4.730000e+12,Sat6983
216,28.15,3.00,Male,Yes,Sat,Dinner,5,5.63,Shawn Barnett PhD,4.590000e+12,Sat7320
217,11.59,1.50,Male,Yes,Sat,Dinner,2,5.80,Gary Orr,3.030000e+13,Sat8489
218,7.74,1.44,Male,Yes,Sat,Dinner,2,3.87,Nicholas Archer,3.410000e+14,Sat4772
219,30.14,3.09,Female,Yes,Sat,Dinner,4,7.54,Shelby House,5.020000e+11,Sat8863
220,12.16,2.20,Male,Yes,Fri,Lunch,2,6.08,Ricky Johnson,2.130000e+14,Fri4607
221,13.42,3.48,Female,Yes,Fri,Lunch,2,6.71,Leslie Kaufman,3.790000e+14,Fri7511
222,8.58,1.92,Male,Yes,Fri,Lunch,1,8.58,Jason Lawrence,3.510000e+15,Fri6624
223,15.98,3.00,Female,No,Fri,Lunch,3,5.33,Mary Rivera,5.340000e+15,Fri6014
224,13.42,1.58,Male,Yes,Fri,Lunch,2,6.71,Ronald Vaughn DVM,3.420000e+14,Fri5959
225,16.27,2.50,Female,Yes,Fri,Lunch,2,8.14,Whitney Arnold,3.580000e+15,Fri6665
226,10.09,2.00,Female,Yes,Fri,Lunch,2,5.04,Ruth Weiss,5.270000e+15,Fri6359
227,20.45,3.00,Male,No,Sat,Dinner,4,5.11,Robert Bradley,2.130000e+14,Sat4319
228,13.28,2.72,Male,No,Sat,Dinner,2,6.64,Glenn Jones,5.020000e+11,Sat2937
229,22.12,2.88,Female,Yes,Sat,Dinner,2,11.06,Jennifer Russell,4.790000e+12,Sat3943
230,24.01,2.00,Male,Yes,Sat,Dinner,4,6.00,Michael Osborne,4.260000e+12,Sat7872
231,15.69,3.00,Male,Yes,Sat,Dinner,3,5.23,Jason Parks,4.810000e+12,Sat6334
232,11.61,3.39,Male,No,Sat,Dinner,2,5.80,James Taylor,6.010000e+15,Sat2124
233,10.77,1.47,Male,No,Sat,Dinner,2,5.38,Paul Novak,6.010000e+15,Sat1467
234,15.53,3.00,Male,Yes,Sat,Dinner,2,7.76,Tracy Douglas,4.100000e+15,Sat7220
235,10.07,1.25,Male,No,Sat,Dinner,2,5.04,Sean Gonzalez,3.530000e+15,Sat4615
236,12.60,1.00,Male,Yes,Sat,Dinner,2,6.30,Matthew Myers,3.540000e+15,Sat5032
237,32.83,1.17,Male,Yes,Sat,Dinner,2,16.42,Thomas Brown,4.280000e+15,Sat2929
238,35.83,4.67,Female,No,Sat,Dinner,3,11.94,Kimberly Crane,6.760000e+11,Sat9777
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5.300000e+15,Sat2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3.510000e+15,Sat1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6.010000e+15,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4.380000e+12,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3.510000e+15,Thur672

#ROW DELETE

In [116]:
#Row Drop

df.drop(index=range(0,21)) #0 to 21 column drop

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,total_amt
21,20.29,2.75,Female,No,Sat,Dinner,2,10.14,Natalie Gardner,5.450000e+15,Sat9618,23.0
22,15.77,2.23,Female,No,Sat,Dinner,2,7.88,Ashley Shelton,3.520000e+15,Sat9786,18.0
23,39.42,7.58,Male,No,Sat,Dinner,4,9.86,Lance Peterson,3.540000e+15,Sat239,47.0
24,19.82,3.18,Male,No,Sat,Dinner,2,9.91,Christopher Ross,3.670000e+13,Sat6236,23.0
25,17.81,2.34,Male,No,Sat,Dinner,4,4.45,Robert Perkins,3.050000e+13,Sat907,20.0
26,13.37,2.00,Male,No,Sat,Dinner,2,6.68,Kyle Avery,6.530000e+15,Sat6651,15.0
27,12.69,2.00,Male,No,Sat,Dinner,2,6.34,Patrick Barber,3.020000e+13,Sat394,15.0
28,21.70,4.30,Male,No,Sat,Dinner,2,10.85,David Collier,5.530000e+15,Sat3697,26.0
29,19.65,3.00,Female,No,Sat,Dinner,2,9.82,Melinda Murphy,5.490000e+15,Sat2467,23.0
30,9.55,1.45,Male,No,Sat,Dinner,2,4.78,Grant Hall,3.020000e+13,Sat4099,11.0
31,18.35,2.50,Male,No,Sat,Dinner,4,4.59,Danny Santiago,6.300000e+11,Sat4947,21.0
32,15.06,3.00,Female,No,Sat,Dinner,2,7.53,Amanda Wilson,2.130000e+14,Sat1327,18.0
33,20.69,2.45,Female,No,Sat,Dinner,4,5.17,Amber Francis,3.780000e+14,Sat6649,23.0
34,17.78,3.27,Male,No,Sat,Dinner,2,8.89,Jacob Castillo,3.550000e+15,Sat8124,21.0
35,24.06,3.60,Male,No,Sat,Dinner,3,8.02,Joseph Mullins,5.520000e+15,Sat632,28.0
36,16.31,2.00,Male,No,Sat,Dinner,3,5.44,William Ford,3.530000e+15,Sat9139,18.0
37,16.93,3.07,Female,No,Sat,Dinner,3,5.64,Erin Lewis,5.160000e+15,Sat6406,20.0
38,18.69,2.31,Male,No,Sat,Dinner,3,6.23,Brandon Bradley,4.430000e+15,Sat4056,21.0
39,31.27,5.00,Male,No,Sat,Dinner,3,10.42,Mr. Brandon Berry,6.010000e+15,Sat6373,36.0
40,16.04,2.24,Male,No,Sat,Dinner,3,5.35,Adam Edwards,3.540000e+15,Sat8549,18.0
41,17.46,2.54,Male,No,Sun,Dinner,2,8.73,David Boyer,3.540000e+15,Sun9460,20.0
42,13.94,3.06,Male,No,Sun,Dinner,2,6.97,Bryan Brown,3.620000e+13,Sun1699,17.0
43,9.68,1.32,Male,No,Sun,Dinner,2,4.84,Christopher Spears,4.390000e+15,Sun3279,11.0
44,30.40,5.60,Male,No,Sun,Dinner,4,7.60,Todd Cooper,5.040000e+11,Sun2274,36.0
45,18.29,3.00,Male,No,Sun,Dinner,2,9.14,Richard Fitzgerald,3.750000e+14,Sun8643,21.0
46,22.23,5.00,Male,No,Sun,Dinner,2,11.12,Joshua Gilmore,4.290000e+12,Sun7097,27.0
47,32.40,6.00,Male,No,Sun,Dinner,4,8.10,James Barnes,3.550000e+15,Sun9677,38.0
48,28.55,2.05,Male,No,Sun,Dinner,3,9.52,Austin Fisher,6.010000e+15,Sun4142,31.0
49,18.04,3.00,Male,No,Sun,Dinner,2,9.02,William Roth,6.570000e+15,Sun9774,21.0
50,12.54,2.50,Male,No,Sun,Dinner,2,6.27,Jeremiah Neal,2.230000e+15,Sun2021,15.0
51,10.29,2.60,Female,No,Sun,Dinner,2,5.14,Jessica Ibarra,5.000000e+12,Sun4474,13.0
52,34.81,5.20,Female,No,Sun,Dinner,4,8.70,Emily Daniel,4.290000e+15,Sun6165,40.0
53,9.94,1.56,Male,No,Sun,Dinner,2,4.97,Curtis Morgan,4.630000e+15,Sun4561,12.0
54,25.56,4.34,Male,No,Sun,Dinner,4,6.39,Ronald Owens,6.570000e+15,Sun9470,30.0
55,19.49,3.51,Male,No,Sun,Dinner,2,9.74,Michael Hamilton,6.500000e+15,Sun1118,23.0
56,38.01,3.00,Male,Yes,Sat,Dinner,4,9.50,James Christensen DDS,3.500000e+14,Sat8903,41.0
57,26.41,1.50,Female,No,Sat,Dinner,2,13.20,Melody Simon,4.750000e+15,Sat8980,28.0
58,11.24,1.76,Male,Yes,Sat,Dinner,2,5.62,Troy Guerrero,3.560000e+15,Sat6683,13.0
59,48.27,6.73,Male,No,Sat,Dinner,4,12.07,Brian Ortiz,6.600000e+15,Sat8139,55.0
60,20.29,3.21,Male,Yes,Sat,Dinner,2,10.14,Anthony Mclean,3.480000e+14,Sat2353,24.0
61,13.81,2.00,Male,Yes,Sat,Dinner,2,6.90,Ryan Hernandez,4.770000e+12,Sat3030,16.0
62,11.02,1.98,Male,Yes,Sat,Dinner,2,5.51,Joseph Hart,1.800000e+14,Sat2265,13.0
63,18.29,3.76,Male,Yes,Sat,Dinner,4,4.57,Chad Hart,5.800000e+11,Sat4178,22.0
64,17.59,2.64,Male,No,Sat,Dinner,3,5.86,Michael Johnson,2.220000e+15,Sat1667,20.0
65,20.08,3.15,Male,No,Sat,Dinner,3,6.69,Justin Dixon,1.800000e+14,Sat6840,23.0
66,16.45,2.47,Female,No,Sat,Dinner,2,8.22,Rachel Vaughn,3.570000e+15,Sat4750,19.0
67,3.07,1.00,Female,Yes,Sat,Dinner,1,3.07,Tiffany Brock,4.360000e+15,Sat3455,4.0
68,20.23,2.01,Male,No,Sat,Dinner,2,10.12,Mr. Travis Bailey Jr.,6.040679e+10,Sat561,22.0
69,15.01,2.09,Male,Yes,Sat,Dinner,2,7.50,Adam Hall,4.700000e+15,Sat855,17.0
70,12.02,1.97,Male,No,Sat,Dinner,2,6.01,Max Brown,2.130000e+14,Sat2100,14.0
71,17.07,3.00,Female,No,Sat,Dinner,3,5.69,Teresa Fisher,5.440000e+15,Sat3469,20.0
72,26.86,3.14,Female,Yes,Sat,Dinner,2,13.43,Victoria Obrien MD,4.220000e+12,Sat1967,30.0
73,25.28,5.00,Female,Yes,Sat,Dinner,2,12.64,Julie Holmes,5.420000e+15,Sat6065,30.0
74,14.73,2.20,Female,No,Sat,Dinner,2,7.36,Ashley Harris,5.020000e+11,Sat6548,17.0
75,10.51,1.25,Male,No,Sat,Dinner,2,5.26,Kenneth Hayes,2.130000e+14,Sat5056,12.0
76,17.92,3.08,Male,Yes,Sat,Dinner,2,8.96,Mark Smith,6.760000e+11,Sat9908,21.0
77,27.20,4.00,Male,No,Thur,Lunch,4,6.80,John Davis,3.030000e+13,Thur4924,31.0
78,22.76,3.00,Male,No,Thur,Lunch,2,11.38,Chris Hahn,3.590000e+15,Thur2863,26.0
79,17.29,2.71,Male,No,Thur,Lunch,2,8.64,Brian Diaz,4.760000e+15,Thur9501,20.0
80,19.44,3.00,Male,Yes,Thur,Lunch,2,9.72,Louis Torres,3.880000e+13,Thur6453,22.0
81,16.66,3.40,Male,No,Thur,Lunch,2,8.33,William Martin,4.550000e+15,Thur8232,20.0
82,10.07,1.83,Female,No,Thur,Lunch,1,10.07,Julie Moody,6.300000e+11,Thur4909,12.0
83,32.68,5.00,Male,Yes,Thur,Lunch,2,16.34,Daniel Murphy,5.360000e+15,Thur8801,38.0
84,15.98,2.03,Male,No,Thur,Lunch,2,7.99,Jason Jones,4.440000e+15,Thur1944,18.0
85,34.83,5.17,Female,No,Thur,Lunch,4,8.71,Shawna Cook,6.010000e+15,Thur7972,40.0
86,13.03,2.00,Male,No,Thur,Lunch,2,6.52,Derek Thomas,2.130000e+14,Thur6793,15.0
87,18.28,4.00,Male,No,Thur,Lunch,2,9.14,Donald Williams,5.360000e+15,Thur3636,22.0
88,24.71,5.85,Male,No,Thur,Lunch,2,12.36,Roger Taylor,4.410000e+12,Thur9003,31.0
89,21.16,3.00,Male,No,Thur,Lunch,2,10.58,Keith Lewis,4.360000e+15,Thur6273,24.0
90,28.97,3.00,Male,Yes,Fri,Dinner,2,14.48,Daniel Mason,3.600000e+15,Fri4175,32.0
91,22.49,3.50,Male,No,Fri,Dinner,2,11.24,Earl Horn,6.010000e+15,Fri5700,26.0
92,5.75,1.00,Female,Yes,Fri,Dinner,2,2.88,Leah Ramirez,3.510000e+15,Fri3780,7.0
93,16.32,4.30,Female,Yes,Fri,Dinner,2,8.16,Natalie Nguyen,5.180000e+15,Fri6963,21.0
94,22.75,3.25,Female,No,Fri,Dinner,2,11.38,Jamie Garza,6.760000e+11,Fri2318,26.0
95,40.17,4.73,Male,Yes,Fri,Dinner,4,10.04,Aaron Bentley,1.800000e+14,Fri9628,45.0
96,27.28,4.00,Male,Yes,Fri,Dinner,2,13.64,Eric Carter,4.560000e+15,Fri3159,31.0
97,12.03,1.50,Male,Yes,Fri,Dinner,2,6.02,Eric Herrera,5.800000e+11,Fri9268,14.0
98,21.01,3.00,Male,Yes,Fri,Dinner,2,10.50,Michael Li,4.830000e+15,Fri144,24.0
99,12.46,1.50,Male,No,Fri,Dinner,2,6.23,Edward Carter,3.470000e+14,Fri5575,14.0
100,11.35,2.50,Female,Yes,Fri,Dinner,2,5.68,Lori Lynch,3.860000e+13,Fri4106,14.0
101,15.38,3.00,Female,Yes,Fri,Dinner,2,7.69,Tiffany Colon,6.010000e+15,Fri8382,18.0
102,44.30,2.50,Female,Yes,Sat,Dinner,3,14.77,Heather Cohen,3.800000e+14,Sat6240,47.0
103,22.42,3.48,Female,Yes,Sat,Dinner,2,11.21,Kathleen Hawkins,3.480000e+14,Sat1015,26.0
104,20.92,4.08,Female,No,Sat,Dinner,2,10.46,Gabrielle Frederick,4.010000e+15,Sat3194,25.0
105,15.36,1.64,Male,Yes,Sat,Dinner,2,7.68,David Price,4.030000e+12,Sat5106,17.0
106,20.49,4.06,Male,Yes,Sat,Dinner,2,10.24,Karl Mcdaniel,1.800000e+14,Sat7865,25.0
107,25.21,4.29,Male,Yes,Sat,Dinner,2,12.60,Jason Mullen,4.740000e+12,Sat5196,30.0
108,18.24,3.76,Male,No,Sat,Dinner,2,9.12,Steven Grant,4.110000e+15,Sat6376,22.0
109,14.31,4.00,Female,Yes,Sat,Dinner,2,7.16,Amanda Anderson,3.760000e+14,Sat2614,18.0
110,14.00,3.00,Male,No,Sat,Dinner,2,7.00,James Sanchez,3.450000e+14,Sat6801,17.0
111,7.25,1.00,Female,No,Sat,Dinner,1,7.25,Terri Jones,3.560000e+15,Sat4801,8.0
112,38.07,4.00,Male,No,Sun,Dinner,3,12.69,Jeff Lopez,3.570000e+15,Sun591,42.0
113,23.95,2.55,Male,No,Sun,Dinner,2,11.98,John Joyce,6.570000e+15,Sun1885,26.0
114,25.71,4.00,Female,No,Sun,Dinner,3,8.57,Katie Smith,5.400000e+15,Sun6492,30.0
115,17.31,3.50,Female,No,Sun,Dinner,2,8.65,Kayla Stone,3.790000e+14,Sun8746,21.0
116,29.93,5.07,Male,No,Sun,Dinner,4,7.48,Shawn Blake,4.690000e+15,Sun22,35.0
117,10.65,1.50,Female,No,Thur,Lunch,2,5.32,Linda Zhang,3.560000e+15,Thur9593,12.0
118,12.43,1.80,Female,No,Thur,Lunch,2,6.22,Dr. Caroline Tucker,5.020000e+11,Thur8084,14.0
119,24.08,2.92,Female,No,Thur,Lunch,4,6.02,Melanie Jordan,6.760000e+11,Thur8063,27.0
120,11.69,2.31,Male,No,Thur,Lunch,2,5.84,Kenneth Goodman,4.890000e+12,Thur8289,14.0
121,13.42,1.68,Female,No,Thur,Lunch,2,6.71,Laura Garcia,5.180000e+15,Thur2158,15.0
122,14.26,2.50,Male,No,Thur,Lunch,2,7.13,Perry Garcia,1.800000e+14,Thur3579,17.0
123,15.95,2.00,Male,No,Thur,Lunch,2,7.98,Christopher Lang,4.820000e+15,Thur1992,18.0
124,12.48,2.52,Female,No,Thur,Lunch,2,6.24,Jordan Diaz,4.470000e+15,Thur208,15.0
125,29.80,4.20,Female,No,Thur,Lunch,6,4.97,Angela Sanchez,5.040000e+11,Thur3948,34.0
126,8.52,1.48,Male,No,Thur,Lunch,2,4.26,Mario Bradshaw,4.520000e+15,Thur6719,10.0
127,14.52,2.00,Female,No,Thur,Lunch,2,7.26,Jessica Simmons,2.130000e+14,Thur1512,17.0
128,11.38,2.00,Female,No,Thur,Lunch,2,5.69,Christine Perkins,3.550000e+15,Thur8551,13.0
129,22.82,2.18,Male,No,Thur,Lunch,3,7.61,Raymond Torres,4.860000e+12,Thur9424,25.0
130,19.08,1.50,Male,No,Thur,Lunch,2,9.54,Seth Sexton,2.130000e+14,Thur1446,21.0
131,20.27,2.83,Female,No,Thur,Lunch,2,10.14,Ashley Burke,5.390000e+15,Thur9005,23.0
132,11.17,1.50,Female,No,Thur,Lunch,2,5.58,Taylor Gonzalez,6.010000e+15,Thur7783,13.0
133,12.26,2.00,Female,No,Thur,Lunch,2,6.13,Kaitlin Wolf,6.760000e+11,Thur1561,14.0
134,18.26,3.25,Female,No,Thur,Lunch,2,9.13,Karen Rodriguez,4.950000e+12,Thur75,22.0
135,8.51,1.25,Female,No,Thur,Lunch,2,4.26,Rebecca Harris,4.320000e+15,Thur6600,10.0
136,10.33,2.00,Female,No,Thur,Lunch,2,5.16,Donna Kelly,1.800000e+14,Thur1393,12.0
137,14.15,2.00,Female,No,Thur,Lunch,2,7.08,Vanessa Morris,2.130000e+14,Thur3890,16.0
138,16.00,2.00,Male,Yes,Thur,Lunch,2,8.00,Jason Burgess,3.560000e+15,Thur2710,18.0
139,13.16,2.75,Female,No,Thur,Lunch,2,6.58,Lindsey Meyer,6.760000e+11,Thur6245,16.0
140,17.47,3.50,Female,No,Thur,Lunch,2,8.74,Kayla Rios,5.230000e+15,Thur3906,21.0
141,34.30,6.70,Male,No,Thur,Lunch,6,5.72,Steven Carlson,3.530000e+15,Thur1025,41.0
142,41.19,5.00,Male,No,Thur,Lunch,5,8.24,Eric Andrews,4.360000e+15,Thur3621,46.0
143,27.05,5.00,Female,No,Thur,Lunch,6,4.51,Regina Jones,4.310000e+12,Thur6179,32.0
144,16.43,2.30,Female,No,Thur,Lunch,2,8.22,Linda Jones,6.540000e+15,Thur9002,19.0
145,8.35,1.50,Female,No,Thur,Lunch,2,4.18,Amy Young,4.290000e+12,Thur9331,10.0
146,18.64,1.36,Female,No,Thur,Lunch,3,6.21,Kelly Estrada,6.046330e+10,Thur3941,20.0
147,11.87,1.63,Female,No,Thur,Lunch,2,5.94,Annette Cunningham,6.760000e+11,Thur4780,14.0
148,9.78,1.73,Male,No,Thur,Lunch,2,4.89,David Stewart,3.580000e+15,Thur7276,12.0
149,7.51,2.00,Male,No,Thur,Lunch,2,3.76,Daniel Robbins,4.820000e+15,Thur6321,10.0
150,14.07,2.50,Male,No,Sun,Dinner,2,7.04,Luke Rice,4.810000e+15,Sun8863,17.0
151,13.13,2.00,Male,No,Sun,Dinner,2,6.56,Jason Arnold,3.570000e+15,Sun2127,15.0
152,17.26,2.74,Male,No,Sun,Dinner,3,5.75,Gregory Smith,4.290000e+12,Sun5205,20.0
153,24.55,2.00,Male,No,Sun,Dinner,4,6.14,Todd Patterson,4.420000e+15,Sun8670,27.0
154,19.77,2.00,Male,No,Sun,Dinner,4,4.94,James Smith,2.130000e+14,Sun5814,22.0
155,29.85,5.14,Female,No,Sun,Dinner,5,5.97,Madison Wilson,4.210000e+15,Sun9176,35.0
156,48.17,5.00,Male,No,Sun,Dinner,6,8.03,Ryan Gonzales,3.520000e+15,Sun7518,53.0
157,25.00,3.75,Female,No,Sun,Dinner,4,6.25,Laura Robles,2.130000e+14,Sun7015,29.0
158,13.39,2.61,Female,No,Sun,Dinner,2,6.70,Ashley Boyd,3.570000e+15,Sun982,16.0
159,16.49,2.00,Male,No,Sun,Dinner,4,4.12,Christopher Soto,3.050000e+13,Sun1781,18.0
160,21.50,3.50,Male,No,Sun,Dinner,4,5.38,Travis Gonzalez,3.530000e+15,Sun245,25.0
161,12.66,2.50,Male,No,Sun,Dinner,2,6.33,Brandon Oconnor,4.410000e+15,Sun5879,15.0
162,16.21,2.00,Female,No,Sun,Dinner,3,5.40,Jennifer Baird,4.230000e+15,Sun5521,18.0
163,13.81,2.00,Male,No,Sun,Dinner,2,6.90,Charles Newton,5.550000e+15,Sun8594,16.0
164,17.51,3.00,Female,Yes,Sun,Dinner,2,8.76,Audrey Griffin,3.500000e+15,Sun444,21.0
165,24.52,3.48,Male,No,Sun,Dinner,3,8.17,Jacob Hansen,4.030000e+12,Sun9043,28.0
166,20.76,2.24,Male,No,Sun,Dinner,2,10.38,Gordon Lane,4.110000e+15,Sun6738,23.0
167,31.71,4.50,Male,No,Sun,Dinner,4,7.93,Michael Lawson,3.570000e+15,Sun3719,36.0
168,10.59,1.61,Female,Yes,Sat,Dinner,2,5.30,Sara Jimenez,5.020000e+11,Sat9795,12.0
169,10.63,2.00,Female,Yes,Sat,Dinner,2,5.32,Amy Hill,3.540000e+15,Sat1788,13.0
170,50.81,10.00,Male,Yes,Sat,Dinner,3,16.94,Gregory Clark,5.470000e+15,Sat1954,61.0
171,15.81,3.16,Male,Yes,Sat,Dinner,2,7.90,David Hall,5.020000e+11,Sat6750,19.0
172,7.25,5.15,Male,Yes,Sun,Dinner,2,3.62,Larry White,3.040000e+13,Sun9209,12.0
173,31.85,3.18,Male,Yes,Sun,Dinner,2,15.92,Scott Perez,3.580000e+15,Sun9335,35.0
174,16.82,4.00,Male,Yes,Sun,Dinner,2,8.41,Brian Miles,3.590000e+15,Sun7621,21.0
175,32.90,3.11,Male,Yes,Sun,Dinner,2,16.45,Nathan Reynolds,3.700000e+14,Sun5109,36.0
176,17.89,2.00,Male,Yes,Sun,Dinner,2,8.94,Walter Simmons,6.010000e+15,Sun5961,20.0
177,14.48,2.00,Male,Yes,Sun,Dinner,2,7.24,John Dudley,4.570000e+15,Sun6203,16.0
178,9.60,4.00,Female,Yes,Sun,Dinner,2,4.80,Melanie Gray,4.210000e+12,Sun4598,14.0
179,34.63,3.55,Male,Yes,Sun,Dinner,2,17.32,Brian Bailey,3.470000e+14,Sun9851,38.0
180,34.65,3.68,Male,Yes,Sun,Dinner,4,8.66,James Hebert DDS,6.760000e+11,Sun7544,38.0
181,23.33,5.65,Male,Yes,Sun,Dinner,2,11.66,Jason Cox,6.560000e+15,Sun3402,29.0
182,45.35,3.50,Male,Yes,Sun,Dinner,3,15.12,Jose Parsons,4.110000e+15,Sun2337,49.0
183,23.17,6.50,Male,Yes,Sun,Dinner,4,5.79,Dr. Michael James,4.720000e+12,Sun6059,30.0
184,40.55,3.00,Male,Yes,Sun,Dinner,2,20.27,Stephen Cox,3.550000e+15,Sun5140,44.0
185,20.69,5.00,Male,No,Sun,Dinner,5,4.14,Joseph Howell,3.040000e+13,Sun5842,26.0
186,20.90,3.50,Female,Yes,Sun,Dinner,3,6.97,Heidi Atkinson,4.420000e+15,Sun4254,24.0
187,30.46,2.00,Male,Yes,Sun,Dinner,5,6.09,David Barrett,4.790000e+15,Sun9987,32.0
188,18.15,3.50,Female,Yes,Sun,Dinner,3,6.05,Glenda Wiggins,5.780000e+11,Sun430,22.0
189,23.10,4.00,Male,Yes,Sun,Dinner,3,7.70,Richard Stevens,3.560000e+15,Sun1821,27.0
190,15.69,1.50,Male,Yes,Sun,Dinner,2,7.84,Riley Barnes,1.800000e+14,Sun5104,17.0
191,19.81,4.19,Female,Yes,Thur,Lunch,2,9.90,Kristy Boyd,4.320000e+15,Thur967,24.0
192,28.44,2.56,Male,Yes,Thur,Lunch,2,14.22,Dr. Jeffrey Rich,4.740000e+12,Thur4334,31.0
193,15.48,2.02,Male,Yes,Thur,Lunch,2,7.74,Raymond Sullivan,1.800000e+14,Thur606,18.0
194,16.58,4.00,Male,Yes,Thur,Lunch,2,8.29,Benjamin Weber,6.760000e+11,Thur9318,21.0
195,7.56,1.44,Male,No,Thur,Lunch,2,3.78,Michael White,4.870000e+15,Thur697,9.0
196,10.34,2.00,Male,Yes,Thur,Lunch,2,5.17,Eric Martin,3.040000e+13,Thur9862,12.0
197,43.11,5.00,Female,Yes,Thur,Lunch,4,10.78,Brooke Soto,5.540000e+15,Thur9313,48.0
198,13.00,2.00,Female,Yes,Thur,Lunch,2,6.50,Katherine Bond,4.930000e+12,Thur437,15.0
199,13.51,2.00,Male,Yes,Thur,Lunch,2,6.76,Joseph Murphy MD,6.550000e+15,Thur2428,16.0
200,18.71,4.00,Male,Yes,Thur,Lunch,3,6.24,Jason Conrad,4.580000e+12,Thur6048,23.0
201,12.74,2.01,Female,Yes,Thur,Lunch,2,6.37,Abigail Parks,3.590000e+15,Thur2544,15.0
202,13.00,2.00,Female,Yes,Thur,Lunch,2,6.50,Ashley Shaw,1.800000e+14,Thur1301,15.0
203,16.40,2.50,Female,Yes,Thur,Lunch,2,8.20,Toni Brooks,3.580000e+15,Thur7770,19.0
204,20.53,4.00,Male,Yes,Thur,Lunch,4,5.13,Scott Kim,3.570000e+15,Thur2160,25.0
205,16.47,3.23,Female,Yes,Thur,Lunch,3,5.49,Carly Reyes,4.790000e+12,Thur8084,20.0
206,26.59,3.41,Male,Yes,Sat,Dinner,3,8.86,Daniel Owens,3.900000e+13,Sat1,30.0
207,38.73,3.00,Male,Yes,Sat,Dinner,4,9.68,Ricky Ramirez,3.480000e+14,Sat4505,42.0
208,24.27,2.03,Male,Yes,Sat,Dinner,2,12.14,Jason Carter,4.270000e+15,Sat6048,26.0
209,12.76,2.23,Female,Yes,Sat,Dinner,2,6.38,Sarah Cunningham,3.420000e+14,Sat1274,15.0
210,30.06,2.00,Male,Yes,Sat,Dinner,3,10.02,Shawn Mendoza,3.020000e+13,Sat8361,32.0
211,25.89,5.16,Male,Yes,Sat,Dinner,4,6.47,Christopher Li,6.010000e+15,Sat6735,31.0
212,48.33,9.00,Male,No,Sat,Dinner,4,12.08,Alex Williamson,6.760000e+11,Sat4590,57.0
213,13.27,2.50,Female,Yes,Sat,Dinner,2,6.64,Robin Andersen,5.800000e+11,Sat1374,16.0
214,28.17,6.50,Female,Yes,Sat,Dinner,3,9.39,Marissa Jackson,4.920000e+15,Sat3374,35.0
215,12.90,1.10,Female,Yes,Sat,Dinner,2,6.45,Jessica Owen,4.730000e+12,Sat6983,14.0
216,28.15,3.00,Male,Yes,Sat,Dinner,5,5.63,Shawn Barnett PhD,4.590000e+12,Sat7320,31.0
217,11.59,1.50,Male,Yes,Sat,Dinner,2,5.80,Gary Orr,3.030000e+13,Sat8489,13.0
218,7.74,1.44,Male,Yes,Sat,Dinner,2,3.87,Nicholas Archer,3.410000e+14,Sat4772,9.0
219,30.14,3.09,Female,Yes,Sat,Dinner,4,7.54,Shelby House,5.020000e+11,Sat8863,33.0
220,12.16,2.20,Male,Yes,Fri,Lunch,2,6.08,Ricky Johnson,2.130000e+14,Fri4607,14.0
221,13.42,3.48,Female,Yes,Fri,Lunch,2,6.71,Leslie Kaufman,3.790000e+14,Fri7511,17.0
222,8.58,1.92,Male,Yes,Fri,Lunch,1,8.58,Jason Lawrence,3.510000e+15,Fri6624,10.0
223,15.98,3.00,Female,No,Fri,Lunch,3,5.33,Mary Rivera,5.340000e+15,Fri6014,19.0
224,13.42,1.58,Male,Yes,Fri,Lunch,2,6.71,Ronald Vaughn DVM,3.420000e+14,Fri5959,15.0
225,16.27,2.50,Female,Yes,Fri,Lunch,2,8.14,Whitney Arnold,3.580000e+15,Fri6665,19.0
226,10.09,2.00,Female,Yes,Fri,Lunch,2,5.04,Ruth Weiss,5.270000e+15,Fri6359,12.0
227,20.45,3.00,Male,No,Sat,Dinner,4,5.11,Robert Bradley,2.130000e+14,Sat4319,23.0
228,13.28,2.72,Male,No,Sat,Dinner,2,6.64,Glenn Jones,5.020000e+11,Sat2937,16.0
229,22.12,2.88,Female,Yes,Sat,Dinner,2,11.06,Jennifer Russell,4.790000e+12,Sat3943,25.0
230,24.01,2.00,Male,Yes,Sat,Dinner,4,6.00,Michael Osborne,4.260000e+12,Sat7872,26.0
231,15.69,3.00,Male,Yes,Sat,Dinner,3,5.23,Jason Parks,4.810000e+12,Sat6334,19.0
232,11.61,3.39,Male,No,Sat,Dinner,2,5.80,James Taylor,6.010000e+15,Sat2124,15.0
233,10.77,1.47,Male,No,Sat,Dinner,2,5.38,Paul Novak,6.010000e+15,Sat1467,12.0
234,15.53,3.00,Male,Yes,Sat,Dinner,2,7.76,Tracy Douglas,4.100000e+15,Sat7220,19.0
235,10.07,1.25,Male,No,Sat,Dinner,2,5.04,Sean Gonzalez,3.530000e+15,Sat4615,11.0
236,12.60,1.00,Male,Yes,Sat,Dinner,2,6.30,Matthew Myers,3.540000e+15,Sat5032,14.0
237,32.83,1.17,Male,Yes,Sat,Dinner,2,16.42,Thomas Brown,4.280000e+15,Sat2929,34.0
238,35.83,4.67,Female,No,Sat,Dinner,3,11.94,Kimberly Crane,6.760000e+11,Sat9777,40.0
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5.300000e+15,Sat2657,35.0
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3.510000e+15,Sat1766,29.0
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6.010000e+15,Sat3880,25.0
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4.380000e+12,Sat17,20.0
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3.510000e+15,Thur672,22.0

#When title in first row,we have to skip that row

In [119]:
df = pd.read_csv('updated_tips.csv',skiprows=1)

In [121]:
print(df.to_string)

<bound method DataFrame.to_string of     total_bill   tip     sex smoker  day    time  size  price_per_person  \
0        16.99  1.01  Female     No  Sun  Dinner     2              8.49
1        10.34  1.66    Male     No  Sun  Dinner     3              3.45
2        21.01  3.50    Male     No  Sun  Dinner     3              7.00
3        23.68  3.31    Male     No  Sun  Dinner     2             11.84
4        24.59  3.61  Female     No  Sun  Dinner     4              6.15
5        25.29  4.71    Male     No  Sun  Dinner     4              6.32
6         8.77  2.00    Male     No  Sun  Dinner     2              4.38
7        26.88  3.12    Male     No  Sun  Dinner     4              6.72
8        15.04  1.96    Male     No  Sun  Dinner     2              7.52
9        14.78  3.23    Male     No  Sun  Dinner     2              7.39
10       10.27  1.71    Male     No  Sun  Dinner     2              5.14
11       35.26  5.00  Female     No  Sun  Dinner     4              8.82
12       15.42  1.57    Male     No  Sun  Dinner     2              7.71
13       18.43  3.00    Male     No  Sun  Dinner     4              4.61
14       14.83  3.02  Female     No  Sun  Dinner     2              7.42
15       21.58  3.92    Male     No  Sun  Dinner     2             10.79
16       10.33  1.67  Female     No  Sun  Dinner     3              3.44
17       16.29  3.71    Male     No  Sun  Dinner     3              5.43
18       16.97  3.50  Female     No  Sun  Dinner     3              5.66
19       20.65  3.35    Male     No  Sat  Dinner     3              6.88
20       17.92  4.08    Male     No  Sat  Dinner     2              8.96
21       20.29  2.75  Female     No  Sat  Dinner     2             10.14
22       15.77  2.23  Female     No  Sat  Dinner     2              7.88
23       39.42  7.58    Male     No  Sat  Dinner     4              9.86
24       19.82  3.18    Male     No  Sat  Dinner     2              9.91
25       17.81  2.34    Male     No  Sat  Dinner     4              4.45
26       13.37  2.00    Male     No  Sat  Dinner     2              6.68
27       12.69  2.00    Male     No  Sat  Dinner     2              6.34
28       21.70  4.30    Male     No  Sat  Dinner     2             10.85
29       19.65  3.00  Female     No  Sat  Dinner     2              9.82
30        9.55  1.45    Male     No  Sat  Dinner     2              4.78
31       18.35  2.50    Male     No  Sat  Dinner     4              4.59
32       15.06  3.00  Female     No  Sat  Dinner     2              7.53
33       20.69  2.45  Female     No  Sat  Dinner     4              5.17
34       17.78  3.27    Male     No  Sat  Dinner     2              8.89
35       24.06  3.60    Male     No  Sat  Dinner     3              8.02
36       16.31  2.00    Male     No  Sat  Dinner     3              5.44
37       16.93  3.07  Female     No  Sat  Dinner     3              5.64
38       18.69  2.31    Male     No  Sat  Dinner     3              6.23
39       31.27  5.00    Male     No  Sat  Dinner     3             10.42
40       16.04  2.24    Male     No  Sat  Dinner     3              5.35
41       17.46  2.54    Male     No  Sun  Dinner     2              8.73
42       13.94  3.06    Male     No  Sun  Dinner     2              6.97
43        9.68  1.32    Male     No  Sun  Dinner     2              4.84
44       30.40  5.60    Male     No  Sun  Dinner     4              7.60
45       18.29  3.00    Male     No  Sun  Dinner     2              9.14
46       22.23  5.00    Male     No  Sun  Dinner     2             11.12
47       32.40  6.00    Male     No  Sun  Dinner     4              8.10
48       28.55  2.05    Male     No  Sun  Dinner     3              9.52
49       18.04  3.00    Male     No  Sun  Dinner     2              9.02

            Payer Name     CC Number Payment ID  total_amt
0   Christy Cunningham  3.560330e+15    Sun2959      18.00
1       Douglas Tucker  4.478070e+15    Sun4608      12.00
2       Travis Walters  6.011810e+15    Sun4458      24.51
3     Nathaniel Harris  4.676140e+15    Sun5260      26.99
4         Tonya Carter  4.832730e+15    Sun2251      28.20
5           Erik Smith  2.131400e+14    Sun9679      30.00
6   Kristopher Johnson  2.223730e+15    Sun5985      10.77
7          Robert Buck  3.514790e+15    Sun8157      30.00
8      Joseph Mcdonald  3.522870e+15    Sun6820      17.00
9        Jerome Abbott  3.532120e+15    Sun3775      18.01
10       William Riley  5.662880e+11    Sun2546      11.98
11        Diane Macias  4.577820e+15    Sun6686      40.26
12     Chad Harrington  5.770410e+11    Sun1300      16.99
13        Joshua Jones  6.011160e+15    Sun2971      21.43
14       Vanessa Jones  3.001670e+13    Sun3848      17.85
15      Matthew Reilly  1.800730e+14    Sun1878      25.50
16    Elizabeth Foster  4.240030e+15    Sun9715      12.00
17        John Pittman  6.521340e+15    Sun2998      20.00
18      Laura Martinez  3.042230e+13    Sun2789      20.47
19       Timothy Oneal  6.568070e+15    Sat9213      24.00
20         Thomas Rice  4.403300e+15    Sat1709      22.00
21     Natalie Gardner  5.448130e+15    Sat9618      23.04
22      Ashley Shelton  3.524120e+15    Sat9786      18.00
23      Lance Peterson  3.542580e+15     Sat239      47.00
24    Christopher Ross  3.673910e+13    Sat6236      23.00
25      Robert Perkins  3.050290e+13     Sat907      20.15
26          Kyle Avery  6.531340e+15    Sat6651      15.37
27      Patrick Barber  3.015560e+13     Sat394      14.69
28       David Collier  5.529690e+15    Sat3697      26.00
29      Melinda Murphy  5.489270e+15    Sat2467      22.65
30          Grant Hall  3.019650e+13    Sat4099      11.00
31      Danny Santiago  6.304160e+11    Sat4947      20.85
32       Amanda Wilson  2.131860e+14    Sat1327      18.06
33       Amber Francis  3.777430e+14    Sat6649      23.14
34      Jacob Castillo  3.551490e+15    Sat8124      21.05
35      Joseph Mullins  5.519770e+15     Sat632      27.66
36        William Ford  3.527690e+15    Sat9139      18.31
37          Erin Lewis  5.161700e+15    Sat6406      20.00
38     Brandon Bradley  4.427600e+15    Sat4056      21.00
39   Mr. Brandon Berry  6.011530e+15    Sat6373      36.27
40        Adam Edwards  3.544450e+15    Sat8549      18.28
41         David Boyer  3.536680e+15    Sun9460      20.00
42         Bryan Brown  3.623120e+13    Sun1699      17.00
43  Christopher Spears  4.387670e+15    Sun3279      11.00
44         Todd Cooper  5.038470e+11    Sun2274      36.00
45  Richard Fitzgerald  3.751570e+14    Sun8643      21.29
46      Joshua Gilmore  4.292070e+12    Sun7097      27.23
47        James Barnes  3.552000e+15    Sun9677      38.40
48       Austin Fisher  6.011480e+15    Sun4142      30.60
49        William Roth  6.573920e+15    Sun9774      21.04  >

In [123]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   total_bill        50 non-null     float64
 1   tip               50 non-null     float64
 2   sex               50 non-null     object
 3   smoker            50 non-null     object
 4   day               50 non-null     object
 5   time              50 non-null     object
 6   size              50 non-null     int64
 7   price_per_person  50 non-null     float64
 8   Payer Name        50 non-null     object
 9   CC Number         50 non-null     float64
 10  Payment ID        50 non-null     object
 11  total_amt         50 non-null     float64
dtypes: float64(5), int64(1), object(6)
memory usage: 4.8+ KB

In [125]:
#Column ADD

df.loc[:, "total_amt"] = df["total_bill"] + df["tip"]

In [126]:
df

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,total_amt
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3.560330e+15,Sun2959,18.00
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4.478070e+15,Sun4608,12.00
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6.011810e+15,Sun4458,24.51
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4.676140e+15,Sun5260,26.99
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4.832730e+15,Sun2251,28.20
5,25.29,4.71,Male,No,Sun,Dinner,4,6.32,Erik Smith,2.131400e+14,Sun9679,30.00
6,8.77,2.00,Male,No,Sun,Dinner,2,4.38,Kristopher Johnson,2.223730e+15,Sun5985,10.77
7,26.88,3.12,Male,No,Sun,Dinner,4,6.72,Robert Buck,3.514790e+15,Sun8157,30.00
8,15.04,1.96,Male,No,Sun,Dinner,2,7.52,Joseph Mcdonald,3.522870e+15,Sun6820,17.00
9,14.78,3.23,Male,No,Sun,Dinner,2,7.39,Jerome Abbott,3.532120e+15,Sun3775,18.01
10,10.27,1.71,Male,No,Sun,Dinner,2,5.14,William Riley,5.662880e+11,Sun2546,11.98
11,35.26,5.00,Female,No,Sun,Dinner,4,8.82,Diane Macias,4.577820e+15,Sun6686,40.26
12,15.42,1.57,Male,No,Sun,Dinner,2,7.71,Chad Harrington,5.770410e+11,Sun1300,16.99
13,18.43,3.00,Male,No,Sun,Dinner,4,4.61,Joshua Jones,6.011160e+15,Sun2971,21.43
14,14.83,3.02,Female,No,Sun,Dinner,2,7.42,Vanessa Jones,3.001670e+13,Sun3848,17.85
15,21.58,3.92,Male,No,Sun,Dinner,2,10.79,Matthew Reilly,1.800730e+14,Sun1878,25.50
16,10.33,1.67,Female,No,Sun,Dinner,3,3.44,Elizabeth Foster,4.240030e+15,Sun9715,12.00
17,16.29,3.71,Male,No,Sun,Dinner,3,5.43,John Pittman,6.521340e+15,Sun2998,20.00
18,16.97,3.50,Female,No,Sun,Dinner,3,5.66,Laura Martinez,3.042230e+13,Sun2789,20.47
19,20.65,3.35,Male,No,Sat,Dinner,3,6.88,Timothy Oneal,6.568070e+15,Sat9213,24.00
20,17.92,4.08,Male,No,Sat,Dinner,2,8.96,Thomas Rice,4.403300e+15,Sat1709,22.00
21,20.29,2.75,Female,No,Sat,Dinner,2,10.14,Natalie Gardner,5.448130e+15,Sat9618,23.04
22,15.77,2.23,Female,No,Sat,Dinner,2,7.88,Ashley Shelton,3.524120e+15,Sat9786,18.00
23,39.42,7.58,Male,No,Sat,Dinner,4,9.86,Lance Peterson,3.542580e+15,Sat239,47.00
24,19.82,3.18,Male,No,Sat,Dinner,2,9.91,Christopher Ross,3.673910e+13,Sat6236,23.00
25,17.81,2.34,Male,No,Sat,Dinner,4,4.45,Robert Perkins,3.050290e+13,Sat907,20.15
26,13.37,2.00,Male,No,Sat,Dinner,2,6.68,Kyle Avery,6.531340e+15,Sat6651,15.37
27,12.69,2.00,Male,No,Sat,Dinner,2,6.34,Patrick Barber,3.015560e+13,Sat394,14.69
28,21.70,4.30,Male,No,Sat,Dinner,2,10.85,David Collier,5.529690e+15,Sat3697,26.00
29,19.65,3.00,Female,No,Sat,Dinner,2,9.82,Melinda Murphy,5.489270e+15,Sat2467,22.65
30,9.55,1.45,Male,No,Sat,Dinner,2,4.78,Grant Hall,3.019650e+13,Sat4099,11.00
31,18.35,2.50,Male,No,Sat,Dinner,4,4.59,Danny Santiago,6.304160e+11,Sat4947,20.85
32,15.06,3.00,Female,No,Sat,Dinner,2,7.53,Amanda Wilson,2.131860e+14,Sat1327,18.06
33,20.69,2.45,Female,No,Sat,Dinner,4,5.17,Amber Francis,3.777430e+14,Sat6649,23.14
34,17.78,3.27,Male,No,Sat,Dinner,2,8.89,Jacob Castillo,3.551490e+15,Sat8124,21.05
35,24.06,3.60,Male,No,Sat,Dinner,3,8.02,Joseph Mullins,5.519770e+15,Sat632,27.66
36,16.31,2.00,Male,No,Sat,Dinner,3,5.44,William Ford,3.527690e+15,Sat9139,18.31
37,16.93,3.07,Female,No,Sat,Dinner,3,5.64,Erin Lewis,5.161700e+15,Sat6406,20.00
38,18.69,2.31,Male,No,Sat,Dinner,3,6.23,Brandon Bradley,4.427600e+15,Sat4056,21.00
39,31.27,5.00,Male,No,Sat,Dinner,3,10.42,Mr. Brandon Berry,6.011530e+15,Sat6373,36.27
40,16.04,2.24,Male,No,Sat,Dinner,3,5.35,Adam Edwards,3.544450e+15,Sat8549,18.28
41,17.46,2.54,Male,No,Sun,Dinner,2,8.73,David Boyer,3.536680e+15,Sun9460,20.00
42,13.94,3.06,Male,No,Sun,Dinner,2,6.97,Bryan Brown,3.623120e+13,Sun1699,17.00
43,9.68,1.32,Male,No,Sun,Dinner,2,4.84,Christopher Spears,4.387670e+15,Sun3279,11.00
44,30.40,5.60,Male,No,Sun,Dinner,4,7.60,Todd Cooper,5.038470e+11,Sun2274,36.00
45,18.29,3.00,Male,No,Sun,Dinner,2,9.14,Richard Fitzgerald,3.751570e+14,Sun8643,21.29
46,22.23,5.00,Male,No,Sun,Dinner,2,11.12,Joshua Gilmore,4.292070e+12,Sun7097,27.23
47,32.40,6.00,Male,No,Sun,Dinner,4,8.10,James Barnes,3.552000e+15,Sun9677,38.40
48,28.55,2.05,Male,No,Sun,Dinner,3,9.52,Austin Fisher,6.011480e+15,Sun4142,30.60
49,18.04,3.00,Male,No,Sun,Dinner,2,9.02,William Roth,6.573920e+15,Sun9774,21.04

##New File after update everything creating

In [129]:
df.to_csv('Newupdated_tips.csv', index=False)